Repository third-culture-software/bhima, pull requests merged in 2018-06, with the labels that each got.

#2801 fix(reports): increase preview height to 80vh
  client/src/modules/templates/bhReportPreview.tmpl.html
Labels: Refactor

#2819 fix(caution): rename variable
  server/models/procedures/invoicing.sql
Labels: Bug Fix

#2823 fix(ci): attempt to unbreak Travis
  package.json
  sh/dependencies.sh
Labels: Bug Fix

#2824 feat(patient registry) display correctly a patient records
  client/src/modules/patients/record/patient-record.ctrl.js
  client/src/modules/patients/templates/action.cell.html
Labels: Bug Fix

#2825 fix: misc presentation ui-glitches
  client/src/modules/depots/modals/depot.modal.html
  client/src/modules/locations/village/village.html
  client/src/modules/purchases/modals/search.tmpl.html
  client/src/modules/roles/modal/userRole.html
Labels: Bug Fix

#2829 fix(install): broken install page
  client/src/js/components/bhStrengthMeter.js
  client/src/js/services/PasswordMeterService.js
Labels: Bug Fix

#2833 fix(trial balance): $state and linking bugs
  client/src/js/app.js
  client/src/js/components/bhJournalLink.js
  client/src/modules/journal/trial-balance/errors.html
  client/src/modules/journal/trial-balance/errors.js
  client/src/modules/journal/trial-balance/overview.html
  client/src/modules/journal/trial-balance/overview.js
Labels: Bug Fix

#2842 feat(role managent) subselect permissions
  client/src/modules/roles/modal/rolesPermissions.html
  client/src/modules/roles/modal/rolesPermissions.js
Labels: Bug Fix

#2864 fix(navigation): do not error if no nextURL
  client/src/js/components/bhNavigation.js
Labels: Bug Fix

#2865 chore: remove ban icon from cancel buttons
  client/src/modules/services/modals/service.modal.html
  client/src/modules/users/UserCashBoxManagementModal.html
  client/src/modules/users/UserDepotManagementModal.html
Labels: Refactor

#2870 fix: broken i18n on patient group modal
  client/src/modules/patients/edit/edit.html
  client/src/modules/patients/edit/updatePatientGroups.modal.js
  client/src/modules/patients/edit/updatePatientGroups.tmpl.html
Labels: Bug Fix

#2879 feat(receipts): allow HTML printing
  client/src/css/structure.css
  client/src/i18n/en/form.json
  client/src/i18n/en/report.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/report.json
  client/src/index.html
  client/src/js/services/AppCache.js
  client/src/js/services/receipts/ReceiptModal.js
  client/src/js/services/receipts/ReceiptService.js
  client/src/js/services/receipts/modal/receiptModal.tmpl.html
  client/src/js/services/receipts/modal/receiptModalController.js
  client/src/modules/application/application.js
  client/src/modules/settings/settings.ctrl.js
  client/src/modules/settings/settings.html
  client/src/modules/settings/settings.routes.js
Labels: Refactor

#2885 fix(patient): lookup patient group price lists
  client/src/modules/inventory/list/modals/actions.tmpl.html
  client/src/modules/inventory/list/modals/search.modal.html
  client/src/modules/inventory/list/modals/search.modal.js
  client/src/modules/inventory/list/templates/action.cell.html
  server/controllers/medical/patients/index.js
Labels: Bug Fix

#2919 fix(invoice): block sales_account if id is zero
  client/src/modules/invoices/patientInvoiceItem.service.js
Labels: Bug Fix

#2893 fix(GeneralLedger): totals are toFixed(2)
  client/src/modules/general-ledger/general-ledger.ctrl.js
  client/src/modules/general-ledger/general-ledger.service.js
  server/config/routes.js
  server/controllers/finance/generalLedger/index.js
  test/integration/generalLedger.js
  test/integration/journal.js
  test/integration/trialBalance.js
Labels: Bug Fix

#2936 fix(filters): use Date() parsing for dates
  server/lib/filter.js
Labels: Refactor, performance

#2913 fix(operating report): update presentation
  client/src/modules/reports/generate/operating/operating.html
  server/controllers/finance/reports/operating/index.js
  server/controllers/finance/reports/operating/report.handlebars
Labels: Bug Fix

#2871 chore: remove Modal.confirm() from Credit Note
  client/src/modules/invoices/registry/modalCreditNote.html
  client/src/modules/invoices/registry/modalCreditNote.js
  client/src/modules/invoices/registry/registry.js
  server/controllers/finance/cash.js
Labels: Refactor

#2922 refactor(Employee and Patient Standing Report)
  server/controllers/finance/reports/financial.employee.handlebars
Labels: Refactor

#2944 bug(Paiement Convention)
  server/controllers/finance/debtors/groups/index.js
Labels: Bug Fix

#2948 fix(General Ledger): ignore empty rows correctly
  client/src/modules/general-ledger/general-ledger.ctrl.js
  client/src/modules/general-ledger/general-ledger.html
  client/src/modules/general-ledger/general-ledger.service.js
  server/controllers/finance/generalLedger/index.js
  server/controllers/finance/reports/generalLedger/index.js
  server/controllers/finance/reports/generalLedger/report.handlebars
Labels: Bug Fix
