Repository third-culture-software/bhima, pull requests merged in 2018-11, with the labels that each got.

#3317 deps: bump ui-grid
  bower.json
Labels: Bug Fix

#3316 fix(cashboxes): load currency modal despite error
  client/src/modules/cash/cashboxes/configure_currency/modal.js
  client/src/modules/cash/cashboxes/update/update.js
Labels: Bug Fix

#3326 deps: remove unused dependencies
  package.json
Labels: chore, dependencies

#3336 fix: remove done() calls from native promises
  server/controllers/medical/patients/index.js
  server/controllers/report.js
  test/integration/barcodes.js
Labels: Bug Fix

#3338 chore(accounts): rewrite end to end tests
  client/src/modules/account_reference/templates/action.cell.html
  client/src/modules/accounts/accounts.js
  client/src/modules/accounts/templates/grid.actionsCell.tmpl.html
  client/src/modules/accounts/templates/grid.indentCell.tmpl.html
  client/src/modules/accounts/templates/grid.leafRow.tmpl.html
  protractor.conf.js
  test/end-to-end/accounts/accounts.page.js
  test/end-to-end/accounts/accounts.spec.js
  test/end-to-end/shared/GridRow.js
Labels: tests

#3345 chore(roles): remove project_id from roles
  client/src/modules/roles/modal/userRole.js
  client/src/modules/roles/roles.ctrl.js
  client/src/modules/roles/roles.service.js
  server/config/routes.js
  server/controllers/admin/roles.js
  server/models/migrations/v0.8.0-v0.9.0/migrate.sql
  server/models/schema.sql
  test/data.sql
  test/integration/role.js
Labels: chore

#3346 refactor(Account References): rewrite tests
  client/src/modules/account_reference/account_reference.modal.html
  client/src/modules/account_reference/templates/action.cell.html
  test/end-to-end/account-reference/account-reference.cu.page.js
  test/end-to-end/account-reference/account-reference.page.js
  test/end-to-end/account-reference/account-reference.spec.js
Labels: Refactor, tests

#3357 feat(user registry) add roles column
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/users/users.js
  server/controllers/admin/users/index.js
Labels: Feature Request

#3362 Fix trailing comma on user roles concatenation
  server/controllers/admin/users/index.js
Labels: Bug Fix

#3344 fix(transaction type): rm async/await from client
  client/src/modules/transaction-type/transaction-type.ctrl.js
  server/models/bhima.sql
Labels: Bug Fix

#3356 test(weekend): rewrite weekend end to end tests
  client/src/js/components/bhWeekConfigSelect.js
  client/src/modules/payroll/modals/payroll.modal.html
  client/src/modules/payroll/modals/payroll.modal.js
  client/src/modules/payroll/weekend_configuration/configuration.html
  client/src/modules/payroll/weekend_configuration/configuration.js
  client/src/modules/payroll/weekend_configuration/configuration.routes.js
  client/src/modules/payroll/weekend_configuration/configuration.service.js
  client/src/modules/payroll/weekend_configuration/modals/config.modal.html
  client/src/modules/payroll/weekend_configuration/modals/config.modal.js
  client/src/modules/payroll/weekend_configuration/modals/weekEnd.modal.html
  client/src/modules/payroll/weekend_configuration/modals/weekEnd.modal.js
  client/src/modules/payroll/weekend_configuration/templates/action.tmpl.html
  client/src/modules/templates/bhWeekendConfigSelect.tmpl.html
  test/end-to-end/weekendConfig/weekend_config.page.js
  test/end-to-end/weekendConfig/weekend_config.spec.js
Labels: Refactor, tests

#3360 test(PasswordMeterService): add unit tests
  client/src/js/services/PasswordMeterService.js
  test/client-unit/services/PasswordMeterService.spec.js
Labels: tests

#3358 test(grades): rewrite grade management e2e test
  client/src/modules/grades/grades.html
  client/src/modules/grades/grades.js
  client/src/modules/grades/modals/grade.modal.html
  client/src/modules/grades/templates/action.tmpl.html
  test/end-to-end/grades/grades.page.js
  test/end-to-end/grades/grades.spec.js
Labels: Refactor, tests

#3355 test(Job Titles): rewrite end to end tests
  client/src/modules/functions/functions.html
  client/src/modules/functions/functions.js
  client/src/modules/functions/modals/function.modal.html
  client/src/modules/functions/modals/function.modal.js
  client/src/modules/functions/templates/action.tmpl.html
  test/end-to-end/functions/functions.page.js
  test/end-to-end/functions/functions.spec.js
Labels: Refactor, tests

#3371 fix(install): do not use project_id for role
  server/controllers/install.js
  server/models/procedures/roles.sql
Labels: Bug Fix

#3373 improvement(Rubric Paiement)
  server/models/migrations/v0.8.0-v0.9.0/migrate.sql
  server/models/schema.sql
Labels: Bug Fix

#3392 fix(tests): remove .only() preventing e2e tests
  test/end-to-end/distributionFeesCenters/distribution_key.spec.js
Labels: Bug Fix

#3394 fix(vouchers): complete i18n translations
  client/src/i18n/en/vouchers.json
  client/src/i18n/fr/vouchers.json
Labels: Bug Fix, Refactor

#3399 feat: add search by description to registries
  client/src/modules/cash/cash.service.js
  client/src/modules/cash/payments/templates/search.modal.html
  client/src/modules/cash/payments/templates/search.modal.js
  client/src/modules/invoices/patientInvoice.service.js
  client/src/modules/invoices/registry/registry.js
  client/src/modules/invoices/registry/search.modal.html
  client/src/modules/invoices/registry/search.modal.js
  server/controllers/finance/cash.js
  server/controllers/finance/patientInvoice.js
  test/integration/cash.search.js
  test/integration/patientInvoice.js
Labels: Feature Request
