Repository third-culture-software/bhima, pull requests merged in 2018-03, with the labels that each got.

#2603 fix(ci): remove gecko from webdriver
  sh/dependencies.sh
Labels: Bug Fix, tests

#2579 feat(General Ledger): add totals on PDF printout
  server/controllers/finance/reports/generalLedger/index.js
  server/controllers/finance/reports/generalLedger/report.handlebars
  server/lib/Tree.js
Labels: Refactor

#2589 chore(*): add timestamps to main tables
  server/models/schema.sql
Labels: Breaking Change, Refactor

#2592 fix(Trial Balance): show loading indicator
  client/src/modules/journal/trial-balance/errors.js
  client/src/modules/journal/trial-balance/overview.js
  client/src/modules/journal/trial-balance/trial-balance.ctrl.js
Labels: Bug Fix

#2587 fix(bhNavigation): update tree on navigation delta
  client/src/js/components/bhNavigation.js
  client/src/modules/templates/navigation.tmpl.html
Labels: Bug Fix

#2606 feat(voucherregistry) formating transaction type
  client/src/modules/vouchers/modals/search.modal.js
Labels: Bug Fix

#2611 fix(reports): incorrect footer account statement
  server/controllers/finance/reports/account_statement/index.js
  server/controllers/finance/reports/reportAccounts/index.js
Labels: Bug Fix

#2608 refractor(stok managent) improvements
  client/src/i18n/en/depot.json
  client/src/i18n/fr/depot.json
  client/src/modules/stock/depot-selection.modal.html
  client/src/modules/stock/entry/entry.html
  client/src/modules/stock/entry/entry.js
  client/src/modules/stock/exit/exit.html
  client/src/modules/stock/exit/exit.js
  client/src/modules/stock/lots/modals/search.modal.html
  client/src/modules/stock/lots/modals/search.modal.js
  client/src/modules/stock/lots/registry.js
  test/end-to-end/shared/search.page.js
  test/end-to-end/stock/stock.lots.spec.js
  test/integration/stock.js
Labels: needs tests

#2610 refactor(vouchers): polish registry
  client/src/modules/vouchers/templates/action.cell.html
  client/src/modules/vouchers/voucher-registry.ctrl.js
  client/src/modules/vouchers/voucher-registry.html
Labels: Refactor

#2616 fix: correct filter display values
  client/src/js/services/util.js
  client/src/modules/cash/payments/templates/search.modal.js
  client/src/modules/invoices/registry/search.modal.js
  client/src/modules/patients/registry/search.modal.js
  client/src/modules/vouchers/modals/search.modal.js
Labels: Bug Fix

#2626 feat(journal) change origin_id to transaction_type_id
  client/src/modules/account_statement/account_statement.ctrl.js
  client/src/modules/account_statement/account_statement.service.js
  client/src/modules/journal/journal.js
  client/src/modules/journal/journal.service.js
  client/src/modules/journal/modals/editTransaction.modal.html
  client/src/modules/journal/modals/editTransaction.modal.js
  client/src/modules/journal/modals/search.modal.html
  client/src/modules/journal/modals/search.modal.js
  client/src/modules/journal/templates/transaction_type.edit.html
  client/src/modules/journal/templates/transaction_type.html
  server/controllers/finance/generalLedger/index.js
  server/controllers/finance/journal/index.js
  server/controllers/finance/ledgers/general.js
  server/controllers/finance/reports/cashReport/index.js
  server/controllers/finance/reports/cashflow/index.js
  server/models/procedures/cash.sql
  server/models/procedures/invoicing.sql
  server/models/procedures/trial_balance.sql
  server/models/procedures/voucher.sql
  server/models/schema.sql
  test/development-build.sql
Labels: Breaking Change, Refactor
