Repository third-culture-software/bhima, pull requests merged in 2018-12, with the labels that each got.

#3416 feat(Trial Balance): group by account type
  client/src/i18n/en/posting_journal.json
  client/src/i18n/fr/posting_journal.json
  client/src/modules/journal/trial-balance/overview.html
  client/src/modules/journal/trial-balance/overview.js
  client/src/modules/journal/trial-balance/overview.subgrid.html
  client/src/modules/journal/trial-balance/trial-balance.service.js
  server/models/procedures/trial_balance.sql
  test/client-unit/services/TrialBalance.spec.js
Labels: Feature Request

#3451 fix: parse project abbr to get transaction length
  server/models/functions.sql
  server/models/procedures.sql
  server/models/procedures/cash.sql
  server/models/procedures/invoicing.sql
  server/models/procedures/voucher.sql
Labels: Bug Fix

#3452 test(util): add unit tests for filterFormElements
  test/client-unit/services/util.spec.js
Labels: tests

#3467 refactor(bhStockEntryExitType): rewrite component
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/js/components/bhStockEntryExitType.js
  client/src/modules/stock/StockEntryExitType.service.js
  client/src/modules/templates/bhStockEntryExitType.tmpl.html
Labels: Refactor

#3475 feat(invoice payment) display debtor remaining balance
  server/controllers/finance/reports/cash/index.js
Labels: Bug Fix

#3480 fix(tests): run full E2E test suite
  client/src/modules/inventory/inventory.routes.js
  client/src/modules/inventory/list/modals/actions.tmpl.html
  test/end-to-end/enterprises/enterprises.spec.js
  test/end-to-end/inventory/list.spec.js
  test/end-to-end/stock/stock.assign.spec.js
Labels: Bug Fix

#3481 docs: add gh-pages scaffold
  client/src/modules/subsidies/subsidies.html
  docs/INSTALL.md
  docs/finance/account-statement.md
  docs/finance/accounts.md
  docs/finance/bookkeeping/cash-payments.md
  docs/finance/bookkeeping/patient-invoices.md
  docs/finance/bookkeeping/vouchers.md
  docs/finance/fiscal-year.md
  docs/finance/general-ledger.md
  docs/finance/index.md
  docs/finance/journal/editing-transactions.md
  docs/finance/journal/trial-balance.md
  docs/finance/overview.md
  docs/finance/posting-journal
  docs/for-developers/installing-bhima.md
  docs/grid-features/column-sorting.md
  docs/grid-features/data-exporting.md
  docs/grid-features/data-filtering.md
  docs/grid-features/inline-filtering.md
  docs/grid-features/row-selection.md
  docs/grid-features/saving-changes.md
  docs/index.md
  docs/medical-records/patient-groups.md
  docs/medical-records/patient-registration.md
  docs/stock-management/overview.md
Labels: documentation

#3485 fix(docs): add CNAME to top level
  CNAME
Labels: documentation

#3486 fix(patients): fix update patient entity map
  client/src/js/services/grid/GridSorting.js
  server/controllers/medical/patients/index.js
Labels: Bug Fix

#3492 fix(reports): clarify i18n translations
  client/src/i18n/en/report.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/report.json
  client/src/modules/reports/generate/income_expense/income_expense.html
  client/src/modules/reports/generate/income_expense_by_month/income_expense_by_month.config.js
  client/src/modules/reports/generate/income_expense_by_month/income_expense_by_month.html
  client/src/modules/reports/generate/income_expense_by_year/income_expense_by_year.html
  server/controllers/finance/reports/income_expense/report.handlebars
  server/controllers/finance/reports/income_expense_by_month/report.handlebars
  server/controllers/finance/reports/income_expense_by_year/report.handlebars
Labels: Refactor

#3495 fix(vouchers): don't make 300 rows on import
  client/src/js/components/bhAccountTypeaheadInline.js
  client/src/modules/vouchers/complex-voucher.ctrl.js
Labels: Bug Fix

#3496 fix(reports): rewrite multiple account statement
  client/src/i18n/en/tree.json
  server/controllers/finance/accounts/extra.js
  server/controllers/finance/reports/reportAccountsMultiple/index.js
  server/controllers/finance/reports/reportAccountsMultiple/report.handlebars
  server/lib/renderers/xls.js
Labels: Bug Fix
