Repository third-culture-software/bhima, pull requests merged in 2018-08, with the labels that each got.

#3009 feat(patients): filter registry by barcode
  client/src/js/services/BarcodeService.js
  client/src/modules/patients/patients.service.js
  client/src/modules/patients/registry/registry.html
  client/src/modules/patients/registry/registry.js
  client/src/modules/templates/barcode-scanner-modal.ctrl.js
  client/src/modules/templates/barcode-scanner-modal.html
  client/src/modules/templates/bhSnapShot.html
  server/controllers/medical/patients/index.js
  test/client-unit/components/bhBarcoderScanner.spec.js
Labels: Feature Request

#3022 fix: add typings for es6 + DOM
  gulpfile.js
Labels: Bug Fix

#3051 fix(patients): typo in display name trim()
  server/controllers/medical/patients/index.js
  server/controllers/payroll/employees/index.js
  test/integration/patients.js
Labels: Bug Fix

#3052 fix(vouchers): close barcode modal after hit
  client/src/modules/vouchers/complex-voucher.ctrl.js
  client/src/modules/vouchers/modals/scanBarcode.modal.js
  client/src/modules/vouchers/vouchers.routes.js
Labels: Bug Fix

#3019 chore: clean up roles code
  client/src/modules/roles/create.html
  client/src/modules/roles/create.js
  client/src/modules/roles/modal/roleActions.html
  client/src/modules/roles/roles.ctrl.js
  client/src/modules/roles/roles.html
  client/src/modules/roles/roles.service.js
  client/src/modules/roles/templates/action.tmpl.html
  server/controllers/admin/roles.js
  test/end-to-end/user/roles.page.js
  test/end-to-end/user/roles.spec.js
Labels: Refactor

#3077 deps: bump client dependencies
  bower.json
Labels: dependencies

#3066 fix(patient): add extra info to thermal receipt
  server/controllers/medical/reports/patient.pos.handlebars
Labels: client request

#3026 chore: update debtors client to pass eslint
  client/src/modules/debtors/debtor.routes.js
  client/src/modules/debtors/debtor.service.js
  client/src/modules/debtors/groups.create.js
  client/src/modules/debtors/groups.js
  client/src/modules/debtors/groups.service.js
  client/src/modules/debtors/groups.update.html
  client/src/modules/debtors/groups.update.js
  client/src/modules/debtors/invoicingFeeSubscriptions.js
  client/src/modules/debtors/subsidySubscriptions.js
  test/end-to-end/vouchers/complex.spec.js
Labels: Refactor

#3084 test(Configuration Rubric Service)
  client/src/modules/payroll/rubric_configuration/configuration.service.js
  server/controllers/payroll/rubricConfig/index.js
  test/client-unit/services/rubricsConfigurationService.spec.js
  test/integration/rubrics.js
Labels: tests

#3045 fix(reports): polish P&L Statement
  client/src/i18n/en/errors.json
  client/src/i18n/fr/errors.json
  server/controllers/finance/reports/income_expense/index.js
  server/controllers/finance/reports/income_expense/report.handlebars
Labels: Bug Fix

#3098 Fix Journal Search: Full Transactions (3055)
  client/src/modules/journal/modals/search.modal.html
  test/end-to-end/journal/journal.config.js
  test/end-to-end/journal/journal.page.js
Labels: Bug Fix, tests

#3097 Fix bh-currency-select unhandled error logging
  client/src/js/components/bhCurrencySelect.js
Labels: Bug Fix, Refactor

#3065 test(ExchangeRate): write client unit tests
  test/client-unit/services/ExchangeRateService.spec.js
Labels: tests

#3104 fix fiscal year list pagination
  client/src/modules/fiscal/fiscal.list.html
Labels: Bug Fix

#3094 fix: migrate to utf8mb4
  server/lib/barcode.js
  server/lib/db/index.js
  server/models/bhima.sql
  server/models/functions.sql
  server/models/icd10.sql
  server/models/procedures.sql
  server/models/procedures/account.sql
  server/models/procedures/inventory.sql
  server/models/schema.sql
  server/models/triggers.sql
  sh/build-database.sh
  test/data.sql
  test/end-to-end/verificationLinks/verificationLinks.spec.js
Labels: Best Practice, Breaking Change

#3105 chore: remove Topic
  client/src/js/services/System.js
  package.json
  server/config/routes.js
  server/controllers/admin/locations.js
  server/controllers/admin/services.js
  server/controllers/admin/suppliers.js
  server/controllers/admin/users/index.js
  server/controllers/auth.js
  server/controllers/finance/cash.create.js
  server/controllers/finance/cashboxes/currencies.js
  server/controllers/finance/cashboxes/index.js
  server/controllers/medical/patientGroups.js
  server/controllers/medical/patients/documents.js
  server/controllers/medical/patients/groups.js
  server/controllers/medical/patients/index.js
  server/controllers/payroll/employees/index.js
  server/controllers/system.js
  yarn.lock
Labels: Refactor
