Repository third-culture-software/bhima, pull requests merged in 2018-09, with the labels that each got.

#3133 Fix `bhFindPatient` expose API exception
  client/src/js/components/bhFindPatient.js
Labels: Bug Fix

#3116 Fix partial path matching on client side authorisation (3114)
  client/src/js/app.js
Labels: Bug Fix

#3147 (Low Priority) Chore: minor tweaks to ui standards
  client/src/modules/cash/cashboxes/cashboxes.html
  client/src/modules/cash/cashboxes/cashboxes.js
  client/src/modules/cash/cashboxes/cashboxes.routes.js
  client/src/modules/cash/cashboxes/configure_currency/modal.js
  client/src/modules/cash/cashboxes/update/edit.html
  client/src/modules/cash/cashboxes/update/update.js
Labels: chore

#3156 Fix simple vouchers state transition to patient debt transfer tool
  client/src/modules/vouchers/simple-voucher.ctrl.js
  client/src/modules/vouchers/simple-voucher.html
Labels: Bug Fix

#3163 Fix build process: Glyphicon path issue and corrupt css minification
  client/src/index.html
  gulpfile.js
Labels: Bug Fix

#3162 Fix invoice item validation CSS animation
  client/src/css/structure.css
Labels: Bug Fix

#3158 use date string for avoiding timezone info on fiscal year date range
  client/src/modules/fiscal/fiscal.manage.js
Labels: Bug Fix

#3171 fix(user): add clarity to user fields
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/templates/messages.tmpl.html
  client/src/modules/users/user.modal.html
Labels: Bug Fix, Refactor

#3170 chore: collapse migrations scripts into one
  server/models/Update/add_account_reference_module.sql
  server/models/Update/add_ohada_balance_sheet.sql
  server/models/Update/add_prepayment_inside_invoice.sql
  server/models/Update/rework_buid_as_hex.sql
  server/models/migrations/v0.8.0-v0.9.0/migrate.sql
Labels: Refactor

#3181 fix async validation in bhFindInvoice
  client/src/js/components/bhFindInvoice.js
  client/src/modules/stock/exit/exit.js
Labels: Bug Fix

#3183 fix(reports): translate P&L
  client/src/i18n/fr/report.json
Labels: Bug Fix
