Repository third-culture-software/bhima, pull requests merged in 2018-04, with the labels that each got.

#2656 refactor: remove NodeTreeService
  client/src/js/services/NodeTreeService.js
Labels: Refactor

#2649 chore: remove SearchFilterService
  client/src/js/services/FilterService.js
  client/src/js/services/SearchFilterService.js
Labels: Refactor

#2640 deps: use @ima-worldhealth/topic
  package.json
  server/controllers/admin/locations.js
  server/controllers/admin/services.js
  server/controllers/admin/suppliers.js
  server/controllers/admin/users/index.js
  server/controllers/auth.js
  server/controllers/finance/cash.create.js
  server/controllers/finance/cashboxes/currencies.js
  server/controllers/finance/cashboxes/index.js
  server/controllers/medical/patientGroups.js
  server/controllers/medical/patients/documents.js
  server/controllers/medical/patients/groups.js
  server/controllers/medical/patients/index.js
  server/controllers/payroll/employees/index.js
  server/controllers/system.js
  server/lib/topic.js
  test/server-unit/topic.spec.js
  yarn.lock
Labels: dependencies

#2664 fix(bhPDFPrint): anticipate memory leak
  .gitignore
  client/src/js/components/bhPDFPrint.js
Labels: Bug Fix, Refactor

#2674 chore(stock): clean up stock modules
  client/src/modules/stock/StockEntryExitType.service.js
  client/src/modules/stock/StockForm.service.js
  client/src/modules/stock/StockItem.service.js
  client/src/modules/stock/adjustment/adjustment.html
  client/src/modules/stock/adjustment/adjustment.js
  client/src/modules/stock/depot-selection.ctrl.js
  client/src/modules/stock/entry/entry.js
  client/src/modules/stock/exit/exit.js
  client/src/modules/stock/inventories/registry.js
  client/src/modules/stock/stock.service.js
Labels: Refactor

#2689 ci: bail protractor on errors
  protractor.conf.js
Labels: tests

#2705 chore: remove yarn error log
  .gitignore
  yarn-error.log
Labels: Build Process, dependencies

#2712 fix(depots): address flaky tests
  client/src/js/components/bhLocationSelect.js
  client/src/modules/depots/modals/depot.modal.html
  client/src/modules/depots/modals/depot.modal.js
  client/src/modules/depots/templates/action.tmpl.html
  client/src/modules/depots/templates/warehouse.tmpl.html
  protractor.conf.js
  server/controllers/inventory/depots/index.js
  test/end-to-end/depots/depots.page.js
  test/end-to-end/depots/depots.spec.js
  test/end-to-end/shared/GridRow.js
  test/end-to-end/user/user.page.js
  test/end-to-end/user/user.spec.js
  test/end-to-end/user/userCU.page.js
  test/end-to-end/weekendConfig/weekend_config.page.js
  test/end-to-end/weekendConfig/weekend_config.spec.js
Labels: Bug Fix

#2696 refractor(bhDateEditor component) add allow-future-date flag
  client/src/js/components/bhDateEditor.js
  client/src/modules/cash/cash.html
  client/src/modules/enterprises/exchange/exchange.modal.html
  client/src/modules/invoices/patientInvoice.html
  client/src/modules/purchases/create/create.html
  client/src/modules/stock/adjustment/adjustment.html
  client/src/modules/stock/entry/entry.html
  client/src/modules/stock/entry/entry.js
  client/src/modules/stock/exit/exit.html
  client/src/modules/vouchers/complex-voucher.html
  client/src/modules/vouchers/simple-voucher.html
  test/client-unit/components/bhDateEditor.spec.js
Labels: needs tests

#2699 fix(invoice): use invoicing fees
  client/src/modules/invoices/templates/grid/code.tmpl.html
  client/src/modules/templates/bhFindPatient.tmpl.html
  server/controllers/finance/invoice/patientInvoice.create.js
  test/integration/patientInvoice.js
Labels: Bug Fix
