Repository third-culture-software/bhima, pull requests merged in 2018-10, with the labels that each got.

#3216 test(bhFilterToggle): write client-unit test
  client/src/js/components/bhFilterToggle.js
  client/src/modules/templates/bhFilterToggle.tmpl.html
  test/client-unit/components/bhFilterToggle.spec.js
Labels: Refactor, tests

#3217 chore: lint client components
  client/src/js/components/bhAccountConfigSelect.js
  client/src/js/components/bhAccountSelect.js
  client/src/js/components/bhAccountSelectMultiple.js
  client/src/js/components/bhCashboxSelect.js
  client/src/js/components/bhClear.js
  client/src/js/components/bhCurrencyInput.js
  client/src/js/components/bhDebtorGroupSelect.js
  client/src/js/components/bhEmployeeSelect.js
  client/src/js/components/bhExchangeRate.js
  client/src/js/components/bhFonctionSelect.js
  client/src/js/components/bhGradeSelect.js
  client/src/js/components/bhGridLoadingIndicator.js
  client/src/js/components/bhHiddenField.js
  client/src/js/components/bhInfo.js
  client/src/js/components/bhInventoryGroupSelect.js
  client/src/js/components/bhInventoryTypeSelect.js
  client/src/js/components/bhIprConfigSelect.js
  client/src/js/components/bhIprScale.js
  client/src/js/components/bhJournalLink.js
  client/src/js/components/bhLoadingButton.js
  client/src/js/components/bhLocationSelect.js
  client/src/js/components/bhMultipleDebtorGroupSelect.js
  client/src/js/components/bhMultipleDepotSelect.js
  client/src/js/components/bhPatientFinancialActivity.js
  client/src/js/components/bhPatientGroupSelect.js
  client/src/js/components/bhPurchaseStatusSelect.js
  client/src/js/components/bhReceipt.js
  client/src/js/components/bhReceiptCurrency.js
  client/src/js/components/bhReferenceLink.js
  client/src/js/components/bhReportSource.js
  client/src/js/components/bhRubricConfigSelect.js
  client/src/js/components/bhServiceSelect.js
  client/src/js/components/bhSupplierSelect.js
  client/src/js/components/bhUserSelect.js
  client/src/js/components/bhWeekConfigSelect.js
Labels: Refactor

#3227 feat(report) rename archive file
  server/controllers/report.js
Labels: Bug Fix

#3208 fix(fiscal): fix fiscal year loading error
  client/src/modules/fiscal/fiscal.js
  client/src/modules/fiscal/fiscal.list.html
Labels: Bug Fix

#3238 feat(voucher receipt) signal if it's canceled
  server/controllers/finance/reports/vouchers/index.js
  server/controllers/finance/reports/vouchers/receipt.handlebars
Labels: Feature Request

#3250 feat(bhInventorySelect): add code to search params
  client/src/js/components/bhInventorySelect.js
  client/src/modules/templates/bhInventorySelect.tmpl.html
Labels: Feature Request

#3249 chore(inventory): lint client modules
  client/src/modules/inventory/InventoryStoreService.js
  client/src/modules/inventory/configuration/groups/groups.js
  client/src/modules/inventory/configuration/groups/groups.service.js
  client/src/modules/inventory/configuration/types/types.js
  client/src/modules/inventory/configuration/types/types.service.js
  client/src/modules/inventory/configuration/units/units.js
  client/src/modules/inventory/configuration/units/units.service.js
  client/src/modules/inventory/inventory.routes.js
  client/src/modules/inventory/list/modals/actions.modal.js
  client/src/modules/inventory/list/modals/search.modal.js
Labels: Refactor

#3222 feat(report) stock value report
  client/src/i18n/en/report.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/tree.json
  client/src/modules/reports/generate/stock_value/stock_value.config.js
  client/src/modules/reports/generate/stock_value/stock_value.html
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/value.js
  server/controllers/stock/reports/stock_value.report.handlebars
  server/lib/template/partials/header.handlebars
  server/models/bhima.sql
  server/models/migrations/v0.8.0-v0.9.0/migrate.sql
  server/models/procedures/stock.sql
Labels: report

#3253 chore: add i18n keys
  client/src/i18n/en/form.json
  client/src/i18n/en/report.json
  client/src/i18n/fr/form.json
  server/models/bhima.sql
Labels: Refactor

#3255 deps: bump angular version
  bower.json
Labels: dependencies

#3271 fix: cross-env-shell on windows
  package.json
Labels: Bug Fix

#3275 fix(bhPeriodSelection): timezone insensitivity
  client/src/js/components/bhPeriodSelection.js
Labels: Bug Fix

#3276 refactor(general-ledger): better hide title accounts
  client/src/modules/general-ledger/general-ledger.ctrl.js
  client/src/modules/general-ledger/general-ledger.html
  client/src/modules/templates/modals/export.modal.js
Labels: Refactor

#3286 Update Travis CI to use Node v10
  .travis.yml
Labels: Bug Fix

#3293 fix(journal): edit transaction exchange bug
  server/controllers/finance/journal/index.js
Labels: Bug Fix
