Repository third-culture-software/bhima, pull requests merged in 2019-10, with the labels that each got.

#3910 test(csv): add unit tests for CSV renderer
  server/controllers/finance/reports/account_statement/index.js
  server/controllers/finance/reports/journal/index.js
  server/controllers/finance/reports/priceList/index.js
  server/lib/renderers/csv.js
  test/server-unit/csv.spec.js
  test/server-unit/xlsx.spec.js
  yarn.lock
Labels: size: XL, tests

#3913 Use of report key in cronEmailReport components
  client/src/i18n/fr/tree.json
  client/src/js/components/bhCronEmailReport/bhCronEmailReport.js
  client/src/modules/reports/baseReports.service.js
  client/src/modules/reports/generate/balance_report/balance_report.html
  client/src/modules/reports/generate/cashflow/cashflow.html
  client/src/modules/reports/generate/ohada_balance_sheet_report/ohada_balance_sheet_report.html
  client/src/modules/reports/generate/ohada_profit_loss/ohada_profit_loss.html
  client/src/modules/reports/generate/operating/operating.html
  client/src/modules/reports/generate/stock_value/stock_value.html
  client/src/modules/reports/generate/unpaid-invoice-payments/unpaid-invoice-payments.html
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: size: XL

#3911 feat(report) sytem usage stat
  client/src/i18n/en/form.json
  client/src/i18n/en/report.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/report.json
  client/src/modules/reports/generate/systemUsageStat/systemUsageStat.config.js
  client/src/modules/reports/generate/systemUsageStat/systemUsageStat.html
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/finance/reports/sytemUsage/index.js
  server/controllers/finance/reports/sytemUsage/system.usage.handlebars
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: has conflicts, size: XL

#3884 chore(ci): run integration tests on Appveyor
  .appveyor.yml
  .travis.yml
Labels: size: XS, tests

#3899 fix(util): minor typo in calculate age
  server/controllers/finance/reports/unpaid-invoice-payments/index.js
  server/lib/util.js
  test/server-unit/util.spec.js
Labels: Bug Fix, size: M

#3928 chore: migrate to bhFilterToggle
  client/src/modules/department/department.ctrl.js
  client/src/modules/department/department.html
  client/src/modules/depots/depots.html
  client/src/modules/depots/depots.js
  client/src/modules/general-ledger/general-ledger.ctrl.js
  client/src/modules/general-ledger/general-ledger.html
  client/src/modules/services/services.html
  client/src/modules/services/services.js
Labels: Refactor, chore, size: L

#3921 chore(inventory): use async/await for import logic
  server/controllers/inventory/import/index.js
Labels: Refactor, size: L

#3932 Release 1.6.0
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/next/migrations.sql
  server/models/migrations/v1.5.0-v1.6.0/fix-imck-unit.sql
  server/models/migrations/v1.5.0-v1.6.0/fix-vanga-unit.sql
  server/models/migrations/v1.5.0-v1.6.0/migrate.sql
Labels: size: XL

#3933 chore: bump dependencies
  yarn.lock
Labels: chore, size: XL

#3936 fix(stock): do not submit adjustments on btn
  client/src/modules/stock/StockForm.service.js
  client/src/modules/stock/adjustment/adjustment.html
  client/src/modules/stock/adjustment/adjustment.js
  docs/en/stock-management/index.md
  server/controllers/stock/lots.js
Labels: Bug, Bug Fix, size: XL

#3942 fix(schema): add in missing fields in stock management
  server/models/migrations/next/migrate.sql
Labels: Bug Fix, size: S

#3938 chore(stock): simplify stock core logic
  server/controllers/stock/core.js
  server/models/schema.sql
Labels: Refactor, size: XL

#3944 chore(schema): migrate.sql for stock_consumption
  server/models/migrations/next/migrate.sql
Labels: chore, size: S

#3930 feat(install) add password meter
  client/src/js/components/bhStrengthMeter.js
  client/src/js/services/PasswordMeterService.js
  client/src/modules/install/install.html
  client/src/modules/install/install.js
  client/src/modules/users/UserEditPasswordModal.html
  test/client-unit/services/PasswordMeterService.spec.js
Labels: Feature Request, size: L

#3954 chore(ci): bump testing versions to latest LTS
  .appveyor.yml
  .travis.yml
Labels: size: XS, tests

#3953 Feat(Stock exit) add barcode to receipts
  server/controllers/stock/reports/stock/exit_depot_receipt.js
  server/controllers/stock/reports/stock/exit_loss_receipt.js
  server/controllers/stock/reports/stock/exit_patient_receipt.js
  server/controllers/stock/reports/stock/exit_service_receipt.js
  server/controllers/stock/reports/stock_exit_depot.receipt.handlebars
  server/controllers/stock/reports/stock_exit_loss.receipt.handlebars
  server/controllers/stock/reports/stock_exit_patient.receipt.handlebars
  server/controllers/stock/reports/stock_exit_service.receipt.handlebars
Labels: Feature Request, size: L

#3960 docs(stock): enrich stock management text
  docs/en/stock-management/index.md
  docs/en/stock-management/overview.md
Labels: documentation, size: M

#3951 refactor(bhFiscalYearPeriodSelect): replace custom logic with two components
  client/src/js/components/bhFiscalYearPeriodSelect/bhFiscalYearPeriodSelect.html
  client/src/js/components/bhFiscalYearPeriodSelect/bhFiscalYearPeriodSelect.js
  test/end-to-end/indicators_files/indicators_files.spec.js
  test/end-to-end/shared/components/bhFiscalYearPeriodSelect.js
  yarn.lock
Labels: Refactor, size: XL

#3961 fix(purchases): render enterprise currency
  server/controllers/inventory/reports/purchases.receipt.handlebars
  server/controllers/inventory/reports/purchases.receipt.js
Labels: Bug, Bug Fix, size: M
