Repository third-culture-software/bhima, pull requests merged in 2019-08, with the labels that each got.

#3794 (cron job) add cron email component to main reports
  client/src/modules/reports/generate/annual-clients-report/annual-clients-report.html
  client/src/modules/reports/generate/annual-clients-report/annual-clients-report.js
  client/src/modules/reports/generate/cashflow/cashflow.config.js
  client/src/modules/reports/generate/cashflow/cashflow.html
  client/src/modules/reports/generate/stock_value/stock_value.config.js
  client/src/modules/reports/generate/stock_value/stock_value.html
  client/src/modules/reports/generate/unpaid-invoice-payments/unpaid-invoice-payments.config.js
  client/src/modules/reports/generate/unpaid-invoice-payments/unpaid-invoice-payments.html
  server/controllers/finance/reports/cashflow/index.js
  server/controllers/finance/reports/debtors/annual-clients-report.js
  server/controllers/finance/reports/index.js
  server/controllers/finance/reports/unpaid-invoice-payments/index.js
  server/controllers/report.handlers.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/value.js
  yarn.lock
Labels: has conflicts, size: XL

#3825 fix (Invoicing Bug)
  server/controllers/finance/debtors/index.js
  server/controllers/finance/patientInvoice.js
Labels: size: S

#3827 feat(report) debtor summary report
  client/src/i18n/en/report.json
  client/src/i18n/fr/report.json
  client/src/modules/reports/generate/debtorSummary/debtorSummary.config.js
  client/src/modules/reports/generate/debtorSummary/debtorSummary.html
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/finance/reports/debtors/summaryReport.handlebars
  server/controllers/finance/reports/debtors/summaryReport.js
  server/models/bhima.sql
  server/models/migrations/next/migrations.sql
Labels: size: XL

#3832 fix(Calcul Sum Distributed)
  client/src/modules/distribution_center/modals/breakDown.modal.js
  client/src/modules/distribution_center/modals/distribution_key.modal.js
Labels: size: S

#3833 add translation in employee report
  client/src/i18n/fr/form.json
Labels: size: XS

#3834 Handle negative values in stock reports
  server/controllers/stock/core.js
  server/models/migrations/next/migrations.sql
  server/models/procedures/stock.sql
Labels: size: XL

#3840 fix: bump unit ids in the migration file
  server/models/migrations/next/migrations.sql
  yarn.lock
Labels: Bug Fix, size: XL

#3849 bug(Cash box translation)
  client/src/js/components/bhUser.js
  client/src/modules/templates/bhUser.tmpl.html
Labels: Bug, size: S

#3846 refactor(Make Exchange Rates human readable)
  client/src/modules/exchange/exchange.modal.html
  client/src/modules/templates/bhExchange.tmpl.html
Labels: Refactor, size: S

#3850 fix(cash): prevent multiple barcode read()s
  client/src/modules/cash/cash-form.service.js
  client/src/modules/patients/patients.service.js
Labels: Bug, Refactor, size: S

#3848 fix(cash): broken barcode binding
  server/controllers/finance/reports/cash/receipt.handlebars
Labels: Bug Fix, size: S

#3845 fix: remove duplicate lint rule
  .eslintrc.json
Labels: size: XS

#3847 fix(bhDateInterval): send dates in UTC format
  client/src/js/components/bhDateInterval.js
Labels: size: S

#3844 fix(grid): rendering bug on reversed records
  client/src/css/structure.css
  client/src/modules/templates/row.reversed.html
Labels: Bug, Bug Fix, size: S

#3692 refractor(patient group) harmonize according 2x
  client/src/modules/patients/groups/groups.html
  client/src/modules/patients/groups/groups.js
  client/src/modules/patients/groups/modal/createUpdate.html
  client/src/modules/patients/groups/modal/createUpdate.js
  client/src/modules/patients/groups/templates/action.cell.html
  server/lib/template/index.js
  test/end-to-end/patient/groups.spec.js
  test/end-to-end/verificationLinks/verificationLinks.spec.js
Labels: size: XL

#3869 fix(accounts): order transactions chronologically
  server/controllers/finance/accounts/transactions.js
Labels: Bug, Bug Fix, size: XS

#3787 chore: add migration script generator
  package.json
  server/models/migrations/setup-migration-script.sh
  sh/build-init-database.sh
  sh/setup-migration-script.sh
  yarn.lock
Labels: chore, size: XL
