Repository third-culture-software/bhima, pull requests merged in 2019-01, with the labels that each got.

#3500 fix(ci): make hound fail on violations
  .hound.yml
Labels: Best Practice, tests

#3512 fix: remove legends from search modals
  client/src/modules/patients/registry/search.modal.html
  client/src/modules/stock/lots/modals/search.modal.html
Labels: Bug Fix

#3504 fix(i18n): add correct PATIENTS key
  client/src/i18n/en/form.json
  client/src/modules/patients/groups/groups.html
Labels: Bug Fix

#3521 feat(report): global total on multi account stmt
  server/controllers/finance/reports/reportAccountsMultiple/index.js
  server/controllers/finance/reports/reportAccountsMultiple/report.handlebars
Labels: Feature Request, report

#3526 feat(employee registry) add a link from Employee Registry to Patient Registry
  client/src/modules/employees/templates/action.cell.html
Labels: Bug Fix

#3524 fix(report): complete unpaid invoices report
  client/src/i18n/en/report.json
  client/src/i18n/fr/report.json
  client/src/js/components/bhDebtorGroupSelect.js
  client/src/modules/reports/generate/unpaid-invoice-payments/unpaid-invoice-payments.config.js
  client/src/modules/reports/generate/unpaid-invoice-payments/unpaid-invoice-payments.html
  client/src/modules/templates/bhDebtorGroupSelect.tmpl.html
  server/controllers/finance/debtors/groups/index.js
  server/controllers/finance/reports/unpaid-invoice-payments/index.js
  server/controllers/finance/reports/unpaid-invoice-payments/report.handlebars
  server/models/bhima.sql
  server/models/migrations/v0.8.0-v0.9.0/migrate.sql
Labels: report

#3531 fix(report): add debtor text to unpaid invoices
  client/src/i18n/fr/report.json
  server/controllers/finance/reports/unpaid-invoice-payments/index.js
  server/controllers/finance/reports/unpaid-invoice-payments/report.handlebars
  server/models/procedures/analysis.sql
  server/models/procedures/invoicing.sql
Labels: Bug Fix, Refactor, report

#3537 fix(journal): preserve trans_id_reference_number
  client/src/modules/journal/modals/editTransaction.modal.js
  server/controllers/finance/journal/index.js
Labels: Bug Fix

#3527 chore(vouchers): lint toolkit and reduce code
  client/src/modules/vouchers/toolkit/cash_transfer/cash_transfer.js
  client/src/modules/vouchers/toolkit/convention_payment/convention_payment.js
  client/src/modules/vouchers/toolkit/convention_payment/convention_payment.modal.html
  client/src/modules/vouchers/toolkit/generic_expense/generic_expense.js
  client/src/modules/vouchers/toolkit/generic_income/generic_income.js
  client/src/modules/vouchers/toolkit/payment_employee/payment_employee.js
  test/end-to-end/shared/components/bhCashBoxSelect.js
  test/end-to-end/vouchers/complex.spec.js
Labels: Refactor

#3551 fix(journal) amount filter update
  server/controllers/finance/journal/index.js
Labels: Bug Fix
