Repository third-culture-software/bhima, pull requests merged in 2019-12, with the labels that each got.

#4031 fix: limit LIMIT fields to positive numbers
  client/src/modules/cash/payments/templates/search.modal.html
  client/src/modules/dashboards/indicators_files_registry/modals/search.modal.html
  client/src/modules/depots/modals/search.modal.html
  client/src/modules/employees/registry/search.modal.html
  client/src/modules/inventory/list/modals/search.modal.html
  client/src/modules/invoices/registry/search.modal.html
  client/src/modules/journal/modals/search.modal.html
  client/src/modules/patients/registry/search.modal.html
  client/src/modules/patients/visits/modals/search.modal.html
  client/src/modules/payroll/staffing_indice/modal/search.modal.html
  client/src/modules/purchases/modals/search.tmpl.html
  client/src/modules/stock/assign/modals/search.modal.html
  client/src/modules/stock/inventories/modals/search.modal.html
  client/src/modules/stock/lots/modals/search.modal.html
  client/src/modules/stock/movements/modals/search.modal.html
  client/src/modules/stock/requisition/modals/search.modal.html
  client/src/modules/vouchers/modals/search.modal.html
Labels: Bug, Bug Fix, size: L

#4028 (Receipt): Stock entry from depot with quantity difference
  client/src/i18n/en/report.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/stock.json
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/stock/entry_depot_receipt.js
  server/controllers/stock/reports/stock/exit_depot_receipt.js
  server/controllers/stock/reports/stock_entry_depot.receipt.handlebars
  server/controllers/stock/reports/stock_exit_depot.receipt.handlebars
  server/lib/template/partials/stockReceiptHeader.handlebars
Labels: size: XL

#4032 Release 1.8.1
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.8.0-v1.8.1/migrate.sql
Labels: size: XL

#4034 Replace bloquote by div
  server/controllers/stock/reports/stock_adjustment.receipt.handlebars
  server/controllers/stock/reports/stock_assign.receipt.handlebars
  server/controllers/stock/reports/stock_entry_donation.receipt.handlebars
  server/controllers/stock/reports/stock_entry_integration.receipt.handlebars
  server/controllers/stock/reports/stock_entry_purchase.receipt.handlebars
  server/controllers/stock/reports/stock_exit_loss.receipt.handlebars
  server/controllers/stock/reports/stock_exit_patient.receipt.handlebars
  server/controllers/stock/reports/stock_exit_service.receipt.handlebars
  server/lib/template/partials/stockReceiptHeader.handlebars
Labels: size: M

#4036 Fix default label for depot select component
  client/src/js/components/bhDepotSelect/bhDepotSelect.js
Labels: Bug Fix, size: XS

#4037 fix(report): render client debt currencies
  server/controllers/finance/reports/client_debts/index.js
  server/controllers/finance/reports/client_debts/report.handlebars
  server/controllers/finance/reports/debtors/index.js
Labels: Bug Fix, size: L

#4035 deps: update dependencies
  package.json
  yarn.lock
Labels: dependencies, size: XL

#4039 Release 1.8.2
  package.json
Labels: size: XS

#3999 Feat(inventory) download log as excel
  client/src/modules/inventory/list/modals/log.modal.html
  client/src/modules/inventory/list/modals/log.modal.js
  server/config/routes.js
  server/controllers/inventory/index.js
  server/controllers/inventory/inventory/core.js
  test/integration/inventory/metadata.js
Labels: Feature Request, size: XL

#4038 chore: migrate account references to async/await
  server/controllers/finance/accounts/references.compute.js
  server/controllers/finance/accounts/references.js
  test/integration/accountReferences.js
Labels: size: XL

#4041 Refactor and Unit Test cronEmailReport
  package.json
  test/server-unit/cron.spec.js
  test/server-unit/cron/addDynamicDatesOptions.spec.js
  test/server-unit/cron/timers.spec.js
  yarn.lock
Labels: Refactor, size: XL, tests

#4042 chore: fix typo in xlsxReceipt
  server/lib/renderers/xlsxReceipt.js
Labels: chore, size: S

#4047 fix(reports): render debit/credit sums in account
  server/controllers/finance/reports/reportAccounts/report.handlebars
  server/controllers/finance/reports/reportAccountsMultiple/report.handlebars
Labels: Bug Fix, size: S

#4046 fix(reports): multiple account statement currency rendering
  server/controllers/finance/reports/account_statement/report.handlebars
  server/controllers/finance/reports/reportAccountsMultiple/index.js
  server/controllers/finance/reports/reportAccountsMultiple/report.handlebars
Labels: Bug, Bug Fix, size: S

#4051 fix: throw on uncaughtExceptions
  server/app.js
Labels: size: S

#4053 chore: update dependencies
  yarn.lock
Labels: size: XL

#4056 fix(cron): adjust weekly unit test
  test/server-unit/cron/addDynamicDatesOptions.spec.js
Labels: Bug Fix, size: XS

#4055 chore: bump deps
  yarn.lock
Labels: dependencies, size: XL
