Repository third-culture-software/bhima, pull requests merged in 2019-05, with the labels that each got.

#3699 use of 5.4.2 protractor version
  .travis.yml
  package.json
  test/end-to-end/stock/stock.entry.page.js
  test/end-to-end/stock/stock.entry.spec.js
  yarn.lock
Labels: size: XL

#3695 refractor, replace create.js file by createUpdate.js
  client/src/modules/prices/modal/createUpdate.html
  client/src/modules/prices/modal/createUpdate.js
  client/src/modules/prices/prices.js
  client/src/modules/purchases/create/createUpdate.html
  client/src/modules/purchases/create/createUpdate.js
  client/src/modules/purchases/purchases.routes.js
  client/src/modules/roles/createUpdate.html
  client/src/modules/roles/createUpdate.js
  client/src/modules/roles/roles.ctrl.js
Labels: size: S

#3696 refractor, use array.includes
  client/src/js/services/grid/GridFilterer.js
  client/src/modules/stock/StockFilterer.service.js
Labels: size: XS

#3690 refractor(supplier) Harmonize according 2x
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/roles/createUpdate.js
  client/src/modules/suppliers/modal/createUpdate.html
  client/src/modules/suppliers/modal/createUpdate.js
  client/src/modules/suppliers/suppliers.html
  client/src/modules/suppliers/suppliers.js
  client/src/modules/suppliers/templates/action.cell.html
  server/config/routes.js
  server/controllers/admin/suppliers.js
  test/end-to-end/suppliers/suppliers.spec.js
Labels: size: XL

#3713 Add week in fiscal year on dashboard
  client/src/modules/home/home.html
Labels: size: XS

#3714 Add database migration file from 1.1.0
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v.1.0.0-v1.1.0/migrate.sql
Labels: size: XL

#3715 Add exchange rate info in exploitation report
  client/src/i18n/en/exchange.json
  client/src/i18n/fr/exchange.json
  server/controllers/finance/reports/operating/index.js
  server/controllers/finance/reports/operating/report.handlebars
Labels: size: M

#3708 feat(service) add hidden column
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/services/modals/service.modal.html
  client/src/modules/services/modals/service.modal.js
  client/src/modules/templates/bhServiceSelect.tmpl.html
  server/controllers/admin/services.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
  test/end-to-end/services/services.page.js
  test/integration/services.js
Labels: size: XL

#3720 fix(Cash Report)
  server/controllers/finance/reports/cashReport/index.js
  server/controllers/finance/reports/cashReport/report_combined.handlebars
  server/controllers/finance/reports/cashReport/report_separated.handlebars
  server/models/migrations/next/migrate.sql
Labels: Bug Fix

#3721 Fix stock value procedure
  server/models/migrations/next/migrate.sql
  server/models/procedures/stock.sql
Labels: size: XL

#3723 fix(Receipt Modal for payslip)
  client/src/js/services/receipts/ReceiptModal.js
Labels: Bug, size: XS

#3725 feat(balance) delete balance sheet report
  .env.development
  server/models/migrations/next/migrate.sql
Labels: size: S

#3729 fix: css compile in production mode
  client/src/modules/application/exchange.html
  gulpfile.js/client-css.js
Labels: Bug Fix, size: XS

#3730 chore: release v1.1.1
  package.json
  server/models/migrations/v1.0.0-v1.1.0/migrate.sql
  server/models/migrations/v1.1.0-v1.1.1/migrate.sql
Labels: Release, size: XS

#3739 Fix indicator report missing value
  client/src/modules/dashboards/indicators_files_registry/modals/hospitalization.modal.html
  server/controllers/finance/indicator/dashboard/report.handlebars
Labels: size: M

#3737 feat(unpaid invoice) add filter by service
  client/src/modules/reports/generate/unpaid-invoice-payments/unpaid-invoice-payments.config.js
  client/src/modules/reports/generate/unpaid-invoice-payments/unpaid-invoice-payments.html
  server/controllers/finance/reports/unpaid-invoice-payments/index.js
  server/models/migrations/next/migrations.sql
  server/models/procedures/analysis.sql
  server/models/procedures/invoicing.sql
Labels: size: XL

#3735 fix: display correct currency in account footer
  server/controllers/finance/reports/reportAccounts/index.js
  server/controllers/finance/reports/reportAccounts/report.handlebars
Labels: Bug Fix, report, size: S

#3733 fix: account reference dropdown header links
  client/src/modules/account_reference/templates/action.cell.html
  client/src/modules/account_reference_type/templates/action.cell.html
Labels: Refactor, size: S

#3734 fix: dismiss fiscal loading indicator once loaded
  client/src/modules/fiscal/fiscal.closingBalance.html
  client/src/modules/fiscal/fiscal.closingBalance.js
Labels: Bug Fix, size: XS

#3732 chore: combine date/username lines on receipt head
  client/src/i18n/en/report.json
  client/src/i18n/fr/report.json
  server/controllers/finance/reports/cash/receipt.handlebars
  server/controllers/finance/reports/invoices/receipt.handlebars
  server/controllers/finance/reports/vouchers/receipt.handlebars
  server/lib/template/partials/header.handlebars
Labels: chore, report, size: M

#3753 fix(invoice): primary key collision invoicing_fees
  server/models/migrations/next/migrations.sql
  server/models/procedures/invoicing.sql
  server/models/schema.sql
Labels: Bug Fix, size: M
