Repository third-culture-software/bhima, pull requests merged in 2019-02, with the labels that each got.

#3567 feat(debtor group) change account
  client/src/modules/debtors/groups.update.js
Labels: Bug Fix

#3590 chore: release version 1.0.0
  CHANGELOG.md
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/setup-migration-script.sh
  server/models/migrations/v0.8.0-v0.9.0/migration-imck.sql
  server/models/migrations/v0.8.0-v1.0.0/migrate.revised.sql
  server/models/migrations/v0.8.0-v1.0.0/migrate.sql
Labels: Release

#3592 fix(docs): update installation documentation links
  README.md
  docs/en/for-developers/installing-bhima.md
  docs/fr/for-developers/installing-bhima.md
Labels: documentation

#3594 fix(prices): show % only when is_percentage
  client/src/modules/prices/modal/createItems.js
  client/src/modules/prices/templates/price_item_value.tmpl.html
Labels: Bug Fix

#3615 docs(stock): expand English stock docs
  docs/en/stock-management/depot.md
  docs/en/stock-management/index.md
  docs/en/stock-management/inventory.md
  docs/en/stock-management/movement.adjustment.md
  docs/en/stock-management/movement.entry.md
  docs/en/stock-management/movement.exit.md
  docs/en/stock-management/movement.md
  docs/en/stock-management/overview.md
Labels: documentation

#3621 docs: fix links to other pages
  docs/en/finance/overview.md
  docs/fr/finance/overview.md
Labels: Bug Fix, documentation
