Repository third-culture-software/bhima, pull requests merged in 2019-07, with the labels that each got.

#3779 improve(Employee Standing)
  client/src/i18n/en/table.json
  client/src/i18n/fr/table.json
  client/src/modules/reports/generate/employeeStanding/employeeStanding.html
  server/controllers/finance/reports/financial.employee.handlebars
  server/controllers/finance/reports/financial.employee.js
Labels: size: M

#3785 fix(Payslip)
  client/src/modules/offdays/modals/offday.modal.html
  server/controllers/payroll/reports/payslipGenerator.handlebars
  server/controllers/payroll/reports/payslipGenerator.js
Labels: size: M

#3775 fix: migration script typo
  server/models/migrations/next/migrations.sql
Labels: Bug Fix, size: S

#3795 fix cron table on migration
  server/models/migrations/next/migrations.sql
Labels: size: XS

#3821 fix stock adjustment deletion
  client/src/modules/stock/adjustment/adjustment.js
Labels: size: XS
