Repository third-culture-software/bhima, pull requests merged in 2019-04, with the labels that each got.

#3664 feature(Break Even Report)
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/reports/generate/breakEven/breakEven.html
  client/src/modules/reports/generate/breakEvenFeeCenter/breakEvenFeeCenter.html
  server/controllers/finance/reports/break_even/index.js
  server/controllers/finance/reports/break_even_fee_center/index.js
Labels: size: XL

#3670 feat(number to text) display a right text if zero is passed
  client/src/i18n/en/numbers.json
  client/src/i18n/fr/numbers.json
  server/lib/NumberToText.js
  test/server-unit/numberToText.spec.js
Labels: size: M

#3653 fix(reports): handle unpaid balance errors
  server/controllers/finance/reports/unpaid-invoice-payments/index.js
  server/controllers/finance/reports/unpaid-invoice-payments/report.handlebars
Labels: Bug, size: M

#3676 feat(bh Account refence select) display warning label only if necessary
  client/src/js/components/bhAccountReferenceSelect.js
  client/src/modules/templates/bhAccountReferenceSelect.tmpl.html
Labels: size: S

#3684 fix currency on footer of the grid and value calculation
  client/src/modules/vouchers/voucher-form.service.js
Labels: size: XS
