Repository third-culture-software/bhima, pull requests merged in 2019-09, with the labels that each got.

#3879 chore: release v1.3.0
  package.json
  server/models/migrations/v1.2.0-v1.3.0/migrate.sql
Labels: Release, size: XS

#3880 improve(Account Reference)
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/account_reference/account_reference.ctrl.js
  client/src/modules/account_reference/account_reference.html
  client/src/modules/account_reference/account_reference.routes.js
  client/src/modules/account_reference/account_reference.service.js
  client/src/modules/account_reference/search.modal.html
  client/src/modules/account_reference/search.modal.js
  server/controllers/finance/accounts/references.js
  test/end-to-end/account-reference/account-reference.cu.page.js
  test/end-to-end/account-reference/account-reference.page.js
  test/end-to-end/account-reference/account-reference.spec.js
  test/integration/accountReferences.js
Labels: size: XL

#3894 chore(payroll): rm unnecessary db.transaction()
  server/controllers/payroll/multiplePayroll/find.js
  server/controllers/payroll/multiplePayroll/getConfig.js
  server/controllers/payroll/multiplePayroll/index.js
Labels: chore, size: L

#3883 fix: remove cache in production
  server/config/express.js
  server/config/interceptors.js
Labels: Bug, size: S

#3902 (receipt): pos receipts for stock exits
  client/src/js/services/receipts/ReceiptService.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/stock/exit_depot_receipt.js
  server/controllers/stock/reports/stock/exit_loss_receipt.js
  server/controllers/stock/reports/stock/exit_patient_receipt.js
  server/controllers/stock/reports/stock/exit_service_receipt.js
  server/controllers/stock/reports/stock_exit_depot.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_loss.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_patient.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_service.receipt.pos.handlebars
Labels: size: XL

#3740 Inventory log
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/js/services/ModalService.js
  client/src/modules/inventory/inventory.service.js
  client/src/modules/inventory/list/list.js
  client/src/modules/inventory/list/modals/log.modal.html
  client/src/modules/inventory/list/modals/log.modal.js
  client/src/modules/inventory/list/templates/action.cell.html
  server/config/routes.js
  server/controllers/inventory/index.js
  server/controllers/inventory/inventory/core.js
  server/models/migrations/next/migration.sql
  server/models/schema.sql
Labels: size: XL
