Repository third-culture-software/bhima, pull requests merged in 2019-11, with the labels that each got.

#3980 fix(vouchers): fixes i18n on voucher item error
  client/src/modules/vouchers/voucher-item.service.js
Labels: Bug, Bug Fix, size: S

#3971 chore(server): clean up old code + lint issues
  server/controllers/admin/holidays.js
  server/controllers/admin/iprTax.js
  server/controllers/admin/offdays.js
  server/controllers/dashboard/stats.js
  server/controllers/finance/discounts.js
  server/controllers/finance/fiscalPeriod.js
  server/controllers/finance/invoicingFees.js
  server/controllers/finance/subsidies.js
  server/lib/db/transaction.js
  server/lib/renderers/xlsxReceipt.js
Labels: chore, size: XL

#3974 docs(finance): replace mermaid with graphic
  docs/Gemfile.lock
  docs/en/finance/overview.md
  docs/fr/finance/overview.md
  docs/images/finance/Financial Overview - Receipts through Reports.svg
Labels: documentation, size: XL

#3981 fix(xls): export XLS files without currency symbol
  server/lib/renderers/html.js
  server/lib/renderers/xls.js
  server/lib/template/helpers/finance.js
Labels: Feature Request, report, size: M

#3983 Fix(client debts reports) fix form submit bug
  client/src/modules/reports/generate/clientDebts/clientDebts.config.js
Labels: Bug, size: XS

#3957 Feat(trial balance) set credit value in red
  client/src/modules/accounts/accounts.service.js
  client/src/modules/journal/trial-balance/overview.js
Labels: Bug, size: S

#3982 chore(xlsx): clean up renderer code
  server/lib/renderers/xlsx.js
  server/lib/renderers/xlsxReceipt.js
  test/server-unit/xlsx.spec.js
Labels: chore, size: L

#3996 Fix filtering on the entry/exit column
  client/src/modules/stock/movements/registry.js
Labels: size: S

#3995 fix: do not crash an uninstalled server by cron
  server/app.js
  server/controllers/admin/cronEmailReport/index.js
Labels: Bug Fix, size: S

#3994 deps: update chai-http to latest
  package.json
  server/controllers/admin/displayMetadata.js
  test/integration/debtorGroups.js
  test/integration/fillForm.js
  yarn.lock
Labels: Refactor, dependencies, size: XL, tests

#4003 fix(app): do not crash on unCaughtException
  server/app.js
Labels: Bug Fix, size: S

#4007 fix(cloud-init): set working directory
  docs/cloud-init.yml
Labels: Bug Fix, size: XS

#4012 Fix(tests): wait for navigation on patient record
  test/end-to-end/patient/record.spec.js
Labels: Bug Fix, size: XS

#4005 chore: remove mz from dependencies
  package.json
  server/lib/backup.js
  server/lib/mailer.js
  server/lib/template/helpers/logic.js
  test/server-unit/pdf.spec.js
  yarn.lock
Labels: Refactor, chore, size: L

#4019 fix(tests): attempt to fix flakey voucher tests
  test/end-to-end/shared/FormUtils.js
  test/end-to-end/transactionType/transactionType.spec.js
  test/end-to-end/vouchers/complex.spec.js
Labels: Bug Fix, size: XL, tests

#4018 Refractor(bhdateInterval) set correct dates
  client/src/js/components/bhDateInterval.js
Labels: size: M

#4029 fix stock identifier for barcode
  server/controllers/stock/reports/stock/adjustment_receipt.js
  server/controllers/stock/reports/stock/assign_receipt.js
  server/controllers/stock/reports/stock/entry_depot_receipt.js
  server/controllers/stock/reports/stock/entry_donation_receipt.js
  server/controllers/stock/reports/stock/entry_integration_receipt.js
  server/controllers/stock/reports/stock/entry_purchase_receipt.js
  server/controllers/stock/reports/stock/exit_depot_receipt.js
  server/controllers/stock/reports/stock/exit_loss_receipt.js
  server/controllers/stock/reports/stock/exit_patient_receipt.js
  server/controllers/stock/reports/stock/exit_service_receipt.js
Labels: Bug Fix, size: M
