Repository third-culture-software/bhima, pull requests merged in 2019-06, with the labels that each got.

#3756 fix: typos in migration script setup
  server/models/migrations/setup-migration-script.sh
  server/models/migrations/v0.8.0-v1.0.0/migrate.sql
Labels: Bug Fix, size: S

#3752 fix price list report
  client/src/modules/prices/templates/action.cell.html
Labels: size: XS

#3736 fix: parse <head> contents from XLS renderer
  server/lib/renderers/xls.js
Labels: Bug Fix, report, size: S

#3760 feat(component) bhperiod, use period translate_key as label
  client/src/js/components/bhPeriodSelection.js
  server/controllers/finance/fiscal.js
  server/controllers/finance/period.js
  server/models/migrations/next/migrations.sql
  server/models/procedures/time_period.sql
  server/models/schema.sql
  test/end-to-end/reports/aged_creditors/aged_creditors.spec.js
  test/end-to-end/reports/aged_debtors/aged_debtors.spec.js
  test/end-to-end/reports/balance_report/balance_report.spec.js
Labels: size: L

#3770 chore: bump dependencies
  yarn.lock
Labels: size: XL
