Repository third-culture-software/bhima, pull requests merged in 2020-09, with the labels that each got.

#4847 fix: ensure sane accounts in test data
  client/src/i18n/en/posting_journal.json
  client/src/i18n/fr/posting_journal.json
  server/models/procedures/trial_balance.sql
  test/data.sql
  test/integration/journal.js
Labels: Bug, needs review, size: S

#4875 fix(stock): skip tags query if empty result
  server/controllers/stock/index.js
Labels: needs review, size: S

#4871 Implemented enterprise and depot-specific min months security stock parameter
  client/src/css/structure.css
  client/src/i18n/en/enterprise.json
  client/src/i18n/en/form.json
  client/src/i18n/fr/enterprise.json
  client/src/i18n/fr/form.json
  client/src/modules/depots/modals/depot.modal.html
  client/src/modules/depots/modals/depot.modal.js
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  server/controllers/admin/enterprises.js
  server/controllers/inventory/depots/index.js
  server/controllers/stock/core.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
  test/end-to-end/cash/registry.spec.js
  test/end-to-end/stock/stock.exit.spec.js
  test/end-to-end/stock/stock.lots.spec.js
  test/end-to-end/stock/stock.movements.spec.js
  test/end-to-end/stock/stock.z2.inventory-adjustment-inventories.spec.js
  test/end-to-end/stock/stock.z3.inventory-adjustment-lots.spec.js
  test/integration/stock/shared.js
  test/integration/stock/stock.js
Labels: needs review, size: XL

#4874 bug(Stock exit from requisition)
  client/src/modules/stock/exit/modals/findDepot.modal.js
Labels: needs review, size: XS

#4857 Swapped inventory/lot labels on expiration warning block
  client/src/js/components/bhStockExpired/bhStockExpired.html
Labels: Stock, needs review, size: XS

#4866 feat(stock): algorithm for quantity in stock
  client/src/modules/stock/adjustment/adjustment.js
  server/controllers/stock/index.js
  server/models/admin.sql
  server/models/migrations/next/migrate.sql
  server/models/procedures/stock.sql
  server/models/schema.sql
Labels: needs review, size: XL

#4881 feat(CMM aggregate data calculation) set in_quantity and out_quantiy when start_date = end_date
  server/models/procedures/stock.sql
Labels: needs review, size: XS

#4865 Alert about expiration in stock registry
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/stock/inventories/modals/search.modal.html
  client/src/modules/stock/inventories/registry.js
  client/src/modules/stock/inventories/templates/warning.cell.html
  server/controllers/stock/index.js
Labels: needs review, size: XL

#4883 docs(stock): improve stock documentation
  docs/en/stock-management/depot.md
  docs/en/stock-management/index.md
  docs/en/stock-management/movement.entry.md
  docs/en/stock-management/overview.md
Labels: Stock, needs review, size: M

#4894 Fix stock movements grouping
  docs/cloud-init.yml
  server/controllers/finance/fiscal.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  test/end-to-end/stock/stock.exit.page.js
  test/end-to-end/stock/stock.inventories.spec.js
  test/end-to-end/stock/stock.lots.spec.js
  test/end-to-end/stock/stock.movements.spec.js
  test/integration/stock/stock.js
Labels: needs review, size: M, tests

#4899 fix(receipts): allow stock movement lookups
  server/config/identifiers.js
  server/lib/referenceLookup.js
Labels: Bug Fix, needs review, size: XL

#4890 Test(Component Date Editor)
  test/end-to-end/fillForm/fillForm.page.js
  test/end-to-end/offdays/offdays.page.js
  test/end-to-end/shared/components/bhDateEditor.js
Labels: needs review, size: XS

#4901 test: force HTML rendering in travis w/ flag
  .travis.yml
  server/lib/ReportManager.js
Labels: needs review, size: XS, tests

#4902 fix(stock): credit supplier on entry from purchase
  client/src/i18n/en/enterprise.json
  client/src/i18n/fr/enterprise.json
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  server/controllers/admin/enterprises.js
  server/controllers/stock/index.js
  server/models/migrations/next/migrate.sql
  server/models/procedures/stock.sql
  server/models/schema.sql
Labels: Bug Fix, needs review, size: L

#4891 Refactored handling of 'Include Exhausted Lots' flag in Stock Lots registry
  client/src/i18n/en/stock.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/stock.json
  client/src/js/components/bhStockExpired/bhStockExpired.html
  client/src/js/components/bhStockFilterExhausted.js
  client/src/js/components/bhStockSoldOut/bhStockSoldOut.html
  client/src/js/constants/bhConstants.js
  client/src/js/services/PeriodService.js
  client/src/js/services/Store.js
  client/src/modules/reports/generate/inventory_report/inventory_report.html
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/stock/inventories/modals/search.modal.html
  client/src/modules/stock/inventories/modals/search.modal.js
  client/src/modules/stock/lots/modals/search.modal.html
  client/src/modules/stock/lots/modals/search.modal.js
  client/src/modules/stock/lots/registry.js
  client/src/modules/stock/lots/templates/action.cell.html
  client/src/modules/templates/bhStockFilterExhausted.tmpl.html
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  test/data.sql
  test/end-to-end/cash/registry.spec.js
  test/end-to-end/stock/stock.inventories.spec.js
  test/end-to-end/stock/stock.movements.spec.js
  test/end-to-end/stock/stock.z3.inventory-adjustment-lots.spec.js
  test/integration/patients.js
  test/integration/stock/shared.js
  test/integration/stock/stock.js
Labels: size: XL

#4898 chore(stock): combine credit lines in stock exit movement
  server/models/procedures/stock.sql
Labels: Refactor, needs review, size: S

#4909 fix(build): use .env for application config
  .appveyor.yml
  .env.development
  .env.sample
  .gitignore
  docs/cloud-init.yml
  docs/en/for-developers/installing-bhima.md
  docs/fr/for-developers/installing-bhima.md
  gulpfile.js/server.js
  package.json
  server/app.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/lib/db/index.js
  sh/appveyor.sh
  sh/build-database.sh
  sh/build-init-database.sh
  sh/install-tests.sh
  sh/integration-tests.sh
  sh/setup-ci-env.sh
  sh/setup-migration-script.sh
  sh/test-ends.sh
  sh/test.sh
  sh/travis.sh
  test/server-unit/setup.js
  yarn.lock
Labels: needs review, size: XL

#4914 Add SemaphoreCI for testing instead of AppVeyor
  .appveyor.yml
  .semaphore/semaphore.yml
  bors.toml
  sh/appveyor.sh
  sh/build-database.sh
Labels: size: XL, tests

#4910 Hide 'Show items in stock' from purchase registry action menus if none
  client/src/modules/purchases/list/list.js
  client/src/modules/purchases/templates/action.cell.html
Labels: needs review, size: XS

#4915 chore: add installation tests to semaphore
  .semaphore/semaphore.yml
  .travis.yml
Labels: needs review, size: L, tests

#4908 Show depots on registry only according depots permission
  client/src/i18n/en/enterprise.json
  client/src/i18n/fr/enterprise.json
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  server/controllers/admin/enterprises.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/stock/adjustment_receipt.js
  server/controllers/stock/reports/stock/assign_receipt.js
  server/controllers/stock/reports/stock/expiration_report.js
  server/controllers/stock/reports/stock/inline_movements_report.js
  server/controllers/stock/reports/stock/inventories_report.js
  server/controllers/stock/reports/stock/lots_report.js
  server/controllers/stock/reports/stock/movements_report.js
  server/controllers/stock/reports/stock/value.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
  test/end-to-end/depots/depots.spec.js
Labels: needs review, size: XL

#4923 chore: migrate bhChangeDepot to a component
  client/src/js/components/bhChangeDepot.js
  client/src/js/directives/bhChangeDepot.js
  client/src/modules/stock/adjustment/adjustment.html
  client/src/modules/stock/entry/entry.html
  client/src/modules/stock/exit/exit.html
  client/src/modules/stock/import/stockImport.html
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.html
  client/src/modules/stock/requisition/registry.html
Labels: needs review, size: XL

#4920 fix(reports): stock expiration report
  client/src/i18n/en/report.json
  client/src/js/components/bhIndicator/bhIndicator.html
  client/src/modules/dashboards/finance/finance.html
  client/src/modules/reports/generate/stock_expiration_report/stock_expiration_report.config.js
  client/src/modules/reports/generate/stock_expiration_report/stock_expiration_report.html
  server/controllers/finance/reports/recovery_capacity/report.handlebars
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock/expiration_report.js
  server/controllers/stock/reports/stock_expiration_report.handlebars
Labels: Bug Fix, needs review, size: XL

#4926 Feat(cmm) get value from stock_movement_status
  client/src/modules/stock/inventories/registry.js
  client/src/modules/stock/inventories/templates/cmm.cell.html
  server/controllers/stock/core.js
  server/models/procedures/stock.sql
Labels: needs review, size: L

#4931 fix: bump gemfile
  docs/Gemfile.lock
Labels: needs review, size: M

#4927 feat(posting journal) unpost transactions
  client/src/i18n/en/form.json
  client/src/i18n/en/posting_journal.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/posting_journal.json
  client/src/js/constants/bhConstants.js
  client/src/modules/journal/journal.html
  client/src/modules/journal/journal.js
  client/src/modules/journal/trial-balance/trial-balance.service.js
  server/config/identifiers.js
  server/config/routes.js
  server/controllers/admin/roles.js
  server/controllers/finance/trialBalance/index.js
  server/models/admin.sql
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: needs review, size: XL

#4936 feat(inventory log) display correctly la chagement
  client/src/modules/inventory/list/modals/log.modal.js
Labels: needs review, size: XS

#4949 feat(stock e2e tests) pull all tests in one block
  test/end-to-end/stock/stock.adjustment.js
  test/end-to-end/stock/stock.assign.js
  test/end-to-end/stock/stock.entry.js
  test/end-to-end/stock/stock.exit.js
  test/end-to-end/stock/stock.import.js
  test/end-to-end/stock/stock.inventories.js
  test/end-to-end/stock/stock.lots.js
  test/end-to-end/stock/stock.movements.js
  test/end-to-end/stock/stock.requisition.js
  test/end-to-end/stock/stock.spec.js
  test/end-to-end/stock/stock.z1.inventory-adjustment.js
Labels: needs review, size: M

#4950 Fix(unit list) put indicator report in dashboard folder
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: needs review, size: XS

#4951 fix(stock): do not show icon for stock out
  client/src/modules/stock/inventories/registry.js
  client/src/modules/stock/inventories/templates/status.cell.html
  client/src/modules/stock/inventories/templates/warning.cell.html
Labels: Bug Fix, needs review, size: S

#4952 fix: improve UI of stock exits
  client/src/js/components/bhStockExpired/bhStockExpired.html
  client/src/js/components/bhStockExpired/bhStockExpired.js
  client/src/js/components/bhStockSoldOut/bhStockSoldOut.html
  client/src/js/components/bhStockSoldOut/bhStockSoldOut.js
  client/src/modules/stock/exit/exit.html
  client/src/modules/stock/exit/exit.js
Labels: Bug Fix, needs review, size: XL

#4958 fix(vouchers): document_uuid on the payment voucher
  client/src/modules/vouchers/complex-voucher.ctrl.js
  client/src/modules/vouchers/toolkit/payment_employee/payment_employee.js
  client/src/modules/vouchers/vouchers.service.js
  server/controllers/finance/vouchers.js
Labels: Bug Fix, needs review, size: S

#4963 Release 1.15.0
  package.json
Labels: Release, needs review, size: XS

#4966 chore: move migration script.
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.14.1-v1.15.0/migrate.sql
Labels: needs review, size: XL

#4968 fix: allow multiple debtor invoice selections
  client/src/modules/cash/cash.routes.js
  client/src/modules/cash/modals/invoice-modal.ctrl.js
Labels: Bug Fix, needs review, size: S
