Repository third-culture-software/bhima, pull requests merged in 2020-11, with the labels that each got.

#5074 Fix stock inventory test
  test/end-to-end/stock/stock.inventories.js
  test/end-to-end/stock/stock.spec.js
Labels: Bug Fix, needs review, size: XS, tests

#5079 deps: bump all dependencies
  package.json
  yarn.lock
Labels: needs review, size: XL

#5062 fix stock inventories report cmm
  server/controllers/stock/reports/stock/inventories_report.js
Labels: needs review, size: XS

#5061 Add created_at to fix the quantity calculation in stock dataset for test
  test/data/service-stock.sql
Labels: needs review, size: L

#5064 Feature filter lot at peremption risk
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/stock/lots/modals/search.modal.html
  client/src/modules/stock/lots/modals/search.modal.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  test/end-to-end/stock/stock.lots.js
  test/integration/stock/lots.js
Labels: needs review, size: M

#5023 Fix migration problem with production databases.
  docs/en/for-developers/installing-bhima.md
  package.json
  server/models/icd10.sql
  server/models/migrations/next/migrate.sql
  server/models/procedures/migration-process.sql
  server/models/triggers.sql
  sh/build-database.sh
  sh/build-init-database.sh
  sh/build-stock-database.sh
  sh/setup-migration-script.sh
  test/server-unit/mysql_functions.spec.js
Labels: needs review, size: XL

#5082 bug(Complete migration file)
  server/models/migrations/next/migrate.sql
Labels: needs review, size: XS

#5075 Add Helpdesk contact info banner
  client/src/i18n/en/enterprise.json
  client/src/i18n/fr/enterprise.json
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/helpdesk.service.js
  client/src/modules/login/login.html
  client/src/modules/login/login.js
  server/config/express.js
  server/config/routes.js
  server/controllers/admin/enterprises.js
  server/controllers/admin/helpdesk.js
  server/controllers/auth.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
  test/data/enterprise.sql
  test/integration/enterprises.js
Labels: Feature Request, needs review, size: XL

#5087 Change English label to 'Assignment History'
  client/src/i18n/en/stock.json
Labels: needs review, size: XS

#5085 5067 - Fix accounts list by adding a filter
  client/src/modules/accounts/AccountGrid.js
  client/src/modules/accounts/AccountStoreService.js
  client/src/modules/accounts/edit/accounts.edit.js
Labels: needs review, size: XS

#5066 fix: drop temporary tables in posting
  .semaphore/semaphore.yml
  server/models/procedures/trial_balance.sql
Labels: Bug Fix, needs review, size: XS

#5086 5039 - fix the image preview cors error
  client/src/modules/patients/documents/documents.js
  client/src/modules/patients/documents/modals/documents.modal.html
  client/src/modules/patients/documents/modals/documents.modal.js
  server/controllers/medical/patients/documents.js
Labels: needs review, size: S

#5080 fix(reports): NULL recovery capacity where no data
  client/src/i18n/en/report.json
  client/src/i18n/fr/report.json
  server/controllers/finance/reports/recovery_capacity/index.js
  server/controllers/finance/reports/recovery_capacity/report.handlebars
Labels: Bug Fix, needs review, size: S

#5035 chore(stock): rm CMM based on days of consumption
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/settings/stock-settings.html
  client/src/modules/stock/settings/stock-settings.js
  server/controllers/inventory/depots/extra.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/stock/inventories_report.js
  server/controllers/stock/reports/stock/lots_report.js
  server/controllers/stock/setting/index.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/end-to-end/stock/stock.setting.js
  test/integration/stock/stockSettings.js
Labels: needs review, size: XL

#5090 BHIMA v1.16.0
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.15.0-v1.16.0/migrate.sql
Labels: needs review, size: XL

#5083 Updated terms for minimum/security stock status labels
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
Labels: needs review, size: XS

#5093 Fix distribution keys folding
  client/src/modules/distribution_center/distribution_key/distribution_key.js
Labels: needs review, size: XS

#5101 Updated migration script to support site-specific migration files
  sh/setup-migration-script.sh
Labels: needs review, size: XS

#5078 fix(reports): prune empty balance accounts
  server/controllers/finance/reports/balance/index.js
  server/controllers/finance/reports/balance/report.handlebars
  server/controllers/finance/reports/operating/report.handlebars
  server/lib/template/partials/head.handlebars
Labels: Bug Fix, needs review, size: M

#5047 Use confirmation date for purchase order
  client/src/modules/purchases/modals/status.js
  server/controllers/finance/purchases.js
  test/integration/helpers.js
  test/integration/purchase.js
  test/integration/purchase.search.js
Labels: needs review, size: XL

#5107 fix(build) ensure that the manifest is correctly parsed
  gulpfile.js/index.js
Labels: Bug Fix, needs review, size: XS

#5100 fix(stock): make adjustments one HTTP request
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/StockForm.service.js
  client/src/modules/stock/StockItem.service.js
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.html
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.js
  client/src/modules/stock/inventory-adjustment/templates/lot.tmpl.html
  client/src/modules/stock/inventory-adjustment/templates/quantity.tmpl.html
Labels: Refactor, needs review, performance, size: XL

#5104 bug(Out Stock)
  client/src/modules/stock/exit/exit.html
  client/src/modules/stock/exit/exit.js
Labels: needs review, size: XS

#5111 Release v1.16.1
  package.json
Labels: needs review, size: XS

#5113 feat(stock): implement stock changes report
  client/src/i18n/en/report.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/stock.json
  client/src/modules/reports/generate/stock_changes/stock_changes.config.js
  client/src/modules/reports/generate/stock_changes/stock_changes.html
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/finance/period.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock_changes.handlebars
  server/controllers/stock/reports/stock_changes.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: needs review, report, size: XL

#5103 refactor(stock): improve find modals
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/exit/modals/RequisitionHelper.service.js
  client/src/modules/stock/exit/modals/findDepot.modal.html
  client/src/modules/stock/exit/modals/findDepot.modal.js
  client/src/modules/stock/exit/modals/findPatient.modal.html
  client/src/modules/stock/exit/modals/findService.modal.html
  client/src/modules/stock/exit/modals/findService.modal.js
  server/controllers/admin/services.js
Labels: Refactor, Stock, needs review, size: XL

#5091 fix(bhFindEmployee): make search work
  client/src/js/components/bhEmployeeSelect.js
  client/src/modules/templates/bhEmployeeSelect.tmpl.html
  server/controllers/finance/accounts/references.js
  test/data/accounts.sql
Labels: Bug Fix, needs review, size: S

#5118 Feature dashboard stock
  client/src/css/structure.css
  client/src/i18n/en/inventory.json
  client/src/i18n/en/stock.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/inventory.json
  client/src/i18n/fr/stock.json
  client/src/i18n/fr/tree.json
  client/src/js/components/bhStockPanelAtRiskExpiration.js
  client/src/js/components/bhStockPanelAtRiskOutStock.js
  client/src/js/components/bhStockPanelExpired.js
  client/src/js/components/bhStockPanelMinimumReached.js
  client/src/js/components/bhStockPanelOutOfStock.js
  client/src/js/components/bhStockPanelOverMax.js
  client/src/js/components/bhStockPanelRequirePurchaseOrder.js
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/stock/dashboard/dashboard.html
  client/src/modules/stock/dashboard/dashboard.js
  client/src/modules/stock/dashboard/dashboard.routes.js
  client/src/modules/stock/dashboard/dashboard.stock.service.js
  client/src/modules/templates/bhStockPanelAtRiskExpiration.tmpl.html
  client/src/modules/templates/bhStockPanelAtRiskOutStock.tmpl.html
  client/src/modules/templates/bhStockPanelExpired.tmpl.html
  client/src/modules/templates/bhStockPanelMinimumReached.tmpl.html
  client/src/modules/templates/bhStockPanelOutOfStock.tmpl.html
  client/src/modules/templates/bhStockPanelOverMax.tmpl.html
  client/src/modules/templates/bhStockPanelRequirePurchaseOrder.tmpl.html
  server/config/routes.js
  server/controllers/admin/users/depots.js
  server/controllers/stock/index.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: needs review, size: XL

#5154 fix(credit note): do not reload entire registry
  client/src/modules/cash/payments/registry.js
  client/src/modules/invoices/registry/modalCreditNote.js
  client/src/modules/invoices/registry/registry.html
  client/src/modules/invoices/registry/registry.js
Labels: Bug Fix

#5141 docs: add documentation on debtor groups
  docs/en/finance/bookkeeping/patient-invoices.md
  docs/en/finance/core-concepts/debtor-groups.md
  docs/en/finance/core-concepts/index.md
  docs/en/finance/index.md
Labels: documentation
