Repository third-culture-software/bhima, pull requests merged in 2020-05, with the labels that each got.

#4408 Release v1.11.0
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.10.2-v1.11.0/migrate.sql
Labels: Release, size: M

#4403 docs(journal): add note about showing full txns
  docs/en/finance/ledgers/posting-journal.md
Labels: discussion, documentation, size: S

#4416 chore(deps): migrate uuid to new syntax.
  test/integration/helpers.js
Labels: size: XS

#4389 fix(purchases): use prev price in optimal PO
  client/src/js/services/Pool.js
  client/src/modules/purchases/create/PurchaseOrderForm.js
  client/src/modules/purchases/create/createUpdate.html
  client/src/modules/purchases/create/createUpdate.js
Labels: Bug, Refactor, size: L

#4404 fix(stock report) correctly calculate sum when details are not displayed
  server/controllers/stock/reports/stock/exit/exitToDepot.js
  server/controllers/stock/reports/stock/exit/exitToLoss.js
  server/controllers/stock/reports/stock/exit/exitToPatient.js
  server/controllers/stock/reports/stock/exit/exitToService.js
Labels: Bug, size: S

#4415 feat(stock exit) show sold out inventory
  client/src/i18n/en/form.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/exit/exit.html
  client/src/modules/stock/exit/exit.js
  client/src/modules/stock/movements/templates/action.cell.html
  server/config/routes.js
  server/controllers/stock/core.js
Labels: Feature Request, size: XL

#4387 fix(cash): add clear() button to reference
  client/src/modules/cash/payments/templates/search.modal.html
Labels: Bug, size: XS

#4425 chore(deps): bump dependency uuid@8
  package.json
  server/controllers/finance/debtors/groups/index.js
  server/controllers/finance/journal/index.js
  server/controllers/finance/vouchers.js
  server/controllers/stock/index.js
  server/lib/util.js
  test/integration/inventory/shared.js
  test/integration/patientInvoice.js
  test/integration/vouchers.js
  yarn.lock
Labels: dependencies, size: M

#4409 feat(stock): link invoice from movements registry
  client/src/modules/stock/movements/registry.js
  client/src/modules/stock/movements/templates/action.cell.html
  server/controllers/stock/core.js
Labels: Feature Request, size: S

#4440 fix required MySQL version in documentation
  docs/en/for-developers/installing-bhima.md
  docs/fr/for-developers/installing-bhima.md
Labels: size: XS

#4445 Improve db creation scripts
  sh/build-database.sh
  sh/build-init-database.sh
  sh/test-ends.sh
Labels: size: M

#4444 Fix loading indicators
  client/src/js/services/receipts/ReceiptModal.js
  client/src/modules/stock/requisition/modals/action.modal.html
  client/src/modules/stock/requisition/modals/action.modal.js
  client/src/modules/stock/requisition/registry.html
  client/src/modules/stock/requisition/registry.js
  client/src/modules/stock/requisition/templates/action.cell.html
Labels: size: M

#4369 Refactor inventory adjustment
  client/src/i18n/en/stock.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/stock.json
  client/src/i18n/fr/tree.json
  client/src/js/constants/bhConstants.js
  client/src/js/services/FluxService.js
  client/src/js/services/StockService.js
  client/src/modules/stock/StockForm.service.js
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.html
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.js
  client/src/modules/stock/inventory-adjustment/templates/lot.tmpl.html
  client/src/modules/stock/inventory-adjustment/templates/quantity.tmpl.html
  client/src/modules/stock/movements/registry.js
  client/src/modules/stock/stock.routes.js
  package.json
  server/config/routes.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/adjustment_receipt.js
  server/controllers/stock/reports/stock_adjustment.receipt.handlebars
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
  test/end-to-end/stock/stock.adjustment.page.js
  test/end-to-end/stock/stock.z1.inventory-adjustment.spec.js
  test/end-to-end/stock/stock.z2.inventory-adjustment-inventories.spec.js
  test/end-to-end/stock/stock.z3.inventory-adjustment-lots.spec.js
Labels: size: XL

#4449 fix e2e tests documentation
  docs/en/for-developers/installing-bhima.md
Labels: size: S

#4447 chore(stock): remove identifiers from origin query
  server/controllers/stock/core.js
Labels: Refactor, size: M

#4451 document how to use docker to start MySQL server
  docs/en/for-developers/installing-bhima.md
Labels: size: S

#4453 Test installation in CI
  .travis.yml
  sh/install-tests.sh
  sh/travis.sh
Labels: Build Process, size: L, tests

#4441 test: refactor fee center GridAction tests
  client/src/modules/distribution_center/distribution_center.html
  client/src/modules/distribution_center/distribution_center.js
  client/src/modules/distribution_center/distribution_key/distribution_key.html
  client/src/modules/distribution_center/distribution_key/distribution_key.js
  client/src/modules/distribution_center/templates/action.tmpl.html
  client/src/modules/distribution_center/templates/setting.tmpl.html
  client/src/modules/fee_center/templates/action.tmpl.html
  client/src/modules/journal/templates/transaction-id.cell.html
  test/end-to-end/distributionFeesCenters/distribution_feescenters.page.js
  test/end-to-end/distributionFeesCenters/distribution_feescenters.spec.js
  test/end-to-end/distributionFeesCenters/distribution_key.page.js
  test/end-to-end/distributionFeesCenters/distribution_key.spec.js
  test/end-to-end/feeCenter/fee_center.spec.js
  test/end-to-end/journal/journal.page.js
Labels: size: XL, tests

#4454 Add loading indicator
  client/src/modules/stock/entry/modals/findPurchase.modal.js
Labels: Bug, size: M

#4462 fix docs, currently only MySQL 5.7 is supported
  docs/en/for-developers/installing-bhima.md
  docs/fr/for-developers/installing-bhima.md
Labels: size: XS

#4455 Fix self requisition
  client/src/js/components/bhDepotSelect.js
  client/src/js/components/bhDepotSelect/bhDepotSelect.js
  client/src/modules/stock/requisition/modals/action.modal.html
  server/controllers/inventory/depots/index.js
Labels: Bug, size: S

#4464 fix(Downloading employee registry as CSV and PDF crashes)
  server/controllers/payroll/reports/registrations.js
Labels: Bug, size: S

#4402 Refactor Employee and Multiple Payroll w/ Links and References
  client/src/i18n/en/employee.json
  client/src/i18n/fr/employee.json
  client/src/modules/employees/employee.service.js
  client/src/modules/employees/registry/registry.js
  client/src/modules/employees/registry/search.modal.html
  client/src/modules/employees/registry/search.modal.js
  client/src/modules/employees/templates/action.cell.html
  client/src/modules/invoices/registry/registry.js
  client/src/modules/multiple_payroll/multiple_payroll.js
  client/src/modules/multiple_payroll/multiple_payroll.service.js
  client/src/modules/multiple_payroll/templates/action.tmpl.html
  client/src/modules/purchases/templates/cellStatus.tmpl.html
  server/controllers/payroll/multiplePayroll/find.js
  server/controllers/payroll/multiplePayroll/index.js
  test/end-to-end/employees/registration.page.js
  test/end-to-end/employees/update.spec.js
  test/end-to-end/payrollProcess/payroll_process.page.js
  test/end-to-end/payrollProcess/payroll_process.spec.js
  test/end-to-end/staffingIndice/staffing-indice.spec.js
Labels: Feature Request, Refactor, size: XL

#4410 feature(Report to Compare Invoiced Items to received Stock)
  client/src/i18n/en/form.json
  client/src/i18n/en/report.json
  client/src/i18n/en/table.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/table.json
  client/src/i18n/fr/tree.json
  client/src/modules/reports/generate/invoicedReceivedStock/invoicedReceivedStock.html
  client/src/modules/reports/generate/invoicedReceivedStock/invoicedReceivedStock.js
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/finance/reports/index.js
  server/controllers/finance/reports/invoicedReceivedStock/index.js
  server/controllers/finance/reports/invoicedReceivedStock/report.handlebars
  server/lib/template/helpers/finance.js
  server/lib/template/index.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: proposal, report, size: XL

#4468 refactor(stock): move invoice reference on receipt
  server/controllers/stock/reports/stock_exit_patient.receipt.handlebars
  server/lib/template/partials/stockReceiptHeader.handlebars
Labels: Refactor, size: S

#4474 Fix: test on mariadb reliably
  .env.development
  .snyk
  .travis.yml
  server/controllers/finance/vouchers.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/lib/ReportManager.js
  test/end-to-end/cashflow/cashflow.spec.js
  test/end-to-end/stock/stock.movements.spec.js
Labels: Feature Request, needs tests, size: L

#4472 feat(depot registry) add link to stock inventories
  client/src/modules/depots/templates/action.tmpl.html
Labels: Refactor, size: S

#4475 feat(stock requisition) add status filter
  client/src/js/services/StockService.js
  client/src/modules/stock/requisition/registry.js
  client/src/modules/stock/requisition/templates/status.filter.html
  server/config/routes.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
Labels: Bug, size: L

#4458 test different versions of node
  .appveyor.yml
  .travis.yml
Labels: Build Process, size: M, tests

#4488 fix(stock): standardize requisition receipt
  server/controllers/stock/requisition/requisition.js
  server/controllers/stock/requisition/requisition.receipt.handlebars
Labels: Refactor, size: XL

#4466 fix(reports): better empty message for employee financial activity
  server/controllers/finance/reports/financial.employee.handlebars
Labels: Bug, size: S

#4486 fix(purchase): make DECIMALs compatible with PJ/GL
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: Bug, Bug Fix, Feature Request, size: S

#4471 feat(employee registry) add a link to patient financial report
  client/src/modules/employees/registry/registry.js
  client/src/modules/employees/templates/action.cell.html
Labels: Feature Request, size: S

#4473 make bhima MySQL8 compatible
  .appveyor.yml
  .travis.yml
  docs/en/for-developers/installing-bhima.md
  docs/fr/for-developers/installing-bhima.md
  server/controllers/admin/users/index.js
  server/controllers/auth.js
  server/controllers/finance/accounts/transactions.js
  server/controllers/install.js
  server/controllers/stock/core.js
  server/models/functions.sql
  sh/appveyor.sh
  sh/setup-ci-env.sh
  sh/test.sh
  sh/travis-install-mysql8.sh
  sh/travis.sh
  test/data-init.sql
  test/data.sql
  test/integration/accountConfig.js
  test/integration/cashboxes.js
  test/integration/creditorGroups.js
  test/integration/currencies.js
  test/integration/employeeConfig.js
  test/integration/enterprises.js
  test/integration/exchange.js
  test/integration/feesCenters.js
  test/integration/functions.js
  test/integration/grades.js
  test/integration/holidays.js
  test/integration/offdays.js
  test/integration/patientInvoice.js
  test/integration/payrollConfig.js
  test/integration/projects.js
  test/integration/purchase.js
  test/integration/rubrics.js
  test/integration/services.js
  test/integration/suppliers.js
  test/integration/taxIpr.js
  test/integration/vouchers.js
  test/integration/weekEndConfig.js
Labels: Feature Request, size: XL, tests

#4476 fix: print colors in PDFs
  client/src/less/bhima-bootstrap.less
  client/src/less/bhima-print.less
  gulpfile.js/client-css.js
  server/controllers/finance/reports/analysis_auxiliary_cashbox/report.handlebars
  server/lib/template/partials/head.handlebars
Labels: Bug, Bug Fix, size: XL

#4487 fix(reports): fixes indent on operating account
  server/controllers/finance/reports/operating/index.js
  server/controllers/finance/reports/operating/report.handlebars
Labels: Bug, size: XL

#4504 fix link to installation
  docs/en/for-developers/installing-bhima.md
Labels: size: XS

#4502 fix(stock): movement search flux displayValues
  client/src/js/components/bhFluxSelect.js
  client/src/modules/stock/movements/modals/search.modal.js
  client/src/modules/templates/bhFluxSelect.tmpl.html
Labels: Bug, size: L

#4508 Fix: Spacing and Overflows on Stock Reports
  server/controllers/stock/reports/monthly_consumption.report.handlebars
  server/controllers/stock/reports/purchaseOrderAnalysis/index.js
  server/controllers/stock/reports/purchaseOrderAnalysis/report.handlebars
  server/controllers/stock/reports/stock/inventory_report.js
  server/controllers/stock/reports/stock/monthly_consumption.js
  server/controllers/stock/reports/stock_entry.report.handlebars
  server/controllers/stock/reports/stock_exit.report.handlebars
  server/controllers/stock/reports/stock_inventory.report.handlebars
Labels: Refactor, size: XL

#4496 fix(cash): bug fixes in search modal
  client/src/modules/cash/payments/templates/search.modal.html
  client/src/modules/cash/payments/templates/search.modal.js
Labels: Bug, Bug Fix, size: S

#4492 fix(reports): improve Aux Cashbox Analysis
  client/src/modules/reports/generate/analysisAuxiliaryCash/analysisAuxiliaryCash.config.js
  client/src/modules/reports/generate/analysisAuxiliaryCash/analysisAuxiliaryCash.html
  server/controllers/finance/reports/analysis_auxiliary_cashbox/index.js
  server/controllers/finance/reports/analysis_auxiliary_cashbox/report.handlebars
Labels: Bug, Refactor, size: XL

#4477 Add enterprise setting to change CMM calculation
  client/src/i18n/en/enterprise.json
  client/src/i18n/fr/enterprise.json
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  server/controllers/admin/enterprises.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/stock/inventories_report.js
  server/controllers/stock/reports/stock/lots_report.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: proposal, size: XL

#4516 chore: release v1.12.0
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.11.0-v1.12.0/migrate.sql
  yarn.lock
Labels: Release, size: XL

#4514 refactor(reports): rename stock_sheet
  client/src/i18n/en/report.json
  client/src/i18n/en/tree.json
  client/src/modules/reports/generate/stock_sheet/stock_sheet.config.js
  client/src/modules/reports/generate/stock_sheet/stock_sheet.html
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/stock/core.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/stock_sheet.js
  server/controllers/stock/reports/stock_sheet.report.handlebars
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Feature Request, Refactor, size: XL

#4527 feat(depot registry) add users columns
  client/src/modules/depots/depots.js
  client/src/modules/depots/depots.service.js
  server/controllers/inventory/depots/index.js
Labels: Feature Request, size: S

#4509 feat(Distribution center) save search filters
  client/src/js/components/bhFiscalPeriodSelect.js
  client/src/modules/distribution_center/distribution_center.service.js
  client/src/modules/distribution_center/modals/setting_distribution.modal.html
  client/src/modules/distribution_center/modals/setting_distribution.modal.js
  server/controllers/finance/distributionFeeCenter/configuration.js
  server/controllers/finance/distributionFeeCenter/getDistributed.js
  server/controllers/finance/journal/index.js
Labels: Refactor, size: XL

#4530 deps: CORAL_REUSE_BROWSER flag for speedy PDF startup
  .appveyor.yml
  .travis.yml
  package.json
  yarn.lock
Labels: size: S, tests

#4535 feat(Patient financial activities) add movement value and total on the pan
  client/src/js/components/bhPatientFinancialActivity.js
  client/src/modules/patients/record/bh-patient-financial-activity.html
  server/controllers/medical/patients/index.js
Labels: Feature Request, size: M

#4537 refractor(Stock movement) fix exit filter position
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/movements/modals/search.modal.html
  client/src/modules/stock/movements/modals/search.modal.js
Labels: Refactor, size: S

#4534 feat(distribution fee center) translate grid footer
  client/src/modules/distribution_center/distribution_center.js
  client/src/modules/distribution_center/distribution_key/distribution_key.js
  client/src/modules/distribution_center/templates/footer.template.html
  client/src/modules/distribution_center/update/update_center.js
  docs/index.md
Labels: Refactor, size: S

#4511 catch MySQL exception and rethrow with error in case of incorrect value
  server/controllers/admin/functions.js
  server/controllers/admin/holidays.js
  server/controllers/admin/iprTax.js
  server/controllers/admin/offdays.js
  server/controllers/admin/projects.js
  server/controllers/admin/services.js
  server/controllers/finance/cashboxes/currencies.js
  server/controllers/finance/cashboxes/index.js
  server/controllers/finance/exchange.js
  server/controllers/payroll/accounts/index.js
  server/controllers/payroll/configuration/index.js
  server/controllers/payroll/employeeConfig/index.js
  server/controllers/payroll/rubricConfig/index.js
  server/controllers/payroll/rubrics/index.js
  server/controllers/payroll/weekendConfig/index.js
  server/lib/db/index.js
  test/integration/accountConfig.js
  test/integration/cashboxes.js
  test/integration/creditorGroups.js
  test/integration/currencies.js
  test/integration/employeeConfig.js
  test/integration/enterprises.js
  test/integration/exchange.js
  test/integration/feesCenters.js
  test/integration/functions.js
  test/integration/grades.js
  test/integration/holidays.js
  test/integration/offdays.js
  test/integration/patientInvoice.js
  test/integration/payrollConfig.js
  test/integration/projects.js
  test/integration/purchase.js
  test/integration/rubrics.js
  test/integration/services.js
  test/integration/suppliers.js
  test/integration/taxIpr.js
  test/integration/vouchers.js
  test/integration/weekEndConfig.js
Labels: discussion, size: XL

#4546 feat(inventory group) set account not required if enterprise setting enable_auto_stock_accounting = 0;
  client/src/modules/inventory/configuration/groups/modals/actions.modal.js
  client/src/modules/inventory/configuration/groups/modals/actions.tmpl.html
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
Labels: Refactor, size: S

#4547 fix stock value validation and exit from a custom date
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  client/src/modules/stock/exit/exit.js
  test/end-to-end/fiscalYears/fiscalYears.spec.js
  test/end-to-end/iprTaxesConfig/iprTaxesConfig.page.js
  test/end-to-end/stock/stock.exit.spec.js
Labels: Bug, size: XL

#4548 feat(report printing) allow black & white printing
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/templates/modals/report.save.html
  server/lib/renderers/html.js
  server/lib/template/partials/head.handlebars
Labels: Feature Request, size: S

#4552 refactor: remove `event` table
  server/controllers/admin/entities/index.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: Refactor, size: M

#4555 refractor(Stock lot)set action header
  client/src/modules/stock/lots/templates/action.cell.html
Labels: Refactor, size: XS
