Repository third-culture-software/bhima, pull requests merged in 2020-04, with the labels that each got.

#4222 chore(reports): clean up cron email configurations.
  client/src/js/components/bhCronEmailReport/bhCronEmailReport.html
  client/src/js/components/bhCronEmailReport/bhCronEmailReport.js
  client/src/modules/entities/entities.html
  client/src/modules/entities/entities.js
  client/src/modules/entities/entities.routes.js
  client/src/modules/entities/modals/entity.modal.html
  client/src/modules/entities/modals/entity.modal.js
  client/src/modules/entities/templates/action.tmpl.html
  client/src/modules/entity_group/entity_group.html
  client/src/modules/entity_group/entity_group.js
  client/src/modules/entity_group/entity_group.routes.js
  client/src/modules/entity_group/modals/entity_group.modal.html
  client/src/modules/entity_group/templates/action.tmpl.html
  server/controllers/admin/cronEmailReport/index.js
  server/controllers/admin/cronEmailReport/utils.js
  server/controllers/admin/entities/groups/index.js
  server/controllers/finance/reports/ohada_balance_sheet/index.js
  server/controllers/finance/reports/ohada_balance_sheet/report.handlebars
  server/lib/mailer.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
  test/end-to-end/entities/entities.spec.js
  test/end-to-end/reports/page.js
  test/server-unit/cron/addDynamicDatesOptions.spec.js
Labels: Bug Fix, size: XL

#4245 docs(getting-started): flesh out initial config
  docs/en/getting-started/deploying-digital-ocean.md
  docs/en/getting-started/index.md
Labels: size: M

#4241 test: be more specific when selecting dropdown
  test/end-to-end/account-reference/account-reference.cu.page.js
  test/end-to-end/inventory/configuration.spec.js
  test/end-to-end/shared/FormUtils.js
  test/end-to-end/shared/components/bhAccountSelect.js
  test/end-to-end/shared/components/bhRubricConfigSelect.js
Labels: size: M

#4251 Fix average consumption calculation
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/stock/inventories_report.js
  test/integration/stock/stock.js
Labels: Bug, size: M

#4266 docs(getting-started): more DO install updates
  docs/en/getting-started/deploying-digital-ocean.md
Labels: size: L

#4269 feature(Add stock movement in the patient financial Status)
  client/src/i18n/en/patient_records.json
  client/src/i18n/fr/patient_records.json
  client/src/js/components/bhPatientFinancialActivity.js
  client/src/modules/patients/patients.service.js
  client/src/modules/patients/record/bh-patient-financial-activity.html
  server/config/routes.js
  server/controllers/medical/patients/index.js
  test/data.sql
  test/end-to-end/stock/stock.movements.spec.js
  test/integration/patients.js
  test/integration/stock/shared.js
  test/integration/stock/stock.js
Labels: Feature Request, size: XL

#4277 Feature: use previous purchase price of medicine in Purchase Order
  client/src/modules/purchases/create/PurchaseOrderForm.js
  server/controllers/finance/purchases.js
  server/controllers/inventory/inventory/core.js
  test/integration/inventory/metadata.js
Labels: Feature Request, size: L

#4289 Add unit in stock exit receipts
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/exit_loss_receipt.js
  server/controllers/stock/reports/stock/exit_patient_receipt.js
  server/controllers/stock/reports/stock/exit_service_receipt.js
  server/controllers/stock/reports/stock_exit_depot.receipt.handlebars
  server/controllers/stock/reports/stock_exit_depot.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_loss.receipt.handlebars
  server/controllers/stock/reports/stock_exit_loss.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_patient.receipt.handlebars
  server/controllers/stock/reports/stock_exit_patient.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_service.receipt.handlebars
  server/controllers/stock/reports/stock_exit_service.receipt.pos.handlebars
Labels: size: L

#4290 Do not allow to edit received stock PO
  client/src/js/constants/bhConstants.js
  client/src/modules/purchases/list/list.js
  client/src/modules/purchases/templates/action.cell.html
  client/src/modules/purchases/templates/cellStatus.tmpl.html
Labels: size: M

#4268 chore(install): do not enforce password meter
  client/src/js/components/bhStrengthMeter.js
  client/src/modules/install/install.html
Labels: design, size: S

#4247 chore: add PNAM inventory items
  client/src/js/services/HttpCacheService.js
  client/src/modules/inventory/inventory.service.js
  client/src/modules/inventory/list/list.html
  client/src/modules/inventory/list/list.js
  client/src/modules/inventory/list/modals/actions.modal.js
  client/src/modules/inventory/list/modals/search.modal.html
  protractor.conf.js
  server/controllers/inventory/import/index.js
  server/controllers/stock/core.js
  server/models/bhima.sql
  test/data.sql
  test/end-to-end/account-reference/account-reference.cu.page.js
  test/end-to-end/inventory/list.spec.js
  test/end-to-end/patient/invoice/invoice.spec.js
  test/end-to-end/price_list/price_list.spec.js
  test/end-to-end/purchases/purchases.spec.js
  test/end-to-end/shared/FormUtils.js
  test/end-to-end/stock/stock.assign.spec.js
  test/end-to-end/stock/stock.exit.spec.js
  test/end-to-end/stock/stock.inventories.spec.js
  test/end-to-end/stock/stock.lots.spec.js
  test/end-to-end/stock/stock.movements.spec.js
  test/end-to-end/stock/stock.requisition.spec.js
  test/fixtures/import-inventory-item-template.csv
  test/integration/inventory/group.js
  test/integration/inventory/metadata.js
  test/integration/inventory/type.js
  test/integration/inventory/unit.js
  test/integration/reports/inventory/items.js
  test/integration/stock/stock.js
Labels: size: XL

#4278 feat(purchase): add barcode to purchase orders
  server/controllers/finance/purchases.js
  server/controllers/finance/reports/cash/receipt.handlebars
  server/controllers/inventory/reports/purchases.receipt.handlebars
  server/controllers/stock/reports/stock_entry_purchase.receipt.handlebars
Labels: Feature Request, size: L

#4262 Feature stock assignment inventory by code
  client/src/modules/stock/assign/modals/action.modal.html
  client/src/modules/stock/assign/modals/action.modal.js
  package.json
  yarn.lock
Labels: Feature Request, size: M

#4281 Feat: add search by inventory item to purchase registry
  client/src/js/components/bhInventorySelect.js
  client/src/modules/purchases/modals/search.modal.js
  client/src/modules/purchases/modals/search.tmpl.html
  client/src/modules/purchases/purchases.service.js
  server/controllers/finance/purchases.js
  test/end-to-end/purchases/registry.search.js
  test/integration/purchase.js
Labels: size: L

#4288 fix(stock): movements report download crash
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock/movements_report.js
  server/controllers/stock/reports/stock_movements.report.handlebars
Labels: Bug, size: L

#4267 test(filters): add equals() array test
  server/lib/filter.js
  test/server-unit/filter.spec.js
Labels: needs tests, size: S, tests

#4285 chore(inventory): default delay to 1
  server/models/schema.sql
Labels: proposal, size: XS

#4294 Release v1.10.2
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.10.1-1.10.2/migrate.sql
Labels: Release, size: M

#4301 improvement(Rubric Config Loading)
  client/src/modules/payroll/rubric_configuration/configuration.js
  client/src/modules/payroll/rubric_configuration/modals/config.modal.html
  client/src/modules/payroll/rubric_configuration/modals/config.modal.js
Labels: Bug, size: L

#4299 improvement(Stock Value Report)
  client/src/i18n/en/report.json
  client/src/i18n/fr/report.json
  client/src/modules/reports/generate/stock_value/stock_value.config.js
  client/src/modules/reports/generate/stock_value/stock_value.html
  server/controllers/stock/reports/stock/value.js
Labels: Feature Request, size: S

#4298 feat(purchases): link stock entry from purchase
  client/src/modules/purchases/list/list.html
  client/src/modules/purchases/list/list.js
  client/src/modules/purchases/purchases.service.js
  client/src/modules/purchases/templates/action.cell.html
  client/src/modules/stock/StockFilterer.service.js
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock/entry/entryFromPurchase.js
  test/end-to-end/shared/search.page.js
Labels: Feature Request, size: XL

#4321 feature(Stock Movement)
  client/src/modules/stock/movements/registry.js
  client/src/modules/stock/movements/templates/reference.cell.html
Labels: Feature Request, size: XS

#4286 feat(inventory): link stock on inventory dropdown
  client/src/i18n/en/inventory.json
  client/src/i18n/fr/inventory.json
  client/src/modules/inventory/list/templates/action.cell.html
Labels: Bug, size: M

#4317 feature(Stock Movements to patient financia Activity)
  client/src/i18n/en/form.json
  client/src/i18n/en/report.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/report.json
  client/src/modules/reports/generate/patientStanding/patientStanding.html
  server/controllers/finance/reports/financial.patient.handlebars
  server/controllers/finance/reports/financial.patient.js
  server/controllers/medical/patients/index.js
Labels: Feature Request, size: XL

#4331 feature(StockMovementToPatient)
  client/src/modules/stock/movements/templates/action.cell.html
Labels: Feature Request, size: S

#4284 Feat(voucher tool) patient fleg invoices
  client/src/i18n/en/vouchers.json
  client/src/i18n/fr/vouchers.json
  client/src/js/components/bhAccountSelect.js
  client/src/modules/vouchers/complex-voucher.ctrl.js
  client/src/modules/vouchers/complex-voucher.html
  client/src/modules/vouchers/toolkit.service.js
  client/src/modules/vouchers/toolkit/patient_fled/patient_fled.js
  client/src/modules/vouchers/toolkit/patient_fled/patient_fled.modal.html
  server/controllers/finance/debtors/groups/index.js
Labels: Feature Request, size: XL

#4332 fix stock movement export to csv
  client/src/modules/stock/lots/registry.html
  client/src/modules/stock/movements/registry.html
  client/src/modules/stock/movements/registry.js
Labels: size: S

#4333 Add cost in stock exit report
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  server/controllers/stock/reports/stock/exit/exitToDepot.js
  server/controllers/stock/reports/stock/exit/exitToLoss.js
  server/controllers/stock/reports/stock/exit/exitToPatient.js
  server/controllers/stock/reports/stock/exit/exitToService.js
  server/controllers/stock/reports/stock/exit_report.js
  server/controllers/stock/reports/stock_exit.report.handlebars
Labels: size: L

#4343 chore: remove identifiers from debtors query
  server/controllers/finance/debtors/index.js
Labels: chore, size: S

#4312 Improvements to inventory changes report
  client/src/i18n/en/inventory.json
  client/src/i18n/fr/inventory.json
  server/controllers/inventory/reports/changes.handlebars
  server/controllers/inventory/reports/changes.js
  server/models/schema.sql
Labels: Refactor, report, size: XL

#4352 bug(Lot in Stock)
  server/controllers/stock/core.js
Labels: Bug, size: S

#4348 feature(Stock Movement Registry)
  client/src/i18n/en/report.json
  client/src/i18n/fr/report.json
  client/src/modules/stock/movements/templates/action.cell.html
Labels: Feature Request, size: S

#4336 Feat(Stock report) stock consumption graph report
  client/src/i18n/en/report.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/tree.json
  client/src/modules/reports/generate/stock_consumption_graph_report/stock_consumption_graph_report.config.js
  client/src/modules/reports/generate/stock_consumption_graph_report/stock_consumption_graph_report.html
  client/src/modules/reports/reports.routes.js
  package.json
  server/config/routes.js
  server/controllers/stock/core.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/consumption_graph.js
  server/controllers/stock/reports/stock_consumption_graph.handlebars
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
  yarn.lock
Labels: Feature Request, size: XL

#4291 Handle error message on transaction deletion
  client/src/js/components/bhModalNotify/bhModalNotify.html
  client/src/js/components/bhModalNotify/bhModalNotify.js
  client/src/less/bhima-bootstrap.less
  client/src/modules/journal/modals/editTransaction.modal.html
  client/src/modules/journal/modals/editTransaction.modal.js
  karma.conf.js
  test/client-unit/components/bhFindInvoice.spec.js
  test/client-unit/components/bhModalNotify.spec.js
Labels: size: XL

#4355 refractor(employee registry) fix link to patient data
  client/src/js/components/bhPatientFinancialActivity.js
  client/src/modules/employees/templates/action.cell.html
Labels: Bug, size: S

#4356 feat(inventory in stock) add link to stock movement
  client/src/modules/stock/inventories/registry.js
  client/src/modules/stock/inventories/templates/inventory.action.html
Labels: Feature Request, size: S

#4363 fix(pdf): skip HTML rendering
  server/lib/renderers/pdf.js
Labels: Bug, Bug Fix, size: XS

#4370 feat(Pateint record) add link to stock movement distributed to patient
  client/src/i18n/en/patient_edit.json
  client/src/i18n/fr/patient_edit.json
  client/src/js/components/bhPatientFinancialActivity.js
  client/src/modules/patients/record/bh-patient-financial-activity.html
  server/controllers/stock/core.js
Labels: Feature Request, size: M

#4374 bug(Stock Movement Registry)
  client/src/modules/stock/movements/registry.js
  client/src/modules/stock/movements/templates/flux.cell.html
Labels: Bug, size: XS

#4359 chore: remove unused inventory store.
  client/src/modules/inventory/InventoryStoreService.js
Labels: chore, size: M

#4368 docs(patient-groups): add text on patient groups
  docs/en/medical-records/patient-groups.md
Labels: documentation, size: S

#4373 Feat: render display values on server
  client/src/js/services/FilterService.js
  server/controllers/finance/reports/cash/index.js
  server/controllers/finance/reports/invoices/index.js
  server/controllers/finance/reports/shared.js
  server/controllers/finance/reports/vouchers/index.js
  server/controllers/inventory/reports/prices.handlebars
  server/controllers/inventory/reports/prices.js
  server/controllers/medical/reports/registrations.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/stock/inventory_report.js
  server/controllers/stock/reports/stock_inventory.report.handlebars
Labels: Feature Request, design, size: XL

#4372 improvement(Stock Movement)
  server/controllers/stock/core.js
  server/controllers/stock/import.js
  server/controllers/stock/index.js
  server/models/migrations/next/migrate.sql
  server/models/procedures/stock.sql
  server/models/schema.sql
  test/data.sql
Labels: Feature Request, size: XL

#4358 perf(bhUnique): cache validator results for 15s
  client/src/js/services/UniqueValidatorService.js
  test/client-unit/directives/bhUnique.spec.js
Labels: performance, size: M

#4385 fix(reports): use the correct shared lib
  server/controllers/stock/reports/stock/inventory_report.js
Labels: Bug Fix, size: XS

#4364 fix(debtors): ensure longest description shown
  server/controllers/finance/debtors/index.js
Labels: Refactor, size: M

#4388 chore(reports): async/await purchase analysis
  client/src/i18n/en/report.json
  server/controllers/stock/reports/purchaseOrderAnalysis/index.js
  server/controllers/stock/reports/purchaseOrderAnalysis/report.handlebars
  server/models/bhima.sql
Labels: Refactor, size: XL

#4320 fix(report): improve client debts report
  client/src/modules/reports/generate/clientDebts/clientDebts.html
  server/controllers/finance/reports/client_debts/index.js
  server/controllers/finance/reports/client_debts/report.handlebars
Labels: Bug, size: XL

#4371 feat(employee componet) add employee reference
  client/src/modules/templates/bhEmployeeSelect.tmpl.html
Labels: Refactor, size: XS
