Repository third-culture-software/bhima, pull requests merged in 2020-12, with the labels that each got.

#5143 Fix stock performance issues
  client/src/js/components/bhStockExpired/bhStockExpired.html
  client/src/js/components/bhStockExpired/bhStockExpired.js
  client/src/js/components/bhStockSoldOut/bhStockSoldOut.html
  client/src/js/components/bhStockSoldOut/bhStockSoldOut.js
  client/src/js/services/StockService.js
  client/src/modules/accounts/accounts.service.js
  client/src/modules/depots/depots.service.js
  client/src/modules/stock/lots/registry.service.js
  server/controllers/inventory/depots/extra.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/stock/lots_report.js
  server/models/procedures/stock.sql
  test/data.sql
  test/end-to-end/stock/stock.inventories.js
  test/integration-stock/depots.js
Labels: Stock, performance

#5170 chore(stock): sort receipt printed values
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/stock/entry_donation_receipt.js
  server/controllers/stock/reports/stock/entry_integration_receipt.js
  server/controllers/stock/reports/stock/entry_purchase_receipt.js
  server/controllers/stock/reports/stock_entry_depot.receipt.handlebars
  server/controllers/stock/reports/stock_entry_donation.receipt.handlebars
  server/controllers/stock/reports/stock_exit_depot.receipt.handlebars
Labels: Stock

#5155 chore(reports): clean up wkhtmltopdf references
  server/controllers/admin/metadataReport/index.js
  server/controllers/finance/indicator/dashboard/report.js
  server/controllers/finance/reports/accounts/index.js
  server/controllers/finance/reports/break_even_fee_center/index.js
  server/controllers/finance/reports/cashflow/index.js
  server/controllers/finance/reports/client_support/index.js
  server/controllers/finance/reports/configurable_analysis_report/index.js
  server/controllers/finance/reports/creditors/index.js
  server/controllers/finance/reports/debtors/index.js
  server/controllers/finance/reports/debtors/openDebtors.js
  server/controllers/finance/reports/debtors/summaryReport.js
  server/controllers/finance/reports/income_expense/index.js
  server/controllers/finance/reports/income_expense_by_month/index.js
  server/controllers/finance/reports/income_expense_by_year/index.js
  server/controllers/finance/reports/ohada_profit_loss/index.js
  server/controllers/finance/reports/ohada_profit_loss/report.handlebars
  server/controllers/finance/reports/priceList/index.js
  server/controllers/payroll/multiplePayrollIndice/report.js
  server/controllers/payroll/reports/payslipGenerator.js
  server/controllers/payroll/reports/registrations.js
  server/controllers/payroll/staffingIndices/report.js
Labels: chore

#5176 fix: sort the stock inventories by CMM vars
  client/src/modules/stock/inventories/registry.js
Labels: Bug Fix, Stock

#5178 fix(reports): use serviceUuid instead of serviceId
  server/controllers/finance/reports/unpaid_invoice_payments/index.js
Labels: Bug Fix, Stock

#5190 fix(lots): edit modal min size
  client/src/modules/stock/lots/modals/edit.modal.html
Labels: Bug Fix

#5151 Add option to display negative quantities
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.html
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.js
  server/controllers/stock/index.js
Labels: Stock

#5197 fix(depots): store depot uuid in URL
  client/src/modules/depots/depots.routes.js
  client/src/modules/depots/modals/depot.modal.js
Labels: Bug Fix

#5191 fix(cash): filter correctly on patient debtor_uuid
  client/src/i18n/en/transactions.json
  client/src/modules/cash/payments/templates/action.cell.html
Labels: Bug Fix

#5167 fix(stock): order stock sheet properly
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock_sheet.report.handlebars
Labels: Stock

#5203 fix: remove old bin before archive upload
  package.json
Labels: chore

#5209 chore(payroll): weekend config w/ bhCheckboxTree
  client/src/modules/payroll/weekend_configuration/modals/weekEnd.modal.html
  client/src/modules/payroll/weekend_configuration/modals/weekEnd.modal.js
Labels: Refactor

#5222 feat(users): link users from role management
  client/src/i18n/en/users.json
  client/src/i18n/fr/users.json
  client/src/modules/cash/payments/registry.js
  client/src/modules/roles/roles.ctrl.js
  client/src/modules/roles/roles.html
  client/src/modules/roles/templates/action.cell.html
  client/src/modules/users/templates/grid/action.cell.html
  client/src/modules/users/users.html
  client/src/modules/users/users.js
  client/src/modules/users/users.routes.js
  client/src/modules/users/users.service.js
  server/controllers/admin/users/index.js
Labels: Feature Request

#5224 Fix: articles in stock excel export options
  client/src/i18n/en/inventory.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/StockFilterer.service.js
  server/controllers/finance/reports/shared.js
  server/controllers/stock/reports/stock/inventories_report.js
  server/lib/renderers/xlsx.js
Labels: Bug Fix, Refactor
