Repository third-culture-software/bhima, pull requests merged in 2020-07, with the labels that each got.

#4674 Added install note about problem with MySQL 8.0+ pasword encoding
  docs/en/for-developers/installing-bhima.md
Labels: size: S

#4667 fix(migrate): read from .env.production
  sh/setup-migration-script.sh
Labels: Build Process, Refactor, size: S

#4675 Add totals and consider unposted transactions
  client/src/modules/reports/generate/collectionCapacity/collectionCapacity.config.js
  client/src/modules/reports/generate/collectionCapacity/collectionCapacity.html
  server/controllers/finance/reports/collection_capacity/index.js
  server/controllers/finance/reports/collection_capacity/report.handlebars
Labels: size: L

#4677 Sorting inventory by quantity to command
  client/src/modules/stock/inventories/registry.js
Labels: size: XS

#4680 Refactor to use IMA-WorldHealth/Tree instead of local copy in lib/Tree
  package.json
  server/controllers/finance/fiscal.js
  server/controllers/finance/generalLedger/index.js
  server/controllers/finance/reports/balance/index.js
  server/controllers/finance/reports/general_ledger/index.js
  server/controllers/finance/reports/income_expense/index.js
  server/controllers/finance/reports/income_expense_by_month/index.js
  server/controllers/finance/reports/income_expense_by_year/index.js
  server/controllers/finance/reports/monthlyBalance/index.js
  server/controllers/finance/reports/operating/index.js
  server/lib/Tree.js
  test/server-unit/Tree.spec.js
  yarn.lock
Labels: size: XL

#4678 Add starting date in the stock sheet report
  client/src/i18n/en/settings.json
  client/src/i18n/fr/settings.json
  client/src/modules/reports/generate/stock_sheet/stock_sheet.config.js
  client/src/modules/reports/generate/stock_sheet/stock_sheet.html
  server/controllers/stock/reports/stock/stock_sheet.js
  server/controllers/stock/reports/stock_sheet.report.handlebars
Labels: Feature Request, size: S

#4702 fix(bhLoadingButton)
  client/src/modules/reports/generate/breakEven/breakEven.config.js
  client/src/modules/reports/generate/breakEvenFeeCenter/breakEvenFeeCenter.config.js
  client/src/modules/reports/generate/feeCenter/feeCenter.config.js
Labels: Bug, needs review, report, size: XS

#4694 docs: add barcode generation documentation
  docs/en/for-developers/barcodes.md
  docs/en/for-developers/index.md
  server/lib/barcode.js
Labels: documentation, needs review, size: M

#4708 Added 'temp' directory to .gitignore
  .gitignore
Labels: needs review, size: XS

#4690 refactor(Merges Locations)
  client/src/i18n/en/country.json
  client/src/i18n/en/form.json
  client/src/i18n/en/location.json
  client/src/i18n/en/province.json
  client/src/i18n/en/sector.json
  client/src/i18n/en/village.json
  client/src/i18n/fr/country.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/location.json
  client/src/i18n/fr/province.json
  client/src/i18n/fr/sector.json
  client/src/i18n/fr/village.json
  client/src/modules/locations/country/country.html
  client/src/modules/locations/country/country.js
  client/src/modules/locations/country/modal/createUpdate.js
  client/src/modules/locations/locations.routes.js
  client/src/modules/locations/locations.service.js
  client/src/modules/locations/modals/mergeLocations.modal.html
  client/src/modules/locations/modals/mergeLocations.modal.js
  client/src/modules/locations/province/province.html
  client/src/modules/locations/province/province.js
  client/src/modules/locations/sector/sector.html
  client/src/modules/locations/sector/sector.js
  client/src/modules/locations/village/village.html
  client/src/modules/locations/village/village.js
  client/src/modules/patients/registry/modals/mergePatients.modal.js
  client/src/modules/patients/templates/action.cell.html
  protractor.conf.js
  server/config/routes.js
  server/controllers/admin/locations.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
  test/end-to-end/locations/countries.spec.js
  test/end-to-end/locations/provinces.spec.js
  test/end-to-end/locations/sectors.spec.js
  test/end-to-end/locations/villages.spec.js
  test/integration/locations.js
Labels: Feature Request, needs review, size: XL

#4686 docs: add notes on AMC in stock exit
  docs/en/glossary.md
  docs/en/index.md
  docs/en/stock-management/movement.exit.md
  docs/en/stock-management/movement.md
Labels: size: M

#4715 Filter barcode
  client/src/modules/purchases/list/list.html
  client/src/modules/purchases/list/list.js
  client/src/modules/purchases/purchases.service.js
  client/src/modules/vouchers/voucher-registry.ctrl.js
  server/config/identifiers.js
  server/lib/barcode.js
Labels: Feature Request, needs review, size: S

#4731 4687: feat add expired flag to lots in stock
  .env.development
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/stock/lots/modals/search.modal.html
  client/src/modules/stock/lots/modals/search.modal.js
  server/controllers/stock/core.js
  test/integration/stock/stock.js
Labels: Feature Request, needs review, size: XL

#4728 fix(purchase): add bh-integer for purchases
  client/src/js/directives/bhInteger.js
  client/src/modules/purchases/create/templates/quantity.tmpl.html
  client/src/modules/purchases/list/list.js
  client/src/modules/purchases/templates/cellCost.tmpl.html
Labels: Bug, needs review, size: XS

#4739 Highlight expired stock lots rows
  client/src/css/structure.css
  client/src/modules/stock/lots/registry.js
  client/src/modules/stock/lots/templates/row.expired.html
Labels: needs review, size: S

#4738 Prevent null values of unit_cost by Stock Entry form
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/entry/modals/StockEntryModalForm.service.js
  client/src/modules/stock/entry/modals/lots.modal.html
  client/src/modules/stock/entry/modals/lots.modal.js
  test/client-unit/services/StockEntryModalForm.spec.js
Labels: needs review, size: S

#4729 Order groups alphabetically in inventory create dialog. Fixes #4704.
  client/src/modules/inventory/list/modals/actions.tmpl.html
Labels: Bug, needs review, size: XS

#4727 fix(stock): render inventory report for adjustment
  client/src/js/services/receipts/ReceiptModal.js
  client/src/js/services/receipts/ReceiptService.js
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.js
  server/controllers/stock/index.js
Labels: Bug, needs review, size: M

#4714 Improvement to "Purchase Order Analysis" report
  server/controllers/finance/purchases.js
  server/controllers/stock/reports/purchaseOrderAnalysis/index.js
  server/controllers/stock/reports/purchaseOrderAnalysis/report.handlebars
Labels: needs review, size: XL

#4733 Add Enterprise flag for automatic confirmation of purchase orders. Fixes #4725
  client/src/i18n/en/enterprise.json
  client/src/i18n/fr/enterprise.json
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  server/controllers/admin/enterprises.js
  server/controllers/finance/purchases.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
Labels: Feature Request, needs review, size: S

#4756 feat(lot in stock) add in_risk_of_expiration filter
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/stock/lots/registry.service.js
  client/src/modules/stock/lots/templates/in_risk_of_expiration.html
  server/controllers/stock/core.js
Labels: size: S

#4745 Update Enterprise settings CMN help and sql type for enterprise_daily_consumption
  client/src/i18n/en/enterprise.json
  client/src/i18n/fr/enterprise.json
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: needs review, size: S

#4679 Feat(Inventory group) add expiration and consumption track flag
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/modules/inventory/configuration/groups/modals/actions.modal.js
  client/src/modules/inventory/configuration/groups/modals/actions.tmpl.html
  client/src/modules/stock/entry/entry.js
  client/src/modules/stock/entry/modals/StockEntryModalForm.service.js
  client/src/modules/stock/entry/modals/lots.modal.js
  client/src/modules/stock/lots/modals/edit.modal.html
  client/src/modules/stock/lots/modals/edit.modal.js
  server/controllers/finance/reports/priceList/index.js
  server/controllers/inventory/inventory/core.js
  server/controllers/inventory/inventory/groups.js
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock/entry_donation_receipt.js
  server/controllers/stock/reports/stock/entry_integration_receipt.js
  server/controllers/stock/reports/stock/entry_purchase_receipt.js
  server/controllers/stock/reports/stock_entry_donation.receipt.handlebars
  server/controllers/stock/reports/stock_entry_integration.receipt.handlebars
  server/controllers/stock/reports/stock_entry_purchase.receipt.handlebars
  server/controllers/stock/reports/stock_lots.report.handlebars
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/client-unit/services/StockEntryModalForm.spec.js
  test/data.sql
  test/integration/inventory/shared.js
Labels: design, size: XL

#4758 Added glossary items related to stock management (English only).
  docs/en/glossary.md
Labels: size: L

#4737 chore: add subfolders for reports
  client/src/i18n/fr/tree.json
  client/src/js/components/bhNavigation.js
  client/src/js/services/tree.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Refactor, needs review, size: XL

#4743 feat(Stock) Sold out compenent
  client/src/js/components/bhStockSoldOutController/bhStockSoldOut.html
  client/src/js/components/bhStockSoldOutController/bhStockSoldOut.js
  client/src/modules/stock/exit/exit.html
  client/src/modules/stock/exit/exit.js
Labels: needs review, size: XL

#4759 fix(reports): typo in system usage statistics
  client/src/i18n/en/cron.json
  server/config/routes.js
  server/controllers/finance/reports/systemUsage/index.js
  server/controllers/finance/reports/systemUsage/system.usage.handlebars
Labels: Bug Fix, needs review, size: S

#4765 feat: use bhCheckboxTree for employee config
  client/src/js/components/bhCheckboxTree/bhCheckboxTree.js
  client/src/modules/payroll/employee_configuration/modals/config.modal.html
  client/src/modules/payroll/employee_configuration/modals/config.modal.js
  client/src/modules/roles/modal/userRole.html
  test/end-to-end/f_employees_config/employees_config.page.js
Labels: Refactor, size: XL

#4764 Added client unit test for PurchaseOrderForm
  client/src/modules/purchases/create/PurchaseOrderForm.js
  test/client-unit/services/PurchaseOrderFormService.spec.js
Labels: needs review, size: XL

#4774 Update migration script to use mysql calls to use username/password
  server/models/migrations/next/migrate.sql
  sh/setup-migration-script.sh
Labels: needs review, size: XS
