Repository third-culture-software/bhima, pull requests merged in 2020-01, with the labels that each got.

#4065 chore: add admin SQL tools
  server/models/admin.sql
Labels: chore, size: L

#4071 chore: update deps
  package.json
  yarn.lock
Labels: dependencies, size: XL

#4075 fix(stock): hide hidden services from distribution
  client/src/modules/stock/exit/modals/findDepot.modal.html
  client/src/modules/stock/exit/modals/findService.modal.html
  client/src/modules/stock/exit/modals/findService.modal.js
Labels: Bug, size: M

#4070 fix(stock): sort registries correctly
  client/src/modules/stock/lots/registry.service.js
  client/src/modules/stock/movements/registry.js
Labels: Bug, size: S

#4088 bug(Render Account Type)
  client/src/modules/accounts/edit/accounts.edit.js
  server/controllers/finance/accounts/index.js
Labels: Bug, size: S

#4077 fix(payroll): salaries report fits on page
  server/controllers/payroll/reports/multipayroll.handlebars
  server/controllers/payroll/reports/multipayroll.js
  server/controllers/payroll/reports/payrollReportGenerator.handlebars
  server/lib/renderers/html.js
  server/lib/renderers/pdf.js
Labels: Bug Fix, size: XL

#4091 refactor(report): ameliorate Articles in Stock
  client/src/i18n/en/report.json
  client/src/modules/reports/generate/inventory_report/inventory_report.config.js
  client/src/modules/reports/generate/inventory_report/inventory_report.html
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock/inventories_report.js
  server/controllers/stock/reports/stock_value.report.handlebars
Labels: Refactor, size: XL

#4100 chore: make POS PDF font size smaller
  server/lib/template/partials/point-of-sale-stylesheet.handlebars
Labels: Feature Request, size: XS

#4097 feat(stock): rm 0 quantity in decrease adjustment
  client/src/modules/stock/adjustment/adjustment.html
  client/src/modules/stock/adjustment/adjustment.js
  server/controllers/stock/reports/stock/entry/entryFromIntegration.js
Labels: Feature Request, size: M

#4102 bhima release 1.9.0
  package.json
  server/models/migrations/v1.8.1-v1.9.0/migrate.sql
Labels: size: XS

#4094 fix(inventory): display sellable flag on edit
  client/src/modules/inventory/list/modals/actions.modal.js
  server/controllers/inventory/inventory/core.js
Labels: Bug Fix, size: XS

#4096 fix(stock): Remove patient reference after submit
  client/src/modules/stock/exit/exit.js
  test/end-to-end/stock/stock.exit.spec.js
Labels: Bug Fix, size: XS

#4106 fix(emails): retry sending, improve whitespace
  package.json
  server/controllers/admin/cronEmailReport/index.js
  server/lib/mailer.js
  yarn.lock
Labels: size: XL

#4113 Fix inventory edition for decimal
  client/src/modules/inventory/list/modals/actions.tmpl.html
  client/src/modules/inventory/list/templates/action.cell.html
Labels: size: S

#4111 Add unit column in stock entry page
  client/src/modules/stock/entry/entry.js
  test/end-to-end/stock/stock.entry.page.js
Labels: size: S

#4108 Add link between inventory and stock registry
  client/src/modules/inventory/list/list.js
  client/src/modules/inventory/list/templates/inventory.cell.html
Labels: size: S

#4118 fix(receipt): increase receipt font size
  server/lib/template/partials/point-of-sale-stylesheet.handlebars
Labels: size: XS

#4117 fix(reports): allow saving Items in Stock
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock/inventories_report.js
  server/models/procedures/stock.sql
Labels: Bug, size: S

#4110 Feat(user grid) display assigned depots
  client/src/modules/users/users.html
  client/src/modules/users/users.js
  server/controllers/admin/users/index.js
Labels: Feature Request, size: L

#4122 fix(stock): remove underline from stock receipts
  server/controllers/stock/reports/stock_exit_depot.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_loss.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_patient.receipt.pos.handlebars
  server/controllers/stock/reports/stock_exit_service.receipt.pos.handlebars
Labels: Bug Fix, size: M

#4125 Feat(Inventories in stock) considere filters while exporting
  client/src/modules/stock/inventories/registry.html
  client/src/modules/stock/inventories/registry.js
Labels: Bug, size: S

#4124 chore(stock): do not require description
  client/src/modules/stock/entry/entry.html
  client/src/modules/stock/exit/exit.html
Labels: Refactor, size: S

#4121 feat(stock): allow mvnts filtering on invoice_uuid
  client/src/modules/invoices/registry/templates/action.cell.html
  client/src/modules/patients/templates/action.cell.html
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/stock/movements/modals/search.modal.js
  server/controllers/stock/core.js
Labels: Feature Request, size: S
