Repository third-culture-software/bhima, pull requests merged in 2020-06, with the labels that each got.

#4564 refracor(Stock) rename "Sold out" to "Stock out"
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/js/constants/bhConstants.js
  client/src/js/services/StockService.js
  client/src/modules/stock/exit/exit.html
  client/src/modules/stock/exit/exit.js
  client/src/modules/stock/inventories/modals/search.modal.html
  client/src/modules/stock/inventories/registry.js
  client/src/modules/stock/inventories/templates/status.cell.html
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock_inventories.report.handlebars
  test/client-unit/services/StockService.spec.js
  test/end-to-end/stock/stock.inventories.spec.js
Labels: Refactor, size: M

#4560 feat(stock lot) add link to stock inventory
  client/src/modules/stock/lots/templates/action.cell.html
Labels: Feature Request, size: S

#4553 feat(Payroll config) set ORDER BY dateTo DESC
  server/controllers/payroll/configuration/index.js
Labels: Refactor, size: XS

#4566 Enhance the stock entry report
  client/src/i18n/en/stock.json
  server/controllers/stock/reports/stock/entry_report.js
  server/controllers/stock/reports/stock_entry.report.handlebars
Labels: size: XL

#4556 bug(Stock Value report crashes server with too much data)
  server/controllers/stock/reports/stock/value.js
  server/controllers/stock/reports/stock_sheet.report.handlebars
  server/controllers/stock/reports/stock_value.report.handlebars
  server/models/procedures/stock.sql
Labels: Bug, performance, size: XL

#4570 bh-depot-select : do not send empty search text parameter
  client/src/js/components/bhDepotSelect/bhDepotSelect.js
Labels: size: XS

#4565 feat(cron email) pushing a registry by mail as a report
  client/src/i18n/en/cron.json
  client/src/i18n/fr/cron.json
  client/src/js/components/bhCronEmailReport/bhCronEmailReport.html
  client/src/js/components/bhCronEmailReport/bhCronEmailReport.js
  client/src/js/services/ModalService.js
  client/src/modules/depots/modals/depot.modal.js
  client/src/modules/invoices/registry/registry.html
  client/src/modules/invoices/registry/registry.js
  client/src/modules/templates/modals/cronEmailModal.html
  client/src/modules/templates/modals/cronEmailModal.js
  server/controllers/finance/reports/invoices/index.js
  server/controllers/report.handlers.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Feature Request, size: XL

#4571 bug(Selector Ipr tax)
  client/src/modules/templates/bhIprScale.tmpl.html
  protractor.conf.js
  test/end-to-end/shared/components/bhIprScale.js
Labels: Refactor, size: S, tests

#4574 feat(voucher registry)Link the credit note from the reversed record
  client/src/modules/vouchers/templates/action.cell.html
Labels: Feature Request, size: XS

#4549 fix(reports): ensure filenames are URI encoded
  server/lib/ReportManager.js
Labels: Bug Fix, size: XS

#4582 The version 1.13.0 of bhima
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.12.0-v1.13.0/migrate.sql
Labels: size: L

#4583 Release 1.13.1
  package.json
Labels: Release, size: XS

#4551 feat(Purchase registry) add link to stock inventory
  client/src/modules/purchases/templates/action.cell.html
Labels: size: S

#4539 docs: improve cloud-init script
  docs/cloud-init.yml
  docs/en/for-developers/installing-bhima.md
Labels: deployment, documentation, size: L

#4592 chore(db): remove unused unit.url
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: size: XL

#4601 fix(tests): Promise.all() -> FU.series()
  test/end-to-end/account-reference/account-reference.cu.page.js
  test/end-to-end/employees/registration.page.js
  test/end-to-end/journal/journal.page.js
  test/end-to-end/shared/FormUtils.js
  test/end-to-end/shared/components/bhFluxSelect.js
  test/end-to-end/shared/components/bhMultipleCashBoxSelect.js
  test/end-to-end/shared/components/bhMultipleDepotSelect.js
  test/end-to-end/shared/components/bhPayrollStatusSelect.js
  test/end-to-end/shared/components/bhProjectsMultipleSelect.js
  test/end-to-end/shared/components/bhPurchaseStatusSelect.js
  test/end-to-end/shared/components/bhServicesMultipleSelect.js
  test/end-to-end/shared/components/bhTransactionTypeSelect.js
  test/end-to-end/shared/components/index.js
  test/end-to-end/stock/stock.z1.inventory-adjustment.spec.js
Labels: Bug Fix, size: XL, tests

#4604 fix(distribution key): add percentage filter
  client/src/js/filters/percentage.js
  client/src/modules/distribution_center/distribution_key/distribution_key.js
Labels: size: S

#4610 Add stock exit report grouped by services
  client/src/i18n/en/report.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/stock.json
  client/src/modules/reports/generate/stock_exit/stock_exit.config.js
  client/src/modules/reports/generate/stock_exit/stock_exit.html
  server/controllers/stock/reports/stock/exit_report.js
  server/controllers/stock/reports/stock_exit.report.handlebars
Labels: Feature Request, size: L

#4594 feat(patients): detect duplicate patients
  client/src/i18n/en/cash.json
  client/src/i18n/en/form.json
  client/src/i18n/en/patient_reg.json
  client/src/i18n/fr/cash.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/patient_reg.json
  client/src/modules/cash/modals/select-cashbox-modal.html
  client/src/modules/patients/patients.service.js
  client/src/modules/patients/registry/modals/findDuplicatePatients.modal.html
  client/src/modules/patients/registry/modals/findDuplicatePatients.modal.js
  client/src/modules/patients/registry/registry.html
  client/src/modules/patients/registry/registry.js
  server/config/routes.js
  server/controllers/medical/patients/index.js
  server/controllers/medical/patients/merge.js
  server/lib/filter.js
  test/integration/patients.js
Labels: size: XL

#4609 feat(patients): refresh debtor group history
  client/src/i18n/en/debtor_group.json
  client/src/js/components/bhDebtorGroupHistory.js
  client/src/modules/patients/edit/edit.html
  client/src/modules/patients/edit/edit.js
  client/src/modules/patients/groups/modal/createUpdate.html
  client/src/modules/templates/bhDebtorGroupHistory.tmpl.html
Labels: Feature Request, size: XL

#4608 fix(db): ensure HR modules are under HR
  server/models/migrations/next/migrate.sql
Labels: Bug Fix, Refactor, size: XS

#4607 fix(bhCurrencySelect): pass back full currency object
  client/src/js/components/bhCurrencySelect.js
  client/src/modules/cash/cash-form.service.js
  client/src/modules/cash/cash.html
  client/src/modules/cash/modals/transfer-modal.ctrl.js
  client/src/modules/cash/modals/transfer-modal.html
  client/src/modules/cash/payments/templates/search.modal.html
  client/src/modules/cash/payments/templates/search.modal.js
  client/src/modules/install/install.html
  client/src/modules/install/install.js
  client/src/modules/ipr_tax/modals/ipr_tax.modal.html
  client/src/modules/ipr_tax/modals/ipr_tax.modal.js
  client/src/modules/journal/modals/search.modal.html
  client/src/modules/journal/modals/search.modal.js
  client/src/modules/multiple_payroll/modals/config.modal.html
  client/src/modules/multiple_payroll/modals/config.modal.js
  client/src/modules/multiple_payroll/modals/search.modal.html
  client/src/modules/multiple_payroll/modals/search.modal.js
  client/src/modules/multiple_payroll_indice/modals/config.modal.html
  client/src/modules/multiple_payroll_indice/modals/config.modal.js
  client/src/modules/multiple_payroll_indice/modals/search.modal.html
  client/src/modules/multiple_payroll_indice/modals/search.modal.js
  client/src/modules/payroll/modals/payroll.modal.js
  client/src/modules/reports/generate/account_report/account_report.config.js
  client/src/modules/reports/generate/account_report/account_report.html
  client/src/modules/reports/generate/account_report_multiple/account_report_multiple.config.js
  client/src/modules/reports/generate/account_report_multiple/account_report_multiple.html
  client/src/modules/reports/generate/aged_debtors/aged_debtors.config.js
  client/src/modules/reports/generate/aged_debtors/aged_debtors.html
  client/src/modules/reports/generate/annual-clients-report/annual-clients-report.html
  client/src/modules/reports/generate/annual-clients-report/annual-clients-report.js
  client/src/modules/reports/generate/operating/operating.config.js
  client/src/modules/reports/generate/operating/operating.html
  client/src/modules/reports/generate/stock_value/stock_value.config.js
  client/src/modules/reports/generate/stock_value/stock_value.html
  client/src/modules/templates/bhCurrencySelect.tmpl.html
  client/src/modules/vouchers/complex-voucher.ctrl.js
  client/src/modules/vouchers/complex-voucher.html
  client/src/modules/vouchers/modals/search.modal.html
  client/src/modules/vouchers/modals/search.modal.js
  client/src/modules/vouchers/simple-voucher.ctrl.js
  client/src/modules/vouchers/simple-voucher.html
Labels: Bug, size: XL

#4572 Stock movement registry
  client/src/i18n/en/tree.json
  client/src/i18n/fr/tree.json
  client/src/js/services/StockService.js
  client/src/modules/stock/movements/modals/search.modal.html
  client/src/modules/stock/movements/modals/search.modal.js
  client/src/modules/stock/movements/registry.html
  client/src/modules/stock/movements/registry.js
  client/src/modules/stock/movements/templates/action.cell.html
  client/src/modules/stock/stock.service.js
  server/config/routes.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/exit_loss_receipt.js
  server/controllers/stock/reports/stock/exit_patient_receipt.js
  server/controllers/stock/reports/stock/exit_service_receipt.js
  server/controllers/stock/reports/stock/inline_movements_report.js
  server/controllers/stock/reports/stock_inline_movements.report.handlebars
  server/models/migrations/next/migrate.sql
  test/end-to-end/stock/stock.movements.spec.js
Labels: size: XL

#4619 chore: remove unused gl route
  server/config/routes.js
  server/controllers/finance/ledgers/general.js
Labels: size: M

#4588 Feat: add link to account statement report
  client/src/modules/accounts/accounts.js
  client/src/modules/accounts/templates/actions.html
  client/src/modules/accounts/templates/checkbox.html
  client/src/modules/accounts/templates/select.html
  client/src/modules/general-ledger/general-ledger.ctrl.js
  client/src/modules/general-ledger/templates/action.cell.html
  client/src/modules/journal/modals/search.modal.js
  server/controllers/finance/reports/general_ledger/index.js
Labels: Feature Request, size: M

#4626 Start bhima from mocha
  .env.development
  server/app.js
  sh/integration-tests.sh
  test/integration/inventory/import.js
  test/integration/setup.js
  test/integration/stock/import.js
Labels: size: M

#4637 chore(reports): use singe formatFilters()
  .gitignore
  server/controllers/finance/reports/shared.js
  server/controllers/stock/reports/common.js
Labels: Refactor, size: L

#4638 fix(reports): fix filename on report download
  server/lib/ReportManager.js
Labels: Bug Fix, size: XS

#4628 fix(feeCenter): check correct affectedRows prop
  server/controllers/finance/feeCenter.js
  test/integration/feesCenters.js
Labels: size: S

#4627 chore(deps): remove mkdirp
  package.json
  server/lib/uploader.js
  yarn.lock
Labels: dependencies, size: S

#4652 refactor(Payroll Process)
  client/src/js/services/receipts/ReceiptModal.js
  client/src/modules/multiple_payroll/multiple_payroll.js
  client/src/modules/multiple_payroll/multiple_payroll.service.js
  client/src/modules/multiple_payroll/templates/action.tmpl.html
  server/controllers/payroll/configuration/index.js
  server/controllers/payroll/multiplePayroll/commitmentFunction.js
  server/controllers/payroll/multiplePayroll/find.js
  server/controllers/payroll/multiplePayroll/makeCommitment.js
  server/controllers/payroll/reports/payslipGenerator.js
  test/integration/payroll.js
Labels: Refactor, size: XL

#4655 chore: remove unused bhMultipleDepotSelect
  client/src/js/components/bhMultipleDepotSelect.js
  client/src/modules/templates/bhMultipleDepotSelect.tmpl.html
  test/end-to-end/shared/components/bhMultipleDepotSelect.js
  test/end-to-end/shared/components/index.js
Labels: Refactor, size: L

#4643 feat(reports): optionally rm cash clients in Annual Clients Report
  client/src/i18n/en/report.json
  client/src/i18n/fr/report.json
  client/src/modules/reports/generate/annual-clients-report/annual-clients-report.html
  client/src/modules/reports/generate/annual-clients-report/annual-clients-report.js
  server/controllers/finance/reports/debtors/annual-clients-report.js
Labels: Feature Request, size: XL

#4659 test(filters/telephone): add telephone unit tests
  test/client-unit/filters/telephone.spec.js
Labels: size: M, tests

#4658 test(filters/percentage): add percentage unit tests
  client/src/js/filters/percentage.js
  test/client-unit/filters/percentage.spec.js
Labels: size: M, tests

#4653 Add the recovery capacity report
  client/src/i18n/en/report.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/tree.json
  client/src/modules/reports/generate/collectionCapacity/collectionCapacity.config.js
  client/src/modules/reports/generate/collectionCapacity/collectionCapacity.html
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/finance/reports/collection_capacity/index.js
  server/controllers/finance/reports/collection_capacity/report.handlebars
  server/controllers/finance/reports/index.js
  server/controllers/finance/reports/realized_profit/index.js
  server/lib/template/helpers/finance.js
  server/lib/template/helpers/logic.js
  server/lib/template/index.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Feature Request, report, size: XL

#4657 test(filters/bytes): adds unit tests for bytes.js
  test/client-unit/filters/bytes.spec.js
Labels: size: L, tests

#4661 refactor(patients): improve stock movement table
  client/src/i18n/en/patient_records.json
  client/src/i18n/fr/patient_records.json
  client/src/less/bhima-bootstrap.less
  client/src/modules/patients/record/bh-patient-financial-activity.html
  server/controllers/medical/patients/index.js
Labels: size: XL

#4673 docs(inventory): expand English documentation
  client/src/i18n/en/form.json
  docs/en/stock-management/inventory.md
Labels: size: XL

#4660 fix(patients): update tests to standards
  client/src/modules/patients/templates/action.cell.html
  test/end-to-end/patient/invoice/registry.page.js
  test/end-to-end/patient/registry.search.js
Labels: size: M

#4671 refactor(Employees Search)
  server/config/routes.js
  server/controllers/payroll/employees/index.js
Labels: Best Practice, Refactor, size: M

#4666 docs: add upgrading bhima notes for developers
  docs/en/for-developers/index.md
  docs/en/for-developers/upgrading-bhima.md
Labels: documentation, size: M

#4662 chore(ci): add job names to Travis
  .appveyor.yml
  .travis.yml
  protractor.conf.js
  sh/integration-tests.sh
  sh/travis.sh
Labels: size: M
