Repository third-culture-software/bhima, pull requests merged in 2020-03, with the labels that each got.

#4199 Fix calculation of monthly average consumption of stock
  client/src/modules/stock/lots/registry.html
  client/src/modules/stock/lots/registry.js
  package.json
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock/inventories_report.js
  server/controllers/stock/reports/stock/lots_report.js
  server/controllers/stock/reports/stock_inventories.report.handlebars
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
  test/end-to-end/stock/stock.inventories.spec.js
  yarn.lock
Labels: size: XL

#4200 Fix voucher reference value in stock receipt
  server/controllers/stock/reports/stock/entry_donation_receipt.js
  server/controllers/stock/reports/stock/entry_integration_receipt.js
  server/controllers/stock/reports/stock/entry_purchase_receipt.js
  server/controllers/stock/reports/stock/exit_loss_receipt.js
  server/controllers/stock/reports/stock/exit_patient_receipt.js
Labels: Bug, Bug Fix, size: S

#4212 chore: rm greenkeeper from Travis
  .travis.yml
  sh/travis.sh
  yarn.lock
Labels: size: XL

#4213 Release v1.10.1
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.10.0-v1.10.1/migrate.sql
Labels: Release, size: M

#4191 chore: unmask patient phone number on fiche
  server/controllers/medical/reports/patient.fiche.handlebars
Labels: size: S

#4221 fix(stock): do not warn for voucher_reference
  bors.toml
  server/controllers/stock/reports/stock/adjustment_receipt.js
Labels: Bug, size: S, tests

#4183 chore: rewrite price lists to use pre-filled template
  client/src/i18n/en/price_list.json
  client/src/i18n/fr/price_list.json
  client/src/modules/inventory/list/modals/import.modal.html
  client/src/modules/prices/modal/import.html
  client/src/modules/prices/prices.html
  client/src/modules/prices/prices.js
  client/src/modules/prices/templates/itemsNumber.cell.html
  docs/en/install/index.md
  server/config/routes.js
  server/controllers/finance/priceLists/index.js
  server/controllers/finance/reports/priceList/index.js
  server/controllers/finance/reports/priceList/report.handlebars
  server/lib/util.js
  server/models/procedures/inventory.sql
  server/models/procedures/payroll.sql
  server/models/schema.sql
  server/resources/templates/import-inventory-item-template.csv
Labels: proposal, size: XL

#4216 Payroll excel format
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/multiple_payroll/multiple_payroll.html
  client/src/modules/multiple_payroll/multiple_payroll.js
  client/src/modules/multiple_payroll/multiple_payroll.service.js
  server/controllers/payroll/reports/payrollReportGenerator.handlebars
  server/controllers/payroll/reports/payslipGenerator.js
Labels: size: XL

#4223 feature(Set Number of months for CMM)
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  server/controllers/admin/enterprises.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/integration/enterprises.js
Labels: size: L

#4215 docs: improve Digital Ocean deployment docs
  docs/Gemfile.lock
  docs/cloud-init.yml
  docs/en/for-developers/installing-bhima.md
  docs/en/getting-started/deploying-digital-ocean.md
  docs/en/getting-started/index.md
  docs/en/index.md
  docs/fr/for-developers/installing-bhima.md
  docs/fr/getting-started/deploying-digital-ocean.md
  docs/fr/getting-started/index.md
  docs/fr/index.md
Labels: documentation, size: L

#4237 make id of multiple_payroll_indice inputs unique
  client/src/modules/multiple_payroll_indice/modals/config.modal.html
  test/end-to-end/staffingIndice/payroll-indice.spec.js
Labels: size: S

#4185 chore(deps): remove puppeteer in favor of coral
  package.json
  server/lib/renderers/pdf.js
  test/server-unit/pdf.spec.js
  yarn.lock
Labels: size: XL
