Repository third-culture-software/bhima, pull requests merged in 2020-10, with the labels that each got.

#4970 fix(test): fix bh-date-editor tests
  client/src/js/components/bhDateEditor.js
  client/src/modules/offdays/modals/offday.modal.html
  client/src/modules/offdays/modals/offday.modal.js
  test/data.sql
  test/end-to-end/offdays/offdays.page.js
  test/end-to-end/offdays/offdays.spec.js
  test/end-to-end/stock/stock.inventories.js
  test/integration/enterprises.js
  test/integration/stock/stock.js
Labels: Bug Fix, needs review, size: M

#4967 docs: improve mysql documentation with docker
  docs/en/for-developers/installing-bhima.md
  docs/fr/for-developers/installing-bhima.md
Labels: documentation, needs review, size: S

#4946 Stock settings page
  client/src/i18n/en/enterprise.json
  client/src/i18n/en/form.json
  client/src/i18n/en/settings.json
  client/src/i18n/en/stock.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/enterprise.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/settings.json
  client/src/i18n/fr/stock.json
  client/src/i18n/fr/tree.json
  client/src/js/services/Session.js
  client/src/modules/depots/modals/depot.modal.js
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  client/src/modules/inventory/configuration/groups/modals/actions.modal.js
  client/src/modules/stock/settings/stock-settings.html
  client/src/modules/stock/settings/stock-settings.js
  client/src/modules/stock/settings/stock-settings.service.js
  client/src/modules/stock/stock.routes.js
  server/config/routes.js
  server/controllers/admin/enterprises.js
  server/controllers/auth.js
  server/controllers/finance/purchases.js
  server/controllers/stock/core.js
  server/controllers/stock/import.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/stock/expiration_report.js
  server/controllers/stock/reports/stock/inline_movements_report.js
  server/controllers/stock/reports/stock/inventories_report.js
  server/controllers/stock/reports/stock/lots_report.js
  server/controllers/stock/reports/stock/movements_report.js
  server/controllers/stock/setting/index.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
  server/models/procedures/stock.sql
  server/models/schema.sql
  test/client-unit/mocks/data.js
  test/client-unit/services/SessionService.spec.js
  test/client-unit/services/VoucherForm.spec.js
  test/data.sql
  test/integration/cashboxes.js
  test/integration/enterprises.js
  test/integration/login.js
  test/integration/stock/stockSettings.js
Labels: size: XL

#4985 Support gear icon for menu settings items
  client/src/js/components/bhNavigation.js
  client/src/modules/templates/navigation.tmpl.html
  server/models/bhima.sql
Labels: Feature Request, needs review, size: XS

#4979 Fixed New Requistions modal cancel
  client/src/modules/stock/requisition/modals/action.modal.js
Labels: needs review, size: XS

#4989 fix(cmm data) Make sure that the calculation is done for all movements
  server/models/procedures/stock.sql
Labels: needs review, size: XS

#4992 Depot permission for distribution
  client/src/i18n/en/depot.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/depot.json
  client/src/i18n/fr/stock.json
  client/src/js/components/bhDepotSelect/bhDepotSelect.js
  client/src/js/components/bhDepotSelectSearch/bhDepotSelect.js
  client/src/js/components/bhDepotSelectSearch/bhDepotSelectSearch.html
  client/src/modules/depots/depots.js
  client/src/modules/depots/depots.routes.js
  client/src/modules/depots/depots.service.js
  client/src/modules/depots/modals/depot.modal.html
  client/src/modules/depots/modals/depot.modal.js
  client/src/modules/depots/templates/action.tmpl.html
  client/src/modules/stock/exit/modals/findDepot.modal.js
  client/src/modules/stock/settings/stock-settings.html
  client/src/modules/stock/settings/stock-settings.js
  server/controllers/auth.js
  server/controllers/inventory/depots/index.js
  server/controllers/stock/setting/index.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/end-to-end/depots/depots.spec.js
  test/integration/depots.js
  test/integration/stock/stockSettings.js
Labels: needs review, size: XL

#5007 deps: update all dependencies at once
  package.json
  yarn.lock
Labels: dependencies, needs review, size: XL

#5004 fix(stock): use days not lifetime for expiration
  client/src/modules/stock/exit/exit.js
  server/controllers/stock/core.js
Labels: Bug Fix, needs review, size: XS

#5010 fix(stock): fixes the breaking tests on master
  test/integration/stock/stock.js
Labels: needs review, size: XL

#5014 fix install routing
  client/src/js/app.js
  client/src/modules/login/login.routes.js
Labels: Bug Fix, needs review, size: XS

#4991 Removed 'Add Tag' from modal
  client/src/js/components/bhTagSelect/bhTagSelect.html
  client/src/js/components/bhTagSelect/bhTagSelect.js
  client/src/modules/stock/lots/modals/edit.modal.html
Labels: needs review, size: S

#5009 fix(stock): show empty lots filter on stock lots
  client/src/js/services/StockService.js
  client/src/modules/stock/StockFilterer.service.js
Labels: needs review, size: S

#4983 chore: use bhFilterToggle on Entry from Transfer
  client/src/js/components/bhFilterToggle.js
  client/src/modules/patients/visits/registry.js
  client/src/modules/stock/entry/modals/findTransfer.modal.html
  client/src/modules/stock/entry/modals/findTransfer.modal.js
  client/src/modules/stock/entry/modals/templates/transfer.status.tmpl.html
  server/controllers/stock/reports/stock/entry/entryFromTransfer.js
Labels: needs review, size: XL

#4993 Parameter setting cmm algo
  client/src/i18n/en/form.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/stock.json
  client/src/js/constants/bhConstants.js
  client/src/modules/stock/settings/stock-settings.html
  client/src/modules/stock/settings/stock-settings.js
  server/controllers/stock/setting/index.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/end-to-end/stock/stock.setting.js
  test/end-to-end/stock/stock.setting.page.js
  test/end-to-end/stock/stock.spec.js
  test/integration/stock/stockSettings.js
Labels: needs review, size: XL

#4990 feat(depots): add routes and tests for depots
  server/config/routes.js
  server/controllers/inventory/depots/extra.js
  server/controllers/inventory/depots/index.js
  server/models/procedures/stock.sql
  test/integration/depots.js
  test/integration/helpers.js
Labels: Refactor, size: XL, tests

#5016 Added 'chromeOptions' from local environment variable
  protractor.conf.js
Labels: needs review, size: XS

#5019 Add link to inventory registry
  client/src/modules/stock/lots/templates/action.cell.html
Labels: needs review, size: XS

#5022 Reload after changing the date
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.js
Labels: needs review, size: XS

#5052 Stock: cmm tests
  .semaphore/semaphore.yml
  package.json
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock/stock_sheet.js
  server/models/admin.sql
  server/models/procedures/stock.sql
  server/models/procedures/time_period.sql
  sh/build-stock-database.sh
  sh/integration-stock-tests.sh
  sh/test.sh
  test/data/accounts.sql
  test/data/core.sql
  test/data/enterprise.sql
  test/data/inventories.sql
  test/data/service-stock.sql
  test/data/stock.sql
  test/end-to-end/stock/stock.inventories.js
  test/integration-stock/depots.js
  test/integration-stock/helpers.js
  test/integration-stock/setup.js
  test/integration/depots.js
  test/integration/stock/stock.js
Labels: needs review, size: XL

#5053 Allow all depots to add sub-depots from action menu
  client/src/i18n/en/depot.json
  client/src/modules/depots/templates/action.tmpl.html
  test/end-to-end/depots/depots.page.js
  test/end-to-end/depots/depots.spec.js
Labels: needs review, size: XS

#5063 Fix inventory selection bug in stock exits
  client/src/modules/stock/exit/exit.js
Labels: needs review, size: XS
