Repository third-culture-software/bhima, pull requests merged in 2020-08, with the labels that each got.

#4777 Release v1.14.0
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.13.0-v1.14.0/migrate.sql
Labels: Release, needs review, size: XL

#4781 fix: ensure proper content-security policy.
  server/config/express.js
Labels: Bug Fix, needs review, size: XS

#4782 fix(csp): adds font and blob src to whitelist
  server/config/express.js
Labels: Bug Fix, needs review, size: XS

#4770 fix(i18n): better translation on link to inventory
  client/src/i18n/en/inventory.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/inventory.json
  client/src/modules/stock/inventories/templates/inventory.action.html
  server/controllers/stock/reports/stock_exit.report.handlebars
Labels: needs review, size: XS

#4788 fix(stock): activate cancel button on depot modal
  client/src/js/directives/bhChangeDepot.js
  client/src/modules/depots/depots.service.js
  client/src/modules/stock/depot-selection.ctrl.js
  client/src/modules/stock/depot-selection.modal.html
  client/src/modules/stock/requisition/registry.html
  client/src/modules/stock/requisition/registry.js
Labels: needs review, size: M

#4801 fix: use correct CSP formulation in helmetjs
  server/config/express.js
Labels: needs review, size: XS

#4794 feat(database schema) rename all foreign key constraints
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: needs review, size: XL

#4814 Patch for v1.14.0 about stock movement registry
  server/models/migrations/v1.14.0-v1.14.1/migrate.sql
Labels: needs review, size: XS

#4812 Automatically update stock lot expiration dates in bhima_test
  test/data.sql
  test/end-to-end/stock/stock.lots.spec.js
  test/end-to-end/stock/stock.z3.inventory-adjustment-lots.spec.js
  test/integration/stock/stock.js
Labels: needs review, size: S

#4757 feat(Stock) expiration report
  client/src/i18n/en/report.json
  client/src/i18n/en/stock.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/stock.json
  client/src/i18n/fr/tree.json
  client/src/modules/reports/generate/stock_expiration_report/stock_expiration_report.config.js
  client/src/modules/reports/generate/stock_expiration_report/stock_expiration_report.html
  client/src/modules/reports/reports.routes.js
  client/src/modules/stock/lots/registry.service.js
  server/config/routes.js
  server/controllers/stock/core.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/consumption_graph.js
  server/controllers/stock/reports/stock/expiration_report.js
  server/controllers/stock/reports/stock_expiration_report.handlebars
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: size: XL

#4792 Prevent selection of expired lots by the user in Stock-Exit (except for Loss)
  client/src/i18n/en/errors.json
  client/src/i18n/fr/errors.json
  client/src/modules/stock/exit/exit.js
  test/end-to-end/stock/stock.exit.spec.js
  test/end-to-end/stock/stock.lots.spec.js
  test/end-to-end/stock/stock.z2.inventory-adjustment-inventories.spec.js
  test/end-to-end/stock/stock.z3.inventory-adjustment-lots.spec.js
Labels: needs review, size: S

#4821 fix collection capacity name to recovery capacity
  client/src/i18n/en/report.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/tree.json
  client/src/modules/reports/generate/recoveryCapacity/recoveryCapacity.config.js
  client/src/modules/reports/generate/recoveryCapacity/recoveryCapacity.html
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/finance/reports/index.js
  server/controllers/finance/reports/recovery_capacity/index.js
  server/controllers/finance/reports/recovery_capacity/report.handlebars
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: needs review, size: L

#4769 Fixe(Stock entry from donation) solve receipt rendering problem
  server/controllers/stock/reports/stock/entry_donation_receipt.js
  test/data.sql
  test/integration/stock/assign.js
  test/integration/stock/lots.js
  test/integration/stock/requisition.js
  test/integration/stock/shared.js
  test/integration/stock/stock.js
Labels: needs review, size: XL

#4815 chore: document stock vars in comments
  client/src/modules/stock/lots/registry.js
  server/controllers/stock/core.js
Labels: needs review, size: M

#4810 feat(component) stock expired
  client/src/css/structure.css
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/js/components/bhStockExpired/bhStockExpired.html
  client/src/js/components/bhStockExpired/bhStockExpired.js
  client/src/js/components/bhStockSoldOut/bhStockSoldOut.html
  client/src/js/components/bhStockSoldOut/bhStockSoldOut.js
  client/src/modules/stock/exit/exit.html
Labels: needs review, size: XL

#4784 feat(SQL procedures) drop columns and indexes if exist
  server/models/procedures.sql
  server/models/procedures/migration-process.sql
  test/server-unit/mysql_functions.spec.js
Labels: needs review, size: XL

#4832 feat(Stock entry report)solve checking at least one issue
  client/src/modules/reports/generate/stock_entry/stock_entry.config.js
Labels: Bug Fix, needs review, size: XS

#4762 Lot tags feature
  client/src/i18n/en/form.json
  client/src/i18n/en/tag.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/tag.json
  client/src/js/components/bhTagSelect/bhTagSelect.html
  client/src/js/components/bhTagSelect/bhTagSelect.js
  client/src/modules/debtors/groups.update.html
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/stock/lots/modals/edit.modal.html
  client/src/modules/stock/lots/modals/edit.modal.js
  client/src/modules/stock/lots/modals/search.modal.html
  client/src/modules/stock/lots/modals/search.modal.js
  client/src/modules/stock/lots/registry.js
  client/src/modules/stock/lots/registry.service.js
  client/src/modules/stock/lots/templates/tags.cell.html
  client/src/modules/tags/modal/createUpdate.html
  client/src/modules/tags/modal/createUpdate.js
  client/src/modules/tags/tags.ctrl.js
  client/src/modules/tags/tags.service.js
  client/src/modules/tags/templates/action.cell.html
  client/src/modules/tags/templates/name.cell.html
  server/controllers/admin/tags.js
  server/controllers/finance/reports/priceList/index.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/lots.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/end-to-end/shared/components/bhTagSelect.js
  test/end-to-end/shared/components/index.js
  test/end-to-end/tags/tags.page.js
  test/end-to-end/tags/tags.spec.js
  test/integration/stock/lots.js
Labels: needs review, size: XL

#4836 chore: update test inventory group expiration flag
  test/data.sql
Labels: needs review, size: S

#4839 Improve stock lot highlighting in Stock Lots registry
  client/src/css/structure.css
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/js/services/LotService.js
  client/src/modules/stock/lots/registry.js
  client/src/modules/stock/lots/registry.service.js
  client/src/modules/stock/lots/templates/row.expired.html
  server/controllers/stock/reports/stock/expiration_report.js
Labels: needs review, size: L
