Repository third-culture-software/bhima, pull requests merged in 2021-05, with the labels that each got.

#5610 fix(patients): properly count stock movements
  client/src/js/components/bhPatientFinancialActivity.js
  client/src/modules/patients/record/bh-patient-financial-activity.html
Labels: Bug Fix

#5615 Add 'unused stock' status warning token to Articles in Stock display
  client/src/css/structure.css
  client/src/i18n/en/stock.json
  client/src/i18n/fr/stock.json
  client/src/js/constants/bhConstants.js
  client/src/js/services/StockService.js
  client/src/modules/stock/inventories/registry.js
  client/src/modules/stock/inventories/templates/status.cell.html
  server/config/constants.js
  server/controllers/stock/core.js
  server/controllers/stock/reports/stock_inventories.report.handlebars
Labels: Stock

#5640 fix(stock): allow delete movements
  client/src/modules/stock/movements/registry.js
  client/src/modules/stock/movements/templates/action.cell.html
Labels: Bug Fix, Stock

#5645 fix(stock): allow saving Stock Sheet report
  client/src/modules/reports/baseReports.service.js
  client/src/modules/reports/reports.save.js
  client/src/modules/templates/modals/report.save.html
  server/controllers/stock/reports/stock/stock_sheet.js
Labels: Bug Fix

#5647 fix(stock): do not hang on requisition search
  client/src/js/components/bhHasRequisitionVoucher/bhHasRequisitionVoucher.html
  client/src/js/components/bhHasRequisitionVoucher/bhHasRequisitionVoucher.js
  client/src/js/components/bhRequisitionSelect.js
  client/src/modules/stock/exit/modals/findDepot.modal.html
  client/src/modules/stock/exit/modals/findDepot.modal.js
  client/src/modules/templates/bhRequisitionSelect.tmpl.html
Labels: Bug Fix

#5639 chore(stock): add zMergeDepots admin routine
  server/models/admin.sql
Labels: chore

#5650 fix(reports): ensure red background on RUMER lines
  client/src/i18n/en/tree.json
  client/src/i18n/fr/tree.json
  server/controllers/stock/reports/rumer.report.handlebars
Labels: Bug Fix

#5655 docs: add RELEASES.md
  .gitignore
  README.md
  RELEASES.md
  server/models/migrations/v1.18.0-v1.19.0/migrate.sql
Labels: chore

#5656 Release 1.19.1
  package.json
Labels: Release

#5659 fix(bhDepotSelect): ensure validation works
  client/src/js/components/bhDepotSelectSearch/bhDepotSelect.js
  client/src/js/components/bhDepotSelectSearch/bhDepotSelectSearch.html
Labels: Bug Fix

#5669 fix(xlsx): do not crash on invalid date
  server/lib/renderers/xlsx.js
  test/server-unit/xlsx.spec.js
Labels: Bug Fix

#5644 chore: improve find transfer/purchase modals
  client/src/modules/stock/entry/modals/findPurchase.modal.html
  client/src/modules/stock/entry/modals/findPurchase.modal.js
  client/src/modules/stock/entry/modals/findTransfer.modal.html
  client/src/modules/stock/entry/modals/findTransfer.modal.js
  client/src/modules/stock/entry/modals/templates/document_reference.tmpl.html
Labels: Refactor

#5671 fix(stock): only consumable items for entry
  client/src/modules/stock/entry/entry.js
  client/src/modules/stock/requisition/modals/action.modal.js
Labels: Bug Fix

#5676 chore(patient): make patient notes printable
  client/src/modules/patients/record/patient-record.html
  server/controllers/medical/reports/patient.fiche.handlebars
  server/controllers/medical/reports/patient.receipt.handlebars
Labels: Feature Request

#5677 fix(purchase): use client-generated uuid
  client/src/js/services/uuid.js
  client/src/modules/purchases/create/PurchaseOrderForm.js
Labels: Bug Fix

#5695 fix(depots): filter before limit in depot select
  client/src/modules/stock/depot-selection.modal.html
Labels: Refactor

#5717 fix(stock): properly exchange stock value
  server/controllers/stock/reports/stock/value.js
Labels: Bug Fix
