Repository third-culture-software/bhima, pull requests merged in 2021-01, with the labels that each got.

#5265 fix: add 2021 as fiscal year
  test/data.sql
  test/integration-stock/depots.js
  test/integration/fiscalYear.js
  test/integration/stock/stock.js
Labels: Bug Fix, tests

#5264 feat(users): add "last_login" functionality
  client/src/i18n/en/users.json
  client/src/i18n/fr/users.json
  client/src/modules/users/users.js
  server/controllers/admin/users/index.js
  server/controllers/auth.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: Feature Request, Refactor

#5248 Improve patient finding functionality
  client/src/i18n/en/form.json
  client/src/i18n/en/patient_reg.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/patient_reg.json
  client/src/modules/patients/lookupReturningPatient.modal.html
  client/src/modules/patients/lookupReturningPatient.modal.js
  client/src/modules/patients/patients.service.js
  client/src/modules/patients/registry/modals/mergePatients.modal.js
  client/src/modules/patients/registry/search.modal.html
  package.json
  server/config/routes.js
  server/controllers/medical/patients/index.js
  test/integration/patientMatches.js
  yarn.lock
Labels: Feature Request, chore

#5285 Fix: critical stock bugs
  client/src/modules/stock/movements/modals/search.modal.js
  server/controllers/stock/index.js
Labels: Bug

#5294 Add tooltips to lot registry column headers
  client/src/modules/stock/lots/registry.service.js
Labels: Refactor, Stock

#5240 fix(reports): properly exchange cash report
  server/controllers/finance/accounts/transactions.js
  server/controllers/finance/reports/cashReport/index.js
  server/controllers/finance/reports/cashReport/report_separated.handlebars
Labels: Bug Fix

#5316 feat(stock): highlight expired lots in adjustment
  client/src/i18n/en/stock.json
  client/src/modules/stock/inventory-adjustment/inventory-adjustment.js
Labels: Feature Request, Stock

#5307 Enable merging lots
  client/src/css/structure.css
  client/src/i18n/en/form.json
  client/src/i18n/en/inventory.json
  client/src/i18n/en/stock.json
  client/src/i18n/en/table.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/inventory.json
  client/src/i18n/fr/stock.json
  client/src/i18n/fr/table.json
  client/src/js/services/LotService.js
  client/src/modules/stock/inventories/templates/inventory.action.html
  client/src/modules/stock/lots/modals/duplicates.modal.html
  client/src/modules/stock/lots/modals/duplicates.modal.js
  client/src/modules/stock/lots/registry.js
  client/src/modules/stock/lots/templates/action.cell.html
  client/src/modules/stock/stock.service.js
  server/config/routes.js
  server/controllers/stock/lots.js
  test/integration/mergeLots.js
  test/integration/stock/lots.js
Labels: Do Not Merge
