Repository third-culture-software/bhima, pull requests merged in 2021-08, with the labels that each got.

#5818 fix: update migration schemas
  server/models/migrations/next/migrate.sql
Labels: Bug Fix

#5823 feat(journal): auto-resize journal log
  client/src/modules/journal/journal_log.html
Labels: Bug Fix

#5835 feat(stock): add expiration date to stock exit
  client/src/modules/stock/exit/exit.js
  client/src/modules/stock/exit/templates/lot.tmpl.html
Labels: Stock

#5843 Release 1.21.0
  RELEASES.md
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.20.0-v1.21.0/migrate.sql
Labels: Release

#5837 fix(reports): monthly analysis of balance cleanup
  client/src/modules/reports/generate/monthly_balance/monthly_balance.config.js
  client/src/modules/reports/generate/monthly_balance/monthly_balance.html
  server/controllers/finance/reports/monthly_balance/index.js
  server/controllers/finance/reports/monthly_balance/report.handlebars
Labels: Bug Fix

#5846 fix(reports): improve system usage stats
  client/src/i18n/en/report.json
  client/src/js/components/bhDateEditor.js
  client/src/modules/reports/generate/system_usage_stat/system_usage_stat.config.js
  client/src/modules/reports/generate/system_usage_stat/system_usage_stat.html
  client/src/modules/templates/bhDateEditor.tmpl.html
Labels: Bug Fix

#5851 5553: sort stock movements in decreasing order
  client/src/modules/stock/movements/registry.js
  client/src/modules/stock/movements/templates/flux.cell.html
  server/controllers/stock/core.js
Labels: Feature Request, Refactor

#5857 fix: do not crash on no account references
  server/controllers/finance/distributionFeeCenter/configuration.js
  server/controllers/finance/distributionFeeCenter/proceed.js
  server/controllers/finance/distributionFeeCenter/setting.js
Labels: Bug Fix

#5863 docs: add upgrade notes
  UPGRADING.md
Labels: documentation

#5859 Improve the appearance of boolean search filter flags
  client/src/js/components/bhFilters.js
  client/src/js/constants/bhConstants.js
  client/src/modules/account_reference/account_reference.service.js
  client/src/modules/cash/cash.service.js
  client/src/modules/employees/employee.service.js
  client/src/modules/inventory/inventory.service.js
  client/src/modules/invoices/patientInvoice.service.js
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/vouchers/vouchers.service.js
  server/controllers/finance/reports/shared.js
Labels: Best Practice, Feature Request

#5836 fix: remove exit to purchase from database
  test/data.sql
Labels: Bug Fix

#5874 Add column for Service to employee registry
  client/src/modules/employees/registry/registry.js
Labels: Feature Request

#5885 Feat: add aggregate cost center table
  server/models/admin.sql
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
Labels: Cost Center Analysis
