Repository third-culture-software/bhima, pull requests merged in 2021-09, with the labels that each got.

#5907 feat: add users/stock movements to sys usage
  client/src/i18n/en/form.json
  client/src/i18n/en/users.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/users.json
  server/controllers/finance/reports/systemUsage/index.js
  server/controllers/finance/reports/systemUsage/system.usage.handlebars
Labels: Refactor

#5917 Fix config allocation key
  client/src/modules/allocation_center/allocation_center.service.js
Labels: Bug Fix

#5918 Fix lot usage schedule display problem
  client/src/css/structure.css
  client/src/modules/stock/lots/modals/schedule.modal.html
  client/src/modules/stock/lots/modals/schedule.modal.js
Labels: Bug Fix

#5913 feat: lookup cost center by service
  server/config/routes.js
  server/controllers/admin/services.js
  server/controllers/finance/accounts/index.js
  server/controllers/finance/patientInvoice.js
  server/models/procedures.sql
  server/models/procedures/cost_centers.sql
  test/end-to-end/allocationCostCenters/distribution_feescenters.spec.js
  test/end-to-end/allocationCostCenters/distribution_key.spec.js
  test/end-to-end/feeCenter/fee_center.spec.js
  test/integration/accounts.js
  test/integration/cost-centers/index.js
  test/integration/services.js
  test/server-unit/cron/addDynamicDatesOptions.spec.js
  test/server-unit/mysql_functions.spec.js
Labels: Cost Center Analysis

#5922 Assign cost center in posting journal
  server/controllers/finance/cost_center.js
  server/controllers/payroll/multiplePayroll/commitment.js
  server/controllers/payroll/multiplePayroll/commitmentFunction.js
  server/controllers/payroll/multiplePayroll/makeCommitment.js
  server/models/migrations/next/migrate.sql
  server/models/procedures/trial_balance.sql
  server/models/procedures/voucher.sql
  server/models/schema.sql
  test/data.sql
  test/server-unit/payroll/assignCostCenter.spec.js
Labels: Cost Center Analysis

#5930 feat(stock): add sale value on stock value report
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  server/controllers/stock/reports/stock/value.js
  server/controllers/stock/reports/stock_value.report.handlebars
Labels: Feature Request, report, Stock

#5929 feat(invoices): automatically allocate costs
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/modules/journal/journal.js
  server/controllers/finance/journal/index.js
  server/models/procedures/cost_center.sql
  server/models/procedures/cost_centers.sql
  server/models/procedures/invoicing.sql
Labels: Feature Request, Cost Center Analysis

#5928 chore: remove TravisCI config
  .travis.yml
Labels: chore

#5961 Fix(Role management) display the add button if necessary
  client/src/modules/roles/roles.html
Labels: Bug Fix
