Repository third-culture-software/bhima, pull requests merged in 2021-04, with the labels that each got.

#5557 Fix: end to end test bugs
  client/src/js/components/bhServiceOrDepot/bhServiceOrDepot.html
  client/src/js/components/bhServiceOrDepot/bhServiceOrDepot.js
  client/src/modules/ipr_tax/ipr_tax.routes.js
  client/src/modules/payroll/rubric_configuration/configuration.js
  client/src/modules/stock/entry/modals/lots.modal.js
  client/src/modules/stock/requisition/modals/action.modal.html
  client/src/modules/survey_form/modals/survey_form.modals.html
  client/src/modules/users/users.js
  docs/Gemfile.lock
  protractor.conf.js
  server/controllers/finance/fiscal.js
  server/controllers/stock/core.js
  server/models/migrations/next/migrate.sql
  server/models/procedures/stock.sql
  server/models/procedures/time_period.sql
  server/models/schema.sql
  test/end-to-end/accounts/accounts.page.js
  test/end-to-end/f_employees_config/employees_config.page.js
  test/end-to-end/fiscalYears/fiscalYears.spec.js
  test/end-to-end/iprTaxesConfig/iprTaxesConfig.page.js
  test/end-to-end/rubrics/rubrics.page.js
  test/end-to-end/rubricsConfig/rubrics_config.spec.js
  test/end-to-end/shared/components/bhCheckboxTree.js
  test/end-to-end/stock/stock.adjustment.page.js
  test/end-to-end/stock/stock.entry.js
  test/end-to-end/stock/stock.entry.page.js
  test/end-to-end/stock/stock.inventories.js
  test/end-to-end/stock/stock.lots.js
  test/end-to-end/stock/stock.movements.js
  test/end-to-end/stock/stock.requisition.js
  test/end-to-end/stock/stock.z1.inventory-adjustment.js
  test/end-to-end/stock/stock.z2.inventory-adjustment-inventories.spec.js
  test/end-to-end/stock/stock.z3.inventory-adjustment-lots.spec.js
  test/end-to-end/surveyForm/surveyForm.page.js
  test/end-to-end/user/roles.page.js
  test/end-to-end/user/roles.spec.js
  test/end-to-end/weekendConfig/weekend_config.page.js
Labels: tests

#5574 feat: remove mailgun and add nodemailer
  .env.sample
  package.json
  server/controllers/report.js
  server/lib/mailer.js
  yarn.lock
Labels: dependencies

#5573 Feature: move delete records to a role_action instead of an enterprise_setting
  client/src/i18n/en/users.json
  client/src/i18n/fr/users.json
  client/src/js/constants/bhConstants.js
  client/src/js/directives/bhHasPermission.js
  client/src/js/directives/bhSubmit.js
  client/src/js/services/Session.js
  client/src/modules/cash/payments/registry.js
  client/src/modules/cash/payments/templates/action.cell.html
  client/src/modules/enterprises/enterprises.html
  client/src/modules/enterprises/enterprises.js
  client/src/modules/invoices/registry/registry.js
  client/src/modules/invoices/registry/templates/action.cell.html
  client/src/modules/journal/journal.html
  client/src/modules/journal/journal.js
  client/src/modules/purchases/registry/registry.js
  client/src/modules/purchases/templates/action.cell.html
  client/src/modules/roles/modal/roles.actions.js
  client/src/modules/roles/roles.ctrl.js
  client/src/modules/roles/templates/action.cell.html
  client/src/modules/stock/movements/registry.js
  client/src/modules/stock/movements/templates/action.cell.html
  client/src/modules/vouchers/templates/action.cell.html
  client/src/modules/vouchers/voucher-registry.ctrl.js
  server/config/constants.js
  server/controllers/admin/enterprises.js
  server/controllers/auth.js
  server/controllers/finance/purchases.js
  server/controllers/finance/transactions.js
  server/controllers/stock/index.js
  server/lib/db/transaction.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/data.sql
  test/data/enterprise.sql
  test/integration/login.js
Labels: Feature Request

#5578 Allow Purchase Requests to use different currencies
  client/src/i18n/currency/eur.json
  client/src/i18n/en/exchange.json
  client/src/i18n/fr/exchange.json
  client/src/less/bhima-bootstrap.less
  client/src/modules/exchange/exchange.modal.html
  client/src/modules/purchases/create/PurchaseOrderForm.js
  client/src/modules/purchases/create/createUpdate.html
  client/src/modules/purchases/create/createUpdate.js
  client/src/modules/purchases/create/templates/amount.tmpl.html
  client/src/modules/stock/entry/entry.js
  client/src/modules/stock/entry/modals/lots.modal.html
  client/src/modules/stock/entry/modals/lots.modal.js
  server/controllers/finance/purchases.js
  server/controllers/inventory/inventory/core.js
  server/controllers/inventory/reports/purchases.receipt.handlebars
  server/controllers/inventory/reports/purchases.receipt.js
  server/lib/template/helpers/finance.js
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.13.0-v1.14.0/migrate.sql
  test/integration/inventory/metadata.js
Labels: Feature Request

#5582 fix(stock): remove lot.origin_uuid
  client/src/i18n/en/report.json
  client/src/i18n/fr/report.json
  client/src/js/services/StockService.js
  client/src/modules/invoices/invoices.routes.js
  client/src/modules/purchases/purchases.routes.js
  client/src/modules/purchases/registry/registry.html
  client/src/modules/purchases/registry/registry.js
  client/src/modules/stock/entry/entry.js
  client/src/modules/stock/movements/templates/action.cell.html
  server/config/routes.js
  server/controllers/finance/purchases.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/reports/purchase_order_analysis/index.js
  server/controllers/stock/reports/stock/entry/entryFromPurchase.js
  server/controllers/stock/reports/stock/entry_purchase_receipt.js
  server/controllers/stock/reports/stock_entry_purchase.receipt.handlebars
  server/models/migrations/next/migrate.sql
  server/models/procedures/stock.sql
  server/models/schema.sql
  test/client-unit/mocks/stock.js
  test/data.sql
  test/data/service-stock.sql
  test/integration/mergeLots.js
Labels: Bug Fix

#5585 Fix permissions for editing roles actions
  client/src/modules/roles/roles.html
Labels: Bug Fix

#5593 fix(purchase): fix delete permissions on purchase
  client/src/modules/purchases/registry/registry.js
  client/src/modules/purchases/templates/action.cell.html
Labels: Bug Fix

#5591 feat(stock): link stock movement transaction
  client/src/modules/journal/journal.service.js
  client/src/modules/stock/movements/templates/action.cell.html
  server/controllers/finance/journal/index.js
Labels: Stock

#5595 Add database port in the database build script
  sh/build-database.sh
  sh/build-init-database.sh
Labels: Build Process
