Repository third-culture-software/bhima, pull requests merged in 2021-12, with the labels that each got.

#6114 Release 1.21.4
  package.json
Labels: Release

#6121 deps: bump dependencies
  yarn.lock
Labels: dependencies

#6122 Release v1.21.5
  package.json
  server/models/migrations/next/migrate.sql
  server/models/migrations/v1.21.1-v1.21.5/migrate.sql
Labels: Release

#6096 Average medication costs per patient report
  client/src/i18n/en/report.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/tree.json
  client/src/modules/reports/generate/avg_med_costs_per_patient/avg_med_costs_per_patient.html
  client/src/modules/reports/generate/avg_med_costs_per_patient/avg_med_costs_per_patient.js
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/stock/reports/common.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/avg_med_costs_per_patient_report.js
  server/controllers/stock/reports/stock_avg_med_costs_per_patient.report.handlebars
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Feature Request

#6156 Hide old cost center menu items and reports
  client/src/i18n/en/tree.json
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Refactor

#6206 chore: update houndci eslint version
  .hound.yml
Labels: Build Process

#6215 fix(journal): ensure cost_center_id exists
  client/src/js/services/TransactionService.js
Labels: Bug Fix

#6209 chore(reports): fixup operating account
  client/src/modules/reports/generate/operating/operating.config.js
  server/controllers/finance/reports/operating/report.handlebars
Labels: Refactor, Report

#6210 fix(reports): add realized_profit report key
  client/src/i18n/en/report.json
  client/src/i18n/en/tree.json
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Bug Fix
