Repository third-culture-software/bhima, pull requests merged in 2022-03, with the labels that each got.

#6434 Small fixes for asset entry
  client/src/modules/inventory/list/templates/asset.cell.tmpl.html
  client/src/modules/stock/assign/modals/action.modal.html
  client/src/modules/stock/entry/entry.js
  client/src/modules/stock/entry/modals/lots.modal.html
  test/data/core.sql
Labels: Asset Tracking

#6437 Delete asset-related data from inventory item when it is not an asset
  client/src/modules/inventory/list/modals/actions.modal.js
  client/src/modules/inventory/list/modals/actions.tmpl.html
Labels: Asset Tracking

#6406 Refactor stock exit for performance and clarity
  client/src/i18n/en/errors.json
  client/src/i18n/en/stock.json
  client/src/i18n/fr/errors.json
  client/src/i18n/fr/stock.json
  client/src/js/components/bhAddItem.js
  client/src/js/components/bhStockExitType.js
  client/src/js/components/bhStockExpired/bhStockExpired.js
  client/src/js/components/bhStockOut/bhStockOut.js
  client/src/js/services/util.js
  client/src/modules/depots/depots.service.js
  client/src/modules/purchases/create/createUpdate.js
  client/src/modules/stock/LotItem.service.js
  client/src/modules/stock/StockEntryExitType.service.js
  client/src/modules/stock/StockExitForm.service.js
  client/src/modules/stock/StockExitFormHelper.service.js
  client/src/modules/stock/StockModal.service.js
  client/src/modules/stock/exit/exit.html
  client/src/modules/stock/exit/exit.js
  client/src/modules/stock/exit/modals/findService.modal.html
  client/src/modules/stock/exit/modals/findService.modal.js
  client/src/modules/stock/exit/templates/actions.tmpl.html
  client/src/modules/stock/exit/templates/amount.tmpl.html
  client/src/modules/stock/exit/templates/available.tmpl.html
  client/src/modules/stock/exit/templates/code.tmpl.html
  client/src/modules/stock/exit/templates/description.tmpl.html
  client/src/modules/stock/exit/templates/expiration.tmpl.html
  client/src/modules/stock/exit/templates/lot.tmpl.html
  client/src/modules/stock/exit/templates/price.tmpl.html
  client/src/modules/stock/exit/templates/quantity.tmpl.html
  client/src/modules/stock/exit/templates/status.tmpl.html
  client/src/modules/stock/exit/templates/unit.tmpl.html
  client/src/modules/vouchers/modals/scanBarcode.modal.js
  server/controllers/inventory/depots/extra.js
  server/controllers/inventory/depots/index.js
  server/controllers/stock/index.js
  server/controllers/stock/requisition/requisition.js
  server/models/procedures/payroll.sql
  server/models/procedures/stock.sql
  server/models/schema.sql
  test/client-unit/services/LotItemService.spec.js
  test/client-unit/services/StockExitFormHelperService.spec.js
  test/client-unit/services/StockExitFormService.spec.js
  test/client-unit/services/util.spec.js
  test/integration-stock/depots.js
  test/integration/stock/stock.js
  yarn.lock
Labels: tests, Stock

#6441 chore: bump ruby dependencies
  docs/Gemfile.lock
Labels: Best Practice, dependencies

#6439 Move reference_number from inventory to lot
  client/src/i18n/en/form.json
  client/src/i18n/fr/form.json
  client/src/js/services/StockService.js
  client/src/modules/inventory/inventory.service.js
  client/src/modules/inventory/list/list.js
  client/src/modules/inventory/list/modals/actions.modal.js
  client/src/modules/inventory/list/modals/actions.tmpl.html
  client/src/modules/stock/StockFilterer.service.js
  client/src/modules/stock/entry/modals/lots.modal.js
  client/src/modules/stock/lots/modals/edit.modal.html
  client/src/modules/stock/lots/modals/search.modal.html
  client/src/modules/stock/lots/modals/search.modal.js
  client/src/modules/stock/lots/registry.service.js
  client/src/modules/stock/lots/templates/reference_number.cell.html
  server/controllers/finance/reports/income_expense/index.js
  server/controllers/inventory/inventory/core.js
  server/controllers/stock/core.js
  server/controllers/stock/index.js
  server/controllers/stock/lots.js
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  test/client-unit/mocks/stock.js
  test/integration/inventory/metadata.js
  test/integration/stock/lots.js
Labels: Asset Tracking
