Repository third-culture-software/bhima, pull requests merged in 2023-08, with the labels that each got.

#7189 chore(payroll): fix typo "payrall"
  server/controllers/payroll/configuration/index.js
  server/models/migrations/v1.14.1-v1.15.0/migrate.sql
  server/models/schema.sql
Labels: Bug Fix, payroll

#7195 deps: remove body-parser
  package.json
  server/config/express.js
  yarn.lock
Labels: dependencies

#7197 test(purchase): checks for missing PO creation
  test/integration/purchase.js
Labels: Bug Fix, tests

#7198 feat(payroll): add service to multiple payroll
  client/src/modules/multiple_payroll/multiple_payroll.js
  client/src/modules/multiple_payroll_indice/multiple_payroll_indice.js
  server/controllers/payroll/multiplePayrollIndice/index.js
Labels: Feature Request, Human Resources, payroll

#7160 chore(reports): remove stock changes report
  client/src/modules/reports/generate/stock_changes/stock_changes.config.js
  client/src/modules/reports/generate/stock_changes/stock_changes.html
  client/src/modules/reports/reports.routes.js
  server/config/routes.js
  server/controllers/stock/reports/index.js
  server/controllers/stock/reports/stock/stock_changes/stock_changes.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Report, chore

#7199 chore: remove odk-central plugin
  client/src/modules/odk-settings/odk-settings.html
  client/src/modules/odk-settings/odk-settings.js
  client/src/modules/odk-settings/odk-settings.routes.js
  client/src/modules/odk-settings/odk-settings.service.js
  package.json
  server/config/routes.js
  server/controllers/admin/odk-central.js
  server/models/bhima.sql
  server/models/migrations/next/migrate.sql
  server/models/schema.sql
  yarn.lock
Labels: Refactor

#7216 fix(odk): clean up all remaining ODK references
  .sqlfluff
  client/src/i18n/en/odk.json
  client/src/i18n/en/tree.json
  client/src/i18n/fr/odk.json
  client/src/i18n/fr/tree.json
  client/src/modules/odk-settings/odk-settings.service.js
  client/src/modules/users/qrcode.modal.html
  client/src/modules/users/qrcode.modal.js
  client/src/modules/users/templates/grid/action.cell.html
  client/src/modules/users/users.js
  docs/en/plugins/odk-central.md
  gulpfile.js/client-vendor.js
  package.json
Labels: dependencies, Bug Fix, chore

#7196 chore(procedures): merge procedures into one file
  .gitignore
  server/controllers/finance/debtors/index.js
  server/models/procedures.sql
  server/models/procedures/account.sql
  server/models/procedures/analysis.sql
  server/models/procedures/cash.sql
  server/models/procedures/cost_centers.sql
  server/models/procedures/inventory.sql
  server/models/procedures/invoicing.sql
  server/models/procedures/location.sql
  server/models/procedures/migration-process.sql
  server/models/procedures/payroll.sql
  server/models/procedures/roles.sql
  server/models/procedures/stock.sql
  server/models/procedures/time_period.sql
  server/models/procedures/trial_balance.sql
  server/models/procedures/voucher.sql
  sh/build-database.sh
  sh/build-init-database.sh
  sh/build-stock-database.sh
  sh/docker-init.sh
  sh/download-latest-release.sh
  sh/install-tests.sh
  sh/integration-stock-tests.sh
  sh/integration-tests.sh
  sh/setup-migration-script.sh
  sh/test.sh
Labels: chore

#7191 Updated BHIMA installation documentation
  docs/en/for-developers/installing-bhima.md
Labels: documentation
