Repository third-culture-software/bhima, pull requests merged in 2024-02, with the labels that each got.

#7460 chore(payroll): fix typos/eslint fixes
  server/controllers/payroll/accounts/index.js
  server/controllers/payroll/employeeConfig/index.js
  server/controllers/payroll/multiplePayroll/manageConfig.js
  server/controllers/payroll/multiplePayrollIndice/index.js
  server/controllers/payroll/multiplePayrollIndice/parameters.config.js
  server/controllers/payroll/rubricConfig/index.js
  server/controllers/payroll/rubrics/index.js
  server/controllers/payroll/rubrics/rubricsIndex.js
  server/controllers/payroll/staffingIndices/report.js
  server/controllers/payroll/weekendConfig/index.js
  server/lib/referenceLookup.js
Labels: chore

#7478 fix: remove '...' from action column headers
  client/src/modules/functions/functions.js
  client/src/modules/prices/modal/createItems.js
  client/src/modules/purchases/detailed/registry.js
  client/src/modules/titles/titles.js
  client/src/modules/vouchers/voucher-registry.ctrl.js
Labels: Best Practice, Refactor

#7386 Improvements to complex vouchers
  client/src/i18n/en/form.json
  client/src/i18n/en/vouchers.json
  client/src/i18n/fr/form.json
  client/src/js/components/bhEntityTypeahead.js
  client/src/js/components/bhRecordTypeahead.js
  client/src/js/services/PrototypeApiService.js
  client/src/modules/accounts/accounts.service.js
  client/src/modules/debtors/debtor.service.js
  client/src/modules/journal/templates/transaction_type.edit.html
  client/src/modules/journal/templates/transaction_type.html
  client/src/modules/templates/bhAccountReferenceSelect.tmpl.html
  client/src/modules/templates/bhAccountTypeaheadInline.html
  client/src/modules/templates/bhEntityTypeahead.html
  client/src/modules/templates/bhRecordTypeahead.html
  client/src/modules/templates/modals/findEntity.modal.html
  client/src/modules/templates/modals/findEntity.modal.js
  client/src/modules/templates/modals/findReference.modal.html
  client/src/modules/templates/modals/findReference.modal.js
  client/src/modules/transaction-type/transaction-type-store.service.js
  client/src/modules/voucher-tools/correct/voucher-tools.correct.component.js
  client/src/modules/vouchers/complex-voucher.ctrl.js
  client/src/modules/vouchers/complex-voucher.html
  client/src/modules/vouchers/find-entity.service.js
  client/src/modules/vouchers/find-reference.service.js
  client/src/modules/vouchers/simple-voucher.ctrl.js
  client/src/modules/vouchers/simple-voucher.html
  client/src/modules/vouchers/templates/entity.grid.tmpl.html
  client/src/modules/vouchers/templates/reference.grid.tmpl.html
  client/src/modules/vouchers/toolkit/advances_loans_installments/advances_loans_installments.js
  client/src/modules/vouchers/toolkit/convention_payment/convention_payment.js
  client/src/modules/vouchers/toolkit/patient_fled/patient_fled.js
  client/src/modules/vouchers/toolkit/payment_employee/payment_employee.js
  client/src/modules/vouchers/toolkit/support_patient/support_patient.js
  client/src/modules/vouchers/voucher-item.service.js
  client/src/modules/vouchers/vouchers.service.js
  server/config/routes.js
  server/controllers/finance/creditors.js
  server/controllers/finance/debtors/index.js
  server/controllers/finance/shared.js
  server/controllers/finance/vouchers.js
  server/controllers/medical/patients/index.js
  test/end-to-end/report
  test/end-to-end/vouchers/complex.spec.js
  test/end-to-end/vouchers/voucherRow.class.js
  test/end-to-end/vouchers/vouchers.spec.js
  test/integration/finance/entities.js
  test/integration/finance/records.js
  test/integration/vouchers.js
Labels: Refactor, Breaking Change

#7490 Clean up after end-to-end tests
  sh/test-e2e-all.sh
Labels: tests

#7486 Budget title subtotals
  client/src/modules/budget/budget.js
  client/src/modules/budget/templates/actuals.cell.html
  client/src/modules/budget/templates/budget.cell.html
  client/src/modules/budget/templates/budgetYTD.cell.html
  client/src/modules/budget/templates/deviationPct.cell.html
  client/src/modules/budget/templates/deviationYTDPct.cell.html
  client/src/modules/budget/templates/differenceYTD.cell.html
  client/src/modules/budget/templates/period_actuals.cell.html
  client/src/modules/budget/templates/period_budget.cell.html
  package.json
  server/controllers/finance/budget/index.js
  server/controllers/finance/reports/budget/budget.handlebars
  yarn.lock
Labels: Feature Request, Budget

#7450 Improve robustness of end-to-end tests
  .gitignore
  sh/test-clean-reports.sh
  test/end-to-end/cash/cash.spec.js
  test/end-to-end/creditorGroups/creditor_groups.spec.js
  test/end-to-end/stock/stock.entry.js
  test/end-to-end/transactionType/transactionType.spec.js
  test/end-to-end/visits/visits.page.js
Labels: tests
