Repository third-culture-software/bhima, pull requests merged in 2024-12, with the labels that each got.

#7900 Fix cashflow report improve budget report
  bash.exe.stackdump
  client/src/i18n/en/form.json
  client/src/i18n/en/report.json
  client/src/i18n/en/table.json
  client/src/i18n/en/vouchers.json
  client/src/i18n/fr/form.json
  client/src/i18n/fr/report.json
  client/src/i18n/fr/table.json
  client/src/i18n/fr/vouchers.json
  client/src/modules/reports/generate/budget_report/budget_report.config.js
  client/src/modules/reports/generate/budget_report/budget_report.html
  client/src/modules/reports/generate/cashflow/cashflow.html
  package-lock.json
  server/controllers/finance/reports/budget_analytical/index.js
  server/controllers/finance/reports/budget_analytical/report.handlebars
  server/controllers/finance/reports/cashflow/index.js
  server/controllers/finance/reports/cashflow/reportGlobal.handlebars
  server/controllers/finance/reports/cashflow/reportSynthetic.handlebars
  server/models/06-bhima.sql
  server/models/migrations/next/migrate.sql
  test/data.sql
  test/end-to-end/account/accountReferenceType/accountReferenceType.spec.js
  test/end-to-end/editJournal/edit_journal.spec.js
  test/end-to-end/journal/SearchModal.tests.js
  test/fixtures/budget-to-import.csv
  test/integration/accountReferenceType.js
  test/integration/accounts.js
  test/integration/budget/import.js
  test/integration/debtorGroups.js
  test/integration/finance/records.js
  test/integration/journal.js
  test/integration/transactionType.js
  test/integration/vouchers.js
Labels: Feature Request, Report

#7933 chore: clean up bash scripts
  sh/debian-install.sh
  sh/download-latest-release.sh
  sh/prot2play
  sh/setup-migration-script.sh
  sh/test-e2e-all.sh
  sh/test-show-results.sh
  sh/test.sh
  sh/travis.sh
Labels: Technical Debt

#7938 refactor(*): replace JSON.parse/JSON.stringify with structuredClone
  .eslintrc.json
  server/controllers/finance/indicator/dashboard/process.js
  server/lib/template/helpers/finance.js
  test/integration/helpers.js
Labels: Technical Debt

#7944 refactor(payroll): replace "date_embauche" with"hiring_date"
  client/src/modules/employees/registration/employees.html
  client/src/modules/employees/registration/employees.js
  client/src/modules/employees/registry/registry.js
  server/controllers/payroll/configuration/index.js
  server/controllers/payroll/employees/index.js
  server/controllers/payroll/multiplePayroll/find.js
  server/controllers/payroll/multiplePayroll/payrollSettings.js
  server/controllers/payroll/multiplePayroll/setConfiguration.js
  server/controllers/payroll/multiplePayrollIndice/parameters.config.js
  server/controllers/payroll/reports/payslipGenerator.handlebars
  server/controllers/payroll/reports/registrations.handlebars
  server/models/01-schema.sql
  server/models/03-procedures.sql
  server/models/migrations/next/migrate.sql
  test/data.sql
  test/end-to-end/employees/registration.page.js
  test/end-to-end/employees/registration.spec.js
  test/integration/employee.js
  test/integration/payroll.js
Labels: Refactor, Human Resources

#7949 chore(HR): correct HR spelling in dictionary.
  client/src/i18n/en/tree.json
  client/src/i18n/fr/tree.json
  client/src/modules/employees/registration/employees.html
  client/src/modules/employees/registry/registry.html
  client/src/modules/functions/functions.html
  client/src/modules/functions/modals/function.modal.html
  client/src/modules/grades/grades.html
  client/src/modules/grades/modals/grade.modal.html
  client/src/modules/holidays/holidays.html
  client/src/modules/holidays/modals/holiday.modal.html
  client/src/modules/ipr_tax/configuration/iprTaxConfig.html
  client/src/modules/ipr_tax/ipr_tax.html
  client/src/modules/multiple_payroll/modals/config.modal.html
  client/src/modules/multiple_payroll/modals/search.modal.html
  client/src/modules/multiple_payroll/modals/waitingListConfirmation.html
  client/src/modules/multiple_payroll/multiple_payroll.html
  client/src/modules/multiple_payroll_indice/modals/config.modal.html
  client/src/modules/multiple_payroll_indice/modals/import.modal.html
  client/src/modules/multiple_payroll_indice/modals/parameter.modal.html
  client/src/modules/multiple_payroll_indice/modals/search.modal.html
  client/src/modules/multiple_payroll_indice/multiple_payroll_indice.html
  client/src/modules/offdays/offdays.html
  client/src/modules/payroll/account_configuration/configuration.html
  client/src/modules/payroll/account_configuration/modals/account.modal.html
  client/src/modules/payroll/employee_configuration/configuration.html
  client/src/modules/payroll/employee_configuration/modals/employee.modal.html
  client/src/modules/payroll/modals/payroll.modal.html
  client/src/modules/payroll/payroll.html
  client/src/modules/payroll/rubric_configuration/configuration.html
  client/src/modules/payroll/rubric_configuration/configuration.js
  client/src/modules/payroll/rubric_configuration/modals/config.modal.html
  client/src/modules/payroll/rubric_configuration/modals/rubric.modal.html
  client/src/modules/payroll/rubrics/modals/rubric.modal.html
  client/src/modules/payroll/rubrics/rubrics.html
  client/src/modules/payroll/settings/settings.html
  client/src/modules/payroll/staffing_indice/modal/createUpdate.html
  client/src/modules/payroll/staffing_indice/modal/funcitonIndiceModal.html
  client/src/modules/payroll/staffing_indice/modal/gradeIndiceModal.html
  client/src/modules/payroll/staffing_indice/modal/search.modal.html
  client/src/modules/payroll/staffing_indice/staffingIndice.html
  client/src/modules/payroll/weekend_configuration/configuration.html
  client/src/modules/payroll/weekend_configuration/modals/weekEnd.modal.html
  client/src/modules/titles/titles.html
  server/models/06-bhima.sql
  server/models/migrations/next/migrate.sql
Labels: Human Resources
