Repository third-culture-software/bhima, pull requests merged in 2024-03, with the labels that each got.

#7532 Fix integration stock tests
  test/data/core.sql
Labels: tests

#7528 fix(journal): sanitize added account props
  client/src/modules/journal/journal.service.js
Labels: Bug Fix

#7529 Fix rendering of installation docs
  docs/en/for-developers/installing-bhima.md
Labels: documentation
